// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Determines how a batch transaction handles failed calls.
/// </summary>
public enum BatchTransactionModeEnum
{
    [EnumMember(Value = "HALT_ON_ERROR")] HaltOnError,
    [EnumMember(Value = "CONTINUE_ON_ERROR")] ContinueOnError,
    [EnumMember(Value = "ALL_OR_NOTHING")] AllOrNothing
}

