// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The response to a counter offer: Accept, Reject, or Counter with a new price.
/// </summary>
public enum CounterOfferResponseEnum
{
    [EnumMember(Value = "ACCEPT")] Accept,
    [EnumMember(Value = "REJECT")] Reject,
    [EnumMember(Value = "COUNTER")] Counter
}

