// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A pallet that a fuel tank rule set may whitelist, allowing any of its calls.
/// </summary>
public enum FuelTankWhitelistedPallet
{
    [EnumMember(Value = "MULTI_TOKENS")] MultiTokens,
    [EnumMember(Value = "BALANCES")] Balances,
    [EnumMember(Value = "MARKETPLACE")] Marketplace,
    [EnumMember(Value = "UTILITY")] Utility
}

