// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A transaction method that a fuel tank rule set may permit. Identifies the pallet and extrinsic; the call arguments are irrelevant on-chain.
/// </summary>
public enum FuelTankPermittedMethod
{
    [EnumMember(Value = "CREATE_COLLECTION")] CreateCollection,
    [EnumMember(Value = "DESTROY_COLLECTION")] DestroyCollection,
    [EnumMember(Value = "MUTATE_COLLECTION")] MutateCollection,
    [EnumMember(Value = "MUTATE_TOKEN")] MutateToken,
    [EnumMember(Value = "CREATE_TOKEN")] CreateToken,
    [EnumMember(Value = "MINT_TOKEN")] MintToken,
    [EnumMember(Value = "TRANSFER_TOKEN")] TransferToken,
    [EnumMember(Value = "CREATE_TOKENS")] CreateTokens,
    [EnumMember(Value = "MINT_TOKENS")] MintTokens,
    [EnumMember(Value = "BATCH_TRANSFER")] BatchTransfer,
    [EnumMember(Value = "FREEZE_COLLECTION")] FreezeCollection,
    [EnumMember(Value = "THAW_COLLECTION")] ThawCollection,
    [EnumMember(Value = "FREEZE_TOKEN")] FreezeToken,
    [EnumMember(Value = "THAW_TOKEN")] ThawToken,
    [EnumMember(Value = "BURN_TOKEN")] BurnToken,
    [EnumMember(Value = "INFUSE_TOKEN")] InfuseToken,
    [EnumMember(Value = "INFUSE_TOKENS")] InfuseTokens,
    [EnumMember(Value = "TRANSFER_ENJ")] TransferEnj,
    [EnumMember(Value = "CREATE_LISTING")] CreateListing,
    [EnumMember(Value = "CANCEL_LISTING")] CancelListing,
    [EnumMember(Value = "FILL_LISTING")] FillListing,
    [EnumMember(Value = "FINALIZE_AUCTION")] FinalizeAuction,
    [EnumMember(Value = "ADD_WHITELISTED_ACCOUNTS")] AddWhitelistedAccounts,
    [EnumMember(Value = "REMOVE_WHITELISTED_ACCOUNTS")] RemoveWhitelistedAccounts,
    [EnumMember(Value = "PLACE_BID")] PlaceBid,
    [EnumMember(Value = "PLACE_COUNTER_OFFER")] PlaceCounterOffer,
    [EnumMember(Value = "ANSWER_COUNTER_OFFER")] AnswerCounterOffer,
    [EnumMember(Value = "CREATE_TOKEN_GROUP")] CreateTokenGroup,
    [EnumMember(Value = "DESTROY_TOKEN_GROUP")] DestroyTokenGroup,
    [EnumMember(Value = "ADD_TOKEN_TO_GROUP")] AddTokenToGroup,
    [EnumMember(Value = "REMOVE_TOKEN_FROM_GROUP")] RemoveTokenFromGroup,
    [EnumMember(Value = "SET_TOKEN_GROUPS")] SetTokenGroups,
    [EnumMember(Value = "SET_TOKEN_GROUP_ATTRIBUTE")] SetTokenGroupAttribute,
    [EnumMember(Value = "REMOVE_TOKEN_GROUP_ATTRIBUTE")] RemoveTokenGroupAttribute,
    [EnumMember(Value = "SET_TOKEN_ATTRIBUTE")] SetTokenAttribute,
    [EnumMember(Value = "SET_COLLECTION_ATTRIBUTE")] SetCollectionAttribute,
    [EnumMember(Value = "REMOVE_TOKEN_ATTRIBUTE")] RemoveTokenAttribute,
    [EnumMember(Value = "REMOVE_COLLECTION_ATTRIBUTE")] RemoveCollectionAttribute,
    [EnumMember(Value = "BATCH_SET_COLLECTION_ATTRIBUTE")] BatchSetCollectionAttribute,
    [EnumMember(Value = "BATCH_SET_TOKEN_ATTRIBUTE")] BatchSetTokenAttribute,
    [EnumMember(Value = "REMOVE_ALL_COLLECTION_ATTRIBUTES")] RemoveAllCollectionAttributes,
    [EnumMember(Value = "REMOVE_ALL_TOKEN_ATTRIBUTES")] RemoveAllTokenAttributes,
    [EnumMember(Value = "ACCEPT_COLLECTION_TRANSFER")] AcceptCollectionTransfer,
    [EnumMember(Value = "CANCEL_COLLECTION_TRANSFER")] CancelCollectionTransfer,
    [EnumMember(Value = "APPROVE_COLLECTION")] ApproveCollection,
    [EnumMember(Value = "UNAPPROVE_COLLECTION")] UnapproveCollection
}

