// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The sweep status of a managed wallet: SWEPT once emptied of transferable tokens, PENDING while any remain.
/// </summary>
public enum ManagedWalletSweepStatusEnum
{
    [EnumMember(Value = "PENDING")] Pending,
    [EnumMember(Value = "SWEPT")] Swept
}

