// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The blockchain network to query.
/// </summary>
public enum Network
{
    [EnumMember(Value = "CANARY")] Canary,
    [EnumMember(Value = "ENJIN")] Enjin
}

