// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The state of a nomination pool.
/// </summary>
public enum PoolStateEnum
{
    [EnumMember(Value = "OPEN")] Open,
    [EnumMember(Value = "BLOCKED")] Blocked,
    [EnumMember(Value = "DESTROYING")] Destroying,
    [EnumMember(Value = "DESTROYED")] Destroyed
}

