// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// How to apply an optional mutation field on the fuel tank. NO_MUTATION keeps the existing value; CLEAR sets it to None; SET requires a value and applies it.
/// </summary>
public enum ShouldMutateAction
{
    [EnumMember(Value = "NO_MUTATION")] NoMutation,
    [EnumMember(Value = "CLEAR")] Clear,
    [EnumMember(Value = "SET")] Set
}

