// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The state of a transaction.
/// </summary>
public enum TransactionStateEnum
{
    [EnumMember(Value = "PENDING")] Pending,
    [EnumMember(Value = "BROADCAST")] Broadcast,
    [EnumMember(Value = "FINALIZED")] Finalized,
    [EnumMember(Value = "FAILED")] Failed,
    [EnumMember(Value = "ABANDONED")] Abandoned,
    [EnumMember(Value = "TIMEOUT")] Timeout
}

