// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public static class GraphQlTypes
{
    public const string BigInt = "BigInt";
    public const string Boolean = "Boolean";
    public const string Float = "Float";
    public const string Int = "Int";
    public const string Json = "JSON";
    public const string String = "String";

    public const string Chain = "Chain";
    public const string CounterOfferResponseEnum = "CounterOfferResponseEnum";
    public const string FreezeState = "FreezeState";
    public const string ListingTypeEnum = "ListingTypeEnum";
    public const string Network = "Network";
    public const string PoolStateEnum = "PoolStateEnum";
    public const string TokenBehaviorType = "TokenBehaviorType";
    public const string TokenCapType = "TokenCapType";
    public const string TransactionStateEnum = "TransactionStateEnum";

    public const string Account = "Account";
    public const string AccountPool = "AccountPool";
    public const string AccountToken = "AccountToken";
    public const string Attribute = "Attribute";
    public const string Block = "Block";
    public const string Collection = "Collection";
    public const string CollectionHolder = "CollectionHolder";
    public const string Event = "Event";
    public const string Extrinsic = "Extrinsic";
    public const string Listing = "Listing";
    public const string ManagedWallet = "ManagedWallet";
    public const string ManagedWalletCursorPagination = "ManagedWalletCursorPagination";
    public const string MarketPolicy = "MarketPolicy";
    public const string Metadata = "Metadata";
    public const string MetadataMedia = "MetadataMedia";
    public const string MetadataMeta = "MetadataMeta";
    public const string MintPolicy = "MintPolicy";
    public const string Mutation = "Mutation";
    public const string NominationPool = "NominationPool";
    public const string PendingCollection = "PendingCollection";
    public const string PoolBalance = "PoolBalance";
    public const string PoolMember = "PoolMember";
    public const string Query = "Query";
    public const string RoyaltyBeneficiary = "RoyaltyBeneficiary";
    public const string RoyaltyCurrency = "RoyaltyCurrency";
    public const string Token = "Token";
    public const string TokenBehavior = "TokenBehavior";
    public const string TokenCap = "TokenCap";
    public const string TokenGroup = "TokenGroup";
    public const string TokenGroupToken = "TokenGroupToken";
    public const string TokenHolder = "TokenHolder";
    public const string Transaction = "Transaction";
    public const string TransactionCursorPagination = "TransactionCursorPagination";
    public const string TransferPolicy = "TransferPolicy";

    public const string AcceptCollectionTransferInput = "AcceptCollectionTransferInput";
    public const string AddTokenToGroupInput = "AddTokenToGroupInput";
    public const string AddWhitelistedAccountsInput = "AddWhitelistedAccountsInput";
    public const string AnswerCounterOfferInput = "AnswerCounterOfferInput";
    public const string AssetIdInput = "AssetIdInput";
    public const string AttributeInput = "AttributeInput";
    public const string BatchSetCollectionAttributeInput = "BatchSetCollectionAttributeInput";
    public const string BatchSetTokenAttributeInput = "BatchSetTokenAttributeInput";
    public const string BatchTransferInput = "BatchTransferInput";
    public const string BurnTokenInput = "BurnTokenInput";
    public const string CancelCollectionTransferInput = "CancelCollectionTransferInput";
    public const string CancelListingInput = "CancelListingInput";
    public const string CreateCollectionInput = "CreateCollectionInput";
    public const string CreateListingInput = "CreateListingInput";
    public const string CreateTokenEntryInput = "CreateTokenEntryInput";
    public const string CreateTokenGroupInput = "CreateTokenGroupInput";
    public const string CreateTokenInput = "CreateTokenInput";
    public const string CreateTokensInput = "CreateTokensInput";
    public const string DestroyCollectionInput = "DestroyCollectionInput";
    public const string DestroyTokenGroupInput = "DestroyTokenGroupInput";
    public const string FillListingInput = "FillListingInput";
    public const string FinalizeAuctionInput = "FinalizeAuctionInput";
    public const string FreezeCollectionInput = "FreezeCollectionInput";
    public const string FreezeTokenInput = "FreezeTokenInput";
    public const string InfuseTokenEntryInput = "InfuseTokenEntryInput";
    public const string InfuseTokenInput = "InfuseTokenInput";
    public const string InfuseTokensInput = "InfuseTokensInput";
    public const string ListingDataInput = "ListingDataInput";
    public const string MintTokenEntryInput = "MintTokenEntryInput";
    public const string MintTokenInput = "MintTokenInput";
    public const string MintTokensInput = "MintTokensInput";
    public const string MutateCollectionInput = "MutateCollectionInput";
    public const string MutateTokenInput = "MutateTokenInput";
    public const string NominationPoolsBondInput = "NominationPoolsBondInput";
    public const string NominationPoolsUnbondInput = "NominationPoolsUnbondInput";
    public const string PlaceBidInput = "PlaceBidInput";
    public const string PlaceCounterOfferInput = "PlaceCounterOfferInput";
    public const string RemoveAllCollectionAttributesInput = "RemoveAllCollectionAttributesInput";
    public const string RemoveAllTokenAttributesInput = "RemoveAllTokenAttributesInput";
    public const string RemoveCollectionAttributeInput = "RemoveCollectionAttributeInput";
    public const string RemoveTokenAttributeInput = "RemoveTokenAttributeInput";
    public const string RemoveTokenFromGroupInput = "RemoveTokenFromGroupInput";
    public const string RemoveTokenGroupAttributeInput = "RemoveTokenGroupAttributeInput";
    public const string RemoveWhitelistedAccountsInput = "RemoveWhitelistedAccountsInput";
    public const string RoyaltyCurrencyInput = "RoyaltyCurrencyInput";
    public const string RoyaltyInput = "RoyaltyInput";
    public const string SetCollectionAttributeInput = "SetCollectionAttributeInput";
    public const string SetTokenAttributeInput = "SetTokenAttributeInput";
    public const string SetTokenGroupAttributeInput = "SetTokenGroupAttributeInput";
    public const string SetTokenGroupsInput = "SetTokenGroupsInput";
    public const string ThawCollectionInput = "ThawCollectionInput";
    public const string ThawTokenInput = "ThawTokenInput";
    public const string TokenBehaviorInput = "TokenBehaviorInput";
    public const string TokenCapInput = "TokenCapInput";
    public const string TransactionInput = "TransactionInput";
    public const string TransferEnjInput = "TransferEnjInput";
    public const string TransferTokenEntryInput = "TransferTokenEntryInput";
    public const string TransferTokenInput = "TransferTokenInput";
    public const string WhitelistedAccountInput = "WhitelistedAccountInput";

    public static readonly IReadOnlyDictionary<global::System.Type, string> ReverseMapping =
        new Dictionary<global::System.Type, string>
        {
            { typeof(string), "String" },
            { typeof(int), "Int" },
            { typeof(global::System.Numerics.BigInteger), "BigInt" },
            { typeof(decimal), "Float" },
            { typeof(DateTimeOffset), "String" },
            { typeof(bool), "Boolean" },
            { typeof(AcceptCollectionTransferInput), "AcceptCollectionTransferInput" },
            { typeof(AddTokenToGroupInput), "AddTokenToGroupInput" },
            { typeof(AddWhitelistedAccountsInput), "AddWhitelistedAccountsInput" },
            { typeof(AnswerCounterOfferInput), "AnswerCounterOfferInput" },
            { typeof(AssetIdInput), "AssetIdInput" },
            { typeof(AttributeInput), "AttributeInput" },
            { typeof(BatchSetCollectionAttributeInput), "BatchSetCollectionAttributeInput" },
            { typeof(BatchSetTokenAttributeInput), "BatchSetTokenAttributeInput" },
            { typeof(BatchTransferInput), "BatchTransferInput" },
            { typeof(BurnTokenInput), "BurnTokenInput" },
            { typeof(CancelCollectionTransferInput), "CancelCollectionTransferInput" },
            { typeof(CancelListingInput), "CancelListingInput" },
            { typeof(CreateCollectionInput), "CreateCollectionInput" },
            { typeof(CreateListingInput), "CreateListingInput" },
            { typeof(CreateTokenEntryInput), "CreateTokenEntryInput" },
            { typeof(CreateTokenGroupInput), "CreateTokenGroupInput" },
            { typeof(CreateTokenInput), "CreateTokenInput" },
            { typeof(CreateTokensInput), "CreateTokensInput" },
            { typeof(DestroyCollectionInput), "DestroyCollectionInput" },
            { typeof(DestroyTokenGroupInput), "DestroyTokenGroupInput" },
            { typeof(FillListingInput), "FillListingInput" },
            { typeof(FinalizeAuctionInput), "FinalizeAuctionInput" },
            { typeof(FreezeCollectionInput), "FreezeCollectionInput" },
            { typeof(FreezeTokenInput), "FreezeTokenInput" },
            { typeof(InfuseTokenEntryInput), "InfuseTokenEntryInput" },
            { typeof(InfuseTokenInput), "InfuseTokenInput" },
            { typeof(InfuseTokensInput), "InfuseTokensInput" },
            { typeof(ListingDataInput), "ListingDataInput" },
            { typeof(MintTokenEntryInput), "MintTokenEntryInput" },
            { typeof(MintTokenInput), "MintTokenInput" },
            { typeof(MintTokensInput), "MintTokensInput" },
            { typeof(MutateCollectionInput), "MutateCollectionInput" },
            { typeof(MutateTokenInput), "MutateTokenInput" },
            { typeof(NominationPoolsBondInput), "NominationPoolsBondInput" },
            { typeof(NominationPoolsUnbondInput), "NominationPoolsUnbondInput" },
            { typeof(PlaceBidInput), "PlaceBidInput" },
            { typeof(PlaceCounterOfferInput), "PlaceCounterOfferInput" },
            { typeof(RemoveAllCollectionAttributesInput), "RemoveAllCollectionAttributesInput" },
            { typeof(RemoveAllTokenAttributesInput), "RemoveAllTokenAttributesInput" },
            { typeof(RemoveCollectionAttributeInput), "RemoveCollectionAttributeInput" },
            { typeof(RemoveTokenAttributeInput), "RemoveTokenAttributeInput" },
            { typeof(RemoveTokenFromGroupInput), "RemoveTokenFromGroupInput" },
            { typeof(RemoveTokenGroupAttributeInput), "RemoveTokenGroupAttributeInput" },
            { typeof(RemoveWhitelistedAccountsInput), "RemoveWhitelistedAccountsInput" },
            { typeof(RoyaltyCurrencyInput), "RoyaltyCurrencyInput" },
            { typeof(RoyaltyInput), "RoyaltyInput" },
            { typeof(SetCollectionAttributeInput), "SetCollectionAttributeInput" },
            { typeof(SetTokenAttributeInput), "SetTokenAttributeInput" },
            { typeof(SetTokenGroupAttributeInput), "SetTokenGroupAttributeInput" },
            { typeof(SetTokenGroupsInput), "SetTokenGroupsInput" },
            { typeof(ThawCollectionInput), "ThawCollectionInput" },
            { typeof(ThawTokenInput), "ThawTokenInput" },
            { typeof(TokenBehaviorInput), "TokenBehaviorInput" },
            { typeof(TokenCapInput), "TokenCapInput" },
            { typeof(TransactionInput), "TransactionInput" },
            { typeof(TransferEnjInput), "TransferEnjInput" },
            { typeof(TransferTokenEntryInput), "TransferTokenEntryInput" },
            { typeof(TransferTokenInput), "TransferTokenInput" },
            { typeof(WhitelistedAccountInput), "WhitelistedAccountInput" }
        };
}

