// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A token held by an account, paired with the account's balance for that token.
/// </summary>
public partial class AccountToken
{
    /// <summary>
    /// The account's balance of this token.
    /// </summary>
    public global::System.Numerics.BigInteger Balance { get; set; }
    /// <summary>
    /// The token itself.
    /// </summary>
    public Token? Token { get; set; }
}

