// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A nomination pool that an account is bonded into.
/// </summary>
public partial class AccountPool
{
    /// <summary>
    /// The pool identifier.
    /// </summary>
    public int? Id { get; set; }
    /// <summary>
    /// The pool name.
    /// </summary>
    public string? Name { get; set; }
    /// <summary>
    /// Current pool state.
    /// </summary>
    public PoolStateEnum? State { get; set; }
    /// <summary>
    /// Amount of sENJ bonded, expressed as ENJ.
    /// </summary>
    public string Bonded { get; set; }
    /// <summary>
    /// Accumulated unrealised ENJ rewards, expressed as ENJ.
    /// </summary>
    public string UnrealisedEnj { get; set; }
    /// <summary>
    /// Total ENJ currently being unbonded (sum of all unbonding eras), expressed as ENJ.
    /// </summary>
    public string TotalUnbonding { get; set; }
    /// <summary>
    /// Pool annual percentage yield.
    /// </summary>
    public decimal? Apy { get; set; }
}

