// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A key-value attribute on a token or collection.
/// </summary>
public partial class Attribute
{
    /// <summary>
    /// The attribute key.
    /// </summary>
    public string? Key { get; set; }
    /// <summary>
    /// The attribute value.
    /// </summary>
    public string? Value { get; set; }
}

