// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A blockchain block.
/// </summary>
public partial class Block
{
    /// <summary>
    /// The block number.
    /// </summary>
    public int? Number { get; set; }
    /// <summary>
    /// The block hash.
    /// </summary>
    public string? Hash { get; set; }
    /// <summary>
    /// The block validator public key.
    /// </summary>
    public string? Validator { get; set; }
    /// <summary>
    /// The extrinsics in this block.
    /// </summary>
    public ICollection<Extrinsic?>? Extrinsics { get; set; }
    /// <summary>
    /// The block creation time.
    /// </summary>
    public DateTimeOffset? CreatedAt { get; set; }
}

