// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A token collection on the blockchain.
/// </summary>
public partial class Collection
{
    /// <summary>
    /// The collection ID.
    /// </summary>
    public global::System.Numerics.BigInteger Id { get; set; }
    /// <summary>
    /// The collection owner.
    /// </summary>
    public Account? Owner { get; set; }
    /// <summary>
    /// The collection attributes.
    /// </summary>
    public ICollection<Attribute?>? Attributes { get; set; }
    /// <summary>
    /// The collection metadata.
    /// </summary>
    public Metadata? Metadata { get; set; }
    /// <summary>
    /// The minting policy.
    /// </summary>
    public MintPolicy? MintPolicy { get; set; }
    /// <summary>
    /// The marketplace policy.
    /// </summary>
    public MarketPolicy? MarketPolicy { get; set; }
    /// <summary>
    /// The transfer policy.
    /// </summary>
    public TransferPolicy? TransferPolicy { get; set; }
    /// <summary>
    /// The account the collection ownership is pending transfer to, if any.
    /// </summary>
    public Account? PendingTransfer { get; set; }
    /// <summary>
    /// The token groups defined in this collection.
    /// </summary>
    public ICollection<TokenGroup>? TokenGroups { get; set; }
    /// <summary>
    /// The holders of tokens in this collection. The effective per-page limit depends on context: up to 100 when fetched via GetCollection (detail), up to 10 when fetched via GetCollections (bulk).
    /// </summary>
    public ICollection<CollectionHolder>? Holders { get; set; }
}

