// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A fuel tank that is compatible with a transaction call.
/// </summary>
public partial class CompatibleFuelTank
{
    /// <summary>
    /// The fuel tank address (public key).
    /// </summary>
    public string? Id { get; set; }
    /// <summary>
    /// The fuel tank display name.
    /// </summary>
    public string? Name { get; set; }
    /// <summary>
    /// The fuel tank account address.
    /// </summary>
    public string? Address { get; set; }
    /// <summary>
    /// Whether the tank covers the storage deposit in addition to fees.
    /// </summary>
    public bool? ProvidesDeposit { get; set; }
    /// <summary>
    /// Whether the tank covers fees only (FEES) or also the storage deposit (FEES_AND_DEPOSIT).
    /// </summary>
    public CoveragePolicy? CoveragePolicy { get; set; }
    /// <summary>
    /// The rule set that makes this tank compatible.
    /// </summary>
    public CompatibleFuelTankRuleSet? RuleSet { get; set; }
    /// <summary>
    /// Free balance of the tank account, expressed as ENJ.
    /// </summary>
    public string? TankBalance { get; set; }
    /// <summary>
    /// The amount available to fund this transaction, expressed as ENJ.
    /// </summary>
    public string AvailableBudget { get; set; }
}

