// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The rule set matched for a compatible fuel tank.
/// </summary>
public partial class CompatibleFuelTankRuleSet
{
    /// <summary>
    /// The opaque rule set id.
    /// </summary>
    public string? Id { get; set; }
    /// <summary>
    /// The numeric index of the rule set on the tank.
    /// </summary>
    public int? Index { get; set; }
}

