// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A blockchain event.
/// </summary>
public partial class Event
{
    /// <summary>
    /// The event ID.
    /// </summary>
    public string? Id { get; set; }
    /// <summary>
    /// The human-readable event name (pallet and method with spaces).
    /// </summary>
    public string? Name { get; set; }
    /// <summary>
    /// The related collection ID.
    /// </summary>
    public global::System.Numerics.BigInteger? CollectionId { get; set; }
    /// <summary>
    /// The related token ID.
    /// </summary>
    public string? TokenId { get; set; }
    /// <summary>
    /// The raw event data payload.
    /// </summary>
    public string? Data { get; set; }
}

