// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// An on-chain extrinsic (transaction).
/// </summary>
public partial class Extrinsic
{
    /// <summary>
    /// The extrinsic ID (blockNumber-extrinsicIndex).
    /// </summary>
    public string? Id { get; set; }
    /// <summary>
    /// The extrinsic hash.
    /// </summary>
    public string? Hash { get; set; }
    /// <summary>
    /// The block containing this extrinsic.
    /// </summary>
    public Block? Block { get; set; }
    /// <summary>
    /// Whether the extrinsic succeeded.
    /// </summary>
    public bool? Success { get; set; }
    /// <summary>
    /// The pallet (module) called.
    /// </summary>
    public string? Pallet { get; set; }
    /// <summary>
    /// The method (call) name.
    /// </summary>
    public string? Method { get; set; }
    /// <summary>
    /// The account that signed the extrinsic.
    /// </summary>
    public Account? Signer { get; set; }
    /// <summary>
    /// The signer nonce.
    /// </summary>
    public int? Nonce { get; set; }
    /// <summary>
    /// The error message if failed.
    /// </summary>
    public string? Error { get; set; }
    /// <summary>
    /// The events in this extrinsic.
    /// </summary>
    public ICollection<Event?>? Events { get; set; }
}

