// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A capped amount of fuel that resets every resetPeriod blocks.
/// </summary>
public partial class FuelBudget
{
    /// <summary>
    /// The maximum fuel spend per reset period, expressed as ENJ.
    /// </summary>
    public string? Amount { get; set; }
    /// <summary>
    /// The number of blocks after which the budget refills.
    /// </summary>
    public global::System.Numerics.BigInteger? ResetPeriod { get; set; }
}

