// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A user account registered on a fuel tank.
/// </summary>
public partial class FuelTankAccount
{
    /// <summary>
    /// The address of the account registered on the tank (public key).
    /// </summary>
    public string? Address { get; set; }
}

