// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// An account rule applied when a user account is added to the tank. Exactly one of the variant fields is populated per row.
/// </summary>
public partial class FuelTankAccountRule
{
    /// <summary>
    /// Only these caller addresses may be added as user accounts.
    /// </summary>
    public ICollection<string>? WhitelistedCallers { get; set; }
    /// <summary>
    /// Caller must hold the referenced token to be added as a user account.
    /// </summary>
    public RequireToken? RequireToken { get; set; }
}

