// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A fuel tank on the FuelTanks pallet, including its rule sets and account rules.
/// </summary>
public partial class FuelTank
{
    /// <summary>
    /// The fuel tank address (public key).
    /// </summary>
    public string? Id { get; set; }
    /// <summary>
    /// The fuel tank display name.
    /// </summary>
    public string? Name { get; set; }
    /// <summary>
    /// The address of the fuel tank owner.
    /// </summary>
    public string? Owner { get; set; }
    /// <summary>
    /// Whether the tank covers transaction fees only (FEES) or also the storage deposit (FEES_AND_DEPOSIT).
    /// </summary>
    public CoveragePolicy? CoveragePolicy { get; set; }
    /// <summary>
    /// Whether the fuel tank is frozen (no calls can be dispatched).
    /// </summary>
    public bool? IsFrozen { get; set; }
    /// <summary>
    /// The number of user accounts currently registered on the tank.
    /// </summary>
    public int? AccountCount { get; set; }
    /// <summary>
    /// The on-chain account holding ENJ funds for this fuel tank.
    /// </summary>
    public Account? TankAccount { get; set; }
    /// <summary>
    /// User-account deposit settings, or null if the tank does not manage user deposits.
    /// </summary>
    public FuelTankUserAccountManagement? UserAccountManagement { get; set; }
    /// <summary>
    /// Account rules applied to all user accounts on this tank.
    /// </summary>
    public ICollection<FuelTankAccountRule>? AccountRules { get; set; }
    /// <summary>
    /// Rule sets defined on this tank, each with a numeric id and a list of dispatch rules.
    /// </summary>
    public ICollection<FuelTankRuleSet>? RuleSets { get; set; }
}

