// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A specific permitted extrinsic on a fuel tank rule set, identified by pallet and extrinsic name.
/// </summary>
public partial class FuelTankPermittedExtrinsic
{
    /// <summary>
    /// The pallet name of the permitted extrinsic.
    /// </summary>
    public string? PalletName { get; set; }
    /// <summary>
    /// The extrinsic name within the pallet.
    /// </summary>
    public string? ExtrinsicName { get; set; }
}

