// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A rule set on a fuel tank, with its numeric id and the dispatch rules that apply to calls made under it.
/// </summary>
public partial class FuelTankRuleSet
{
    /// <summary>
    /// The numeric id of this rule set on the fuel tank.
    /// </summary>
    public int? Id { get; set; }
    /// <summary>
    /// Whether the rule set is frozen (cannot be used).
    /// </summary>
    public bool? IsFrozen { get; set; }
    /// <summary>
    /// If true, only registered user accounts may use this rule set.
    /// </summary>
    public bool? RequireAccount { get; set; }
    /// <summary>
    /// If set, calls under this rule set must include a signature from this signer address.
    /// </summary>
    public string? RequireSignature { get; set; }
    /// <summary>
    /// Only these caller addresses may use this rule set.
    /// </summary>
    public ICollection<string>? WhitelistedCallers { get; set; }
    /// <summary>
    /// Only calls targeting these collection ids are permitted.
    /// </summary>
    public ICollection<global::System.Numerics.BigInteger?>? WhitelistedCollections { get; set; }
    /// <summary>
    /// Only calls targeting these pallets are permitted.
    /// </summary>
    public ICollection<FuelTankWhitelistedPallet>? WhitelistedPallets { get; set; }
    /// <summary>
    /// Maximum fuel that any single transaction under this rule set may burn, expressed as ENJ.
    /// </summary>
    public string? MaxFuelBurnPerTransaction { get; set; }
    /// <summary>
    /// Minimum amount that must be infused into the fuel tank for this rule set to take effect, expressed as ENJ.
    /// </summary>
    public string? MinimumInfusion { get; set; }
    /// <summary>
    /// Per-user fuel budget that resets every resetPeriod blocks.
    /// </summary>
    public FuelBudget? UserFuelBudget { get; set; }
    /// <summary>
    /// Tank-wide fuel budget that resets every resetPeriod blocks.
    /// </summary>
    public FuelBudget? TankFuelBudget { get; set; }
    /// <summary>
    /// Callers must hold the referenced token to use this rule set.
    /// </summary>
    public RequireToken? RequireToken { get; set; }
    /// <summary>
    /// Permitted call hashes (0x-prefixed blake2_256 hex digests).
    /// </summary>
    public ICollection<string>? PermittedCalls { get; set; }
    /// <summary>
    /// Only these specific extrinsics are permitted under this rule set.
    /// </summary>
    public ICollection<FuelTankPermittedExtrinsic>? PermittedExtrinsics { get; set; }
}

