// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A code to be used by an Enjin Wallet user to link their wallet with the Platform.
/// </summary>
public partial class LinkingCode
{
    /// <summary>
    /// An idempotency key of the linking code, either defined by the user or automatically generated.
    /// </summary>
    public string? IdempotencyKey { get; set; }
    /// <summary>
    /// The temporary linking code to be inputted by the user in Enjin Wallet.
    /// </summary>
    public string? Code { get; set; }
    /// <summary>
    /// The link to a renderable image that can be scanned by the user to begin the linking process within the Enjin Wallet.
    /// </summary>
    public string? Qr { get; set; }
    /// <summary>
    /// The link to be used by the user to begin the linking process within the Enjin Wallet.
    /// </summary>
    public string? Url { get; set; }
    /// <summary>
    /// The date and time for when the linking code expires.
    /// </summary>
    public string? Expires { get; set; }
}

