// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A marketplace listing.
/// </summary>
public partial class Listing
{
    /// <summary>
    /// The listing ID.
    /// </summary>
    public string? Id { get; set; }
    /// <summary>
    /// The account that created the listing.
    /// </summary>
    public Account? Seller { get; set; }
    /// <summary>
    /// The token being offered.
    /// </summary>
    public Token? MakeAsset { get; set; }
    /// <summary>
    /// The token requested in exchange.
    /// </summary>
    public Token? TakeAsset { get; set; }
    /// <summary>
    /// The amount of the make asset being offered.
    /// </summary>
    public global::System.Numerics.BigInteger Amount { get; set; }
    /// <summary>
    /// The price of the take asset requested, expressed as ENJ.
    /// </summary>
    public string Price { get; set; }
    /// <summary>
    /// The minimum take value, expressed as ENJ.
    /// </summary>
    public string MinTakeValue { get; set; }
    /// <summary>
    /// The listing type.
    /// </summary>
    public ListingTypeEnum? Type { get; set; }
    /// <summary>
    /// Whether the listing is active.
    /// </summary>
    public bool? IsActive { get; set; }
    /// <summary>
    /// The highest price bid so far, expressed as ENJ (if applicable).
    /// </summary>
    public string? HighestPrice { get; set; }
}

