// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A managed account.
/// </summary>
public partial class ManagedWallet
{
    /// <summary>
    /// The public key of the wallet. Null if the wallet is pending creation.
    /// </summary>
    public string? PublicKey { get; set; }
    /// <summary>
    /// The user-defined external identifier that is used for deriving the address from the managed wallet daemon. Null if unassociated with the wallet daemon.
    /// </summary>
    public string? ExternalId { get; set; }
}

