// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The sweep status of a managed wallet, derived from its transferable token balance.
/// </summary>
public partial class ManagedWalletSweepStatus
{
    /// <summary>
    /// SWEPT when the wallet holds no transferable tokens, PENDING otherwise.
    /// </summary>
    public ManagedWalletSweepStatusEnum? Status { get; set; }
    /// <summary>
    /// The number of transferable token accounts with a positive balance held by the wallet (excludes frozen tokens and tokens in frozen collections).
    /// </summary>
    public int? TransferableTokenCount { get; set; }
}

