// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The minting policy for a collection.
/// </summary>
public partial class MintPolicy
{
    /// <summary>
    /// Whether tokens are forced to collapsing supply (each token must be an NFT with supply of 1).
    /// </summary>
    public bool? ForceCollapsingSupply { get; set; }
    /// <summary>
    /// The maximum number of tokens.
    /// </summary>
    public int? MaxTokenCount { get; set; }
    /// <summary>
    /// The maximum supply per token.
    /// </summary>
    public global::System.Numerics.BigInteger? MaxTokenSupply { get; set; }
}

