// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class Mutation
{
    /// <summary>
    /// Create and encode a transaction on the Enjin blockchain.
    /// </summary>
    public Transaction? CreateTransaction { get; set; }
    /// <summary>
    /// Create and encode a batched transaction on the Enjin blockchain.
    /// </summary>
    public Transaction? CreateBatchTransaction { get; set; }
    /// <summary>
    /// Creates a new, short-lived, linking code. The user must either enter the code or scan the QR to authorize you to submit signing requests.
    /// </summary>
    public LinkingCode? CreateLinkingCode { get; set; }
    /// <summary>
    /// Prepares the creation of a new managed wallet.
    /// </summary>
    public bool? CreateManagedWallet { get; set; }
    /// <summary>
    /// Refreshes the metadata of a token by its identifier or uri.
    /// </summary>
    public bool? RefreshMetadata { get; set; }
    /// <summary>
    /// Signs a pending transaction.
    /// </summary>
    public Transaction? SignTransaction { get; set; }
    /// <summary>
    /// Sweep all transferable tokens and ENJ from a managed wallet to a recipient. The work is performed asynchronously and rate-limited to once per hour per wallet.
    /// </summary>
    public SweepManagedWalletResult? SweepManagedWallet { get; set; }
}

