// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class Mutation
{
    /// <summary>
    /// Create and encode a transaction on the Enjin blockchain.
    /// </summary>
    public Transaction? CreateTransaction { get; set; }
    /// <summary>
    /// Create and encode a batched transaction on the Enjin blockchain.
    /// </summary>
    public Transaction? CreateBatchTransaction { get; set; }
    /// <summary>
    /// Prepares the creation of a new managed wallet.
    /// </summary>
    public bool? CreateManagedWallet { get; set; }
    /// <summary>
    /// Refreshes the metadata of a token by its identifier or uri.
    /// </summary>
    public bool? RefreshMetadata { get; set; }
    /// <summary>
    /// Signs a pending transaction.
    /// </summary>
    public Transaction? SignTransaction { get; set; }
}

