// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A nomination pool.
/// </summary>
public partial class NominationPool
{
    /// <summary>
    /// The pool identifier.
    /// </summary>
    public int? Id { get; set; }
    /// <summary>
    /// The pool name.
    /// </summary>
    public string? Name { get; set; }
    /// <summary>
    /// The current state of the pool.
    /// </summary>
    public PoolStateEnum? State { get; set; }
    /// <summary>
    /// Maximum bonding capacity in sENJ.
    /// </summary>
    public global::System.Numerics.BigInteger Capacity { get; set; }
    /// <summary>
    /// Stash, reward and active balances.
    /// </summary>
    public PoolBalance? Balance { get; set; }
    /// <summary>
    /// Current commission percentage (0–100).
    /// </summary>
    public decimal? Commission { get; set; }
    /// <summary>
    /// Annual percentage yield.
    /// </summary>
    public decimal? Apy { get; set; }
    /// <summary>
    /// Total number of pool members.
    /// </summary>
    public int? TotalMembers { get; set; }
    /// <summary>
    /// Paginated list of pool members.
    /// </summary>
    public ICollection<PoolMember>? Members { get; set; }
}

