// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A token collection with a pending ownership transfer.
/// </summary>
public partial class PendingCollection
{
    /// <summary>
    /// The collection ID.
    /// </summary>
    public global::System.Numerics.BigInteger Id { get; set; }
    /// <summary>
    /// The collection owner.
    /// </summary>
    public Account? Owner { get; set; }
    /// <summary>
    /// The collection attributes.
    /// </summary>
    public ICollection<Attribute?>? Attributes { get; set; }
    /// <summary>
    /// The collection metadata.
    /// </summary>
    public Metadata? Metadata { get; set; }
    /// <summary>
    /// The minting policy.
    /// </summary>
    public MintPolicy? MintPolicy { get; set; }
    /// <summary>
    /// The marketplace policy.
    /// </summary>
    public MarketPolicy? MarketPolicy { get; set; }
    /// <summary>
    /// The transfer policy.
    /// </summary>
    public TransferPolicy? TransferPolicy { get; set; }
    /// <summary>
    /// The account the collection ownership is pending transfer to.
    /// </summary>
    public Account? PendingTransfer { get; set; }
}

