// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The balance breakdown of a nomination pool.
/// </summary>
public partial class PoolBalance
{
    /// <summary>
    /// Total stash balance, expressed as ENJ.
    /// </summary>
    public string Stash { get; set; }
    /// <summary>
    /// Reward account balance, expressed as ENJ.
    /// </summary>
    public string Reward { get; set; }
    /// <summary>
    /// Active bonded amount, expressed as ENJ.
    /// </summary>
    public string Active { get; set; }
}

