// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A member of a nomination pool.
/// </summary>
public partial class PoolMember
{
    /// <summary>
    /// The public key of the pool member.
    /// </summary>
    public string? PublicKey { get; set; }
    /// <summary>
    /// Amount of sENJ bonded.
    /// </summary>
    public global::System.Numerics.BigInteger Bonded { get; set; }
    /// <summary>
    /// Accumulated unrealised ENJ rewards.
    /// </summary>
    public global::System.Numerics.BigInteger UnrealisedEnj { get; set; }
}

