// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The balance breakdown of a nomination pool.
/// </summary>
public partial class PoolBalance
{
    /// <summary>
    /// Total stash balance.
    /// </summary>
    public global::System.Numerics.BigInteger Stash { get; set; }
    /// <summary>
    /// Reward account balance.
    /// </summary>
    public global::System.Numerics.BigInteger Reward { get; set; }
    /// <summary>
    /// Active bonded amount.
    /// </summary>
    public global::System.Numerics.BigInteger Active { get; set; }
}

