// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The authorization details required to subscribe to a private Pusher channel.
/// </summary>
public partial class PusherSocketAuth
{
    /// <summary>
    /// The signed Pusher channel authorization token.
    /// </summary>
    public string? Auth { get; set; }
    /// <summary>
    /// The private Pusher channel authorized for the current user.
    /// </summary>
    public string? Channel { get; set; }
}

