// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class Query
{
    /// <summary>
    /// Get a single account by public key.
    /// </summary>
    public Account? GetAccount { get; set; }
    /// <summary>
    /// Get multiple accounts by addresses.
    /// </summary>
    public ICollection<Account?>? GetAccounts { get; set; }
    /// <summary>
    /// Get a single block by ID (hash) or number.
    /// </summary>
    public Block? GetBlock { get; set; }
    /// <summary>
    /// Get multiple blocks, ordered by newest first.
    /// </summary>
    public ICollection<Block?>? GetBlocks { get; set; }
    /// <summary>
    /// Get a single marketplace listing by ID.
    /// </summary>
    public Listing? GetListing { get; set; }
    /// <summary>
    /// Get multiple marketplace listings for a collection, ordered by newest first.
    /// </summary>
    public ICollection<Listing?>? GetListings { get; set; }
    /// <summary>
    /// Returns a managed wallet. Requires at least publicKey or externalId to be provided.
    /// </summary>
    public ManagedWallet? GetManagedWallet { get; set; }
    /// <summary>
    /// Return a list of managed wallets.
    /// </summary>
    public ManagedWalletCursorPagination? GetManagedWallets { get; set; }
    /// <summary>
    /// Reports whether a managed wallet has been swept, based on its transferable token balance from the indexer.
    /// </summary>
    public ManagedWalletSweepStatus? ManagedWalletSweepStatus { get; set; }
    /// <summary>
    /// Get a single token by ID, or by collectionId + tokenId.
    /// </summary>
    public Token? GetToken { get; set; }
    /// <summary>
    /// Get multiple tokens by collection ID, optionally filtered by token IDs or paginated.
    /// </summary>
    public ICollection<Token?>? GetTokens { get; set; }
    /// <summary>
    /// Get a transaction. Requires at least one of the following: uuid, idempotencyKey, extrinsicHash
    /// </summary>
    public Transaction? GetTransaction { get; set; }
    /// <summary>
    /// Gets multiple transactions.
    /// </summary>
    public TransactionCursorPagination? GetTransactions { get; set; }
    /// <summary>
    /// Get a single collection by ID.
    /// </summary>
    public Collection? GetCollection { get; set; }
    /// <summary>
    /// Get multiple collections by IDs and/or owner address.
    /// </summary>
    public ICollection<Collection?>? GetCollections { get; set; }
    /// <summary>
    /// Get collections with a pending ownership transfer, optionally filtered by collection IDs or the target transfer address.
    /// </summary>
    public ICollection<PendingCollection?>? GetPendingCollectionTransfers { get; set; }
    /// <summary>
    /// Get a single extrinsic by hash.
    /// </summary>
    public Extrinsic? GetExtrinsic { get; set; }
    /// <summary>
    /// Get multiple extrinsics by hashes.
    /// </summary>
    public ICollection<Extrinsic?>? GetExtrinsics { get; set; }
    /// <summary>
    /// Returns a linked wallet. Requires at least address or idempotencyKey to be provided.
    /// </summary>
    public LinkedWallet? GetLinkedWallet { get; set; }
    /// <summary>
    /// Verify a signed message against a public key.
    /// </summary>
    public bool? VerifyMessage { get; set; }
    /// <summary>
    /// Get all nomination pools an account is bonded into, with bonded sENJ, unrealised ENJ, total unbonding, and APY.
    /// </summary>
    public ICollection<AccountPool>? GetAccountPools { get; set; }
    /// <summary>
    /// Get a single nomination pool by ID.
    /// </summary>
    public NominationPool? GetNominationPool { get; set; }
    /// <summary>
    /// Get a paginated list of nomination pools.
    /// </summary>
    public ICollection<NominationPool>? GetNominationPools { get; set; }
    /// <summary>
    /// Get a single fuel tank by its address.
    /// </summary>
    public FuelTank? GetFuelTank { get; set; }
    /// <summary>
    /// Get a paginated list of fuel tanks, optionally filtered by tank address and/or name.
    /// </summary>
    public ICollection<FuelTank>? GetFuelTanks { get; set; }
    /// <summary>
    /// Get a paginated list of accounts registered on a fuel tank, optionally filtered by address.
    /// </summary>
    public ICollection<FuelTankAccount>? GetFuelTankAccounts { get; set; }
    /// <summary>
    /// Get fuel tanks that are compatible with a transaction call.
    /// </summary>
    public ICollection<CompatibleFuelTank>? GetCompatibleFuelTanks { get; set; }
}

