// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Reference to a single multi-token (collectionId + tokenId) required to use a rule set or account rule.
/// </summary>
public partial class RequireToken
{
    /// <summary>
    /// The collection id of the required token.
    /// </summary>
    public global::System.Numerics.BigInteger CollectionId { get; set; }
    /// <summary>
    /// The token id within the collection.
    /// </summary>
    public global::System.Numerics.BigInteger? TokenId { get; set; }
}

