// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A royalty or market policy beneficiary.
/// </summary>
public partial class RoyaltyBeneficiary
{
    /// <summary>
    /// The beneficiary account ID.
    /// </summary>
    public string? AccountId { get; set; }
    /// <summary>
    /// The beneficiary percentage.
    /// </summary>
    public decimal? Percentage { get; set; }
}

