// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// An explicit royalty currency for a collection.
/// </summary>
public partial class RoyaltyCurrency
{
    /// <summary>
    /// The collection ID of the royalty currency token.
    /// </summary>
    public global::System.Numerics.BigInteger CollectionId { get; set; }
    /// <summary>
    /// The token ID of the royalty currency token.
    /// </summary>
    public global::System.Numerics.BigInteger TokenId { get; set; }
}

