// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The result of enqueueing a managed wallet sweep, including the idempotency prefix used to key the resulting batch transactions.
/// </summary>
public partial class SweepManagedWalletResult
{
    /// <summary>
    /// True when the sweep was accepted and the job dispatched.
    /// </summary>
    public bool? Accepted { get; set; }
    /// <summary>
    /// The prefix used to build per-batch idempotency keys (sprintf("%s-%d", prefix, batchNumber)) for the transactions this sweep creates, where batchNumber starts at 1. Use it to correlate the resulting transactions.
    /// </summary>
    public string? IdempotencyPrefix { get; set; }
}

