// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A token on the blockchain.
/// </summary>
public partial class Token
{
    /// <summary>
    /// The full token ID.
    /// </summary>
    public string? Id { get; set; }
    /// <summary>
    /// The numeric token ID.
    /// </summary>
    public string? TokenId { get; set; }
    /// <summary>
    /// The total supply.
    /// </summary>
    public global::System.Numerics.BigInteger Supply { get; set; }
    /// <summary>
    /// Whether the token is frozen.
    /// </summary>
    public bool? IsFrozen { get; set; }
    /// <summary>
    /// Whether the token is non-fungible.
    /// </summary>
    public bool? IsNonFungible { get; set; }
    /// <summary>
    /// Whether listing is forbidden.
    /// </summary>
    public bool? IsListingForbidden { get; set; }
    /// <summary>
    /// The infusion amount.
    /// </summary>
    public global::System.Numerics.BigInteger? Infusion { get; set; }
    /// <summary>
    /// Whether anyone can infuse this token.
    /// </summary>
    public bool? AnyoneCanInfuse { get; set; }
    /// <summary>
    /// The token attributes.
    /// </summary>
    public ICollection<Attribute>? Attributes { get; set; }
    /// <summary>
    /// The token metadata.
    /// </summary>
    public Metadata? Metadata { get; set; }
    /// <summary>
    /// The token behavior (currency or royalty).
    /// </summary>
    public TokenBehavior? Behavior { get; set; }
    /// <summary>
    /// The token cap (supply limit).
    /// </summary>
    public TokenCap? Cap { get; set; }
    /// <summary>
    /// The token group memberships for this token.
    /// </summary>
    public ICollection<TokenGroupToken>? TokenGroupTokens { get; set; }
    /// <summary>
    /// The collection this token belongs to.
    /// </summary>
    public Collection? Collection { get; set; }
    /// <summary>
    /// The holders of this token with their balances. Only populated when querying via GetToken directly.
    /// </summary>
    public ICollection<TokenHolder>? Holders { get; set; }
}

