// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A membership record linking a token to a token group.
/// </summary>
public partial class TokenGroupToken
{
    /// <summary>
    /// The token group ID.
    /// </summary>
    public global::System.Numerics.BigInteger TokenGroupId { get; set; }
    /// <summary>
    /// The token ID.
    /// </summary>
    public string? TokenId { get; set; }
    /// <summary>
    /// The position of the token within the group.
    /// </summary>
    public int? Position { get; set; }
    /// <summary>
    /// The token details.
    /// </summary>
    public Token? Token { get; set; }
    /// <summary>
    /// The token group details.
    /// </summary>
    public TokenGroup? TokenGroup { get; set; }
}

