// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The cap (supply limit) for a token.
/// </summary>
public partial class TokenCap
{
    /// <summary>
    /// The GraphQL type name (TokenCapSingleMint or TokenCapSupply). Note: CollapsingSupply tokens are returned as TokenCapSingleMint.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonProperty("__typename")]
    #endif
    public string? TypeName { get; set; }
    /// <summary>
    /// The cap type.
    /// </summary>
    public string? Type { get; set; }
    /// <summary>
    /// The cap supply limit.
    /// </summary>
    public global::System.Numerics.BigInteger? Supply { get; set; }
}

