// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A token group within a collection.
/// </summary>
public partial class TokenGroup
{
    /// <summary>
    /// The token group ID.
    /// </summary>
    public global::System.Numerics.BigInteger Id { get; set; }
    /// <summary>
    /// The collection this group belongs to.
    /// </summary>
    public global::System.Numerics.BigInteger CollectionId { get; set; }
    /// <summary>
    /// The token group attributes.
    /// </summary>
    public ICollection<Attribute>? Attributes { get; set; }
    /// <summary>
    /// The token group metadata.
    /// </summary>
    public Metadata? Metadata { get; set; }
    /// <summary>
    /// The token memberships in this group.
    /// </summary>
    public ICollection<TokenGroupToken>? TokenGroupTokens { get; set; }
}

