// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class TransactionCursorPagination
{
    /// <summary>
    /// List of items on the current page
    /// </summary>
    public ICollection<Transaction>? Data { get; set; }
    /// <summary>
    /// Number of items returned per page
    /// </summary>
    public int? PerPage { get; set; }
    /// <summary>
    /// Previous page cursor
    /// </summary>
    public string? PreviousCursor { get; set; }
    /// <summary>
    /// Next page cursor
    /// </summary>
    public string? NextCursor { get; set; }
}

