// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The transfer policy for a collection.
/// </summary>
public partial class TransferPolicy
{
    /// <summary>
    /// Whether transfers are frozen.
    /// </summary>
    public bool? IsFrozen { get; set; }
}

