// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The encoded transaction payload result.
/// </summary>
public partial class Transaction
{
    /// <summary>
    /// The UUID of the transaction.
    /// </summary>
    public string? Uuid { get; set; }
    /// <summary>
    /// The user-defined idempotency key of the transaction.
    /// </summary>
    public string? IdempotencyKey { get; set; }
    /// <summary>
    /// The action (pallet.method) of the transaction.
    /// </summary>
    public string? Action { get; set; }
    /// <summary>
    /// The encoded data of the pending transaction that requires signing.
    /// </summary>
    public string? EncodedData { get; set; }
    /// <summary>
    /// The on-chain extrinsic, resolved from the indexer.
    /// </summary>
    public Extrinsic? Extrinsic { get; set; }
    /// <summary>
    /// The state of the transaction.
    /// </summary>
    public TransactionStateEnum? State { get; set; }
    /// <summary>
    /// The on-chain failure reason when the transaction failed, including partial batch failures where the extrinsic finalized but one or more wrapped items did not dispatch.
    /// </summary>
    public string? Error { get; set; }
    /// <summary>
    /// When the transaction was created.
    /// </summary>
    public DateTimeOffset? CreatedAt { get; set; }
    /// <summary>
    /// When the transaction was last updated.
    /// </summary>
    public DateTimeOffset? UpdatedAt { get; set; }
}

