// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class AccountQueryBuilder : GraphQlQueryBuilder<AccountQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "address" },
        new() { Name = "nonce" },
        new() { Name = "balance" },
        new() { Name = "tokens", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(TokenQueryBuilder) }
    };

    protected override string TypeName => "Account";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public AccountQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public AccountQueryBuilder ExceptId() => ExceptField("id");

    public AccountQueryBuilder WithAddress(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("address", alias, [include, skip]);

    public AccountQueryBuilder ExceptAddress() => ExceptField("address");

    public AccountQueryBuilder WithNonce(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("nonce", alias, [include, skip]);

    public AccountQueryBuilder ExceptNonce() => ExceptField("nonce");

    public AccountQueryBuilder WithBalance(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("balance", alias, [include, skip]);

    public AccountQueryBuilder ExceptBalance() => ExceptField("balance");

    /// <param name="limit">The number of tokens to return.</param>
    /// <param name="after">The offset for pagination.</param>
    /// <param name="collectionId">Filter tokens by collection ID.</param>
    /// <param name="tokenIds">Filter by token IDs within the collection (requires collectionId).</param>
    public AccountQueryBuilder WithTokens(TokenQueryBuilder tokenQueryBuilder, QueryBuilderParameter<int> limit, QueryBuilderParameter<int?>? after = null, QueryBuilderParameter<global::System.Numerics.BigInteger?>? collectionId = null, QueryBuilderParameter<IEnumerable<global::System.Numerics.BigInteger>>? tokenIds = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        if (after != null)
            args.Add(new() { ArgumentName = "after", ArgumentValue = after} );

        if (collectionId != null)
            args.Add(new() { ArgumentName = "collectionId", ArgumentValue = collectionId} );

        if (tokenIds != null)
            args.Add(new() { ArgumentName = "tokenIds", ArgumentValue = tokenIds} );

        return WithObjectField("tokens", alias, tokenQueryBuilder, [include, skip], args);
    }

    public AccountQueryBuilder ExceptTokens() => ExceptField("tokens");
}

