// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class AccountTokenQueryBuilder : GraphQlQueryBuilder<AccountTokenQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "balance" },
        new() { Name = "token", IsComplex = true, QueryBuilderType = typeof(TokenQueryBuilder) }
    };

    protected override string TypeName => "AccountToken";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public AccountTokenQueryBuilder WithBalance(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("balance", alias, [include, skip]);

    public AccountTokenQueryBuilder ExceptBalance() => ExceptField("balance");

    public AccountTokenQueryBuilder WithToken(TokenQueryBuilder tokenQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("token", alias, tokenQueryBuilder, [include, skip]);

    public AccountTokenQueryBuilder ExceptToken() => ExceptField("token");
}

