// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class AccountPoolQueryBuilder : GraphQlQueryBuilder<AccountPoolQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "name" },
        new() { Name = "state" },
        new() { Name = "bonded" },
        new() { Name = "unrealisedEnj" },
        new() { Name = "totalUnbonding" },
        new() { Name = "apy" }
    };

    protected override string TypeName => "AccountPool";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public AccountPoolQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public AccountPoolQueryBuilder ExceptId() => ExceptField("id");

    public AccountPoolQueryBuilder WithName(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("name", alias, [include, skip]);

    public AccountPoolQueryBuilder ExceptName() => ExceptField("name");

    public AccountPoolQueryBuilder WithState(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("state", alias, [include, skip]);

    public AccountPoolQueryBuilder ExceptState() => ExceptField("state");

    public AccountPoolQueryBuilder WithBonded(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("bonded", alias, [include, skip]);

    public AccountPoolQueryBuilder ExceptBonded() => ExceptField("bonded");

    public AccountPoolQueryBuilder WithUnrealisedEnj(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("unrealisedEnj", alias, [include, skip]);

    public AccountPoolQueryBuilder ExceptUnrealisedEnj() => ExceptField("unrealisedEnj");

    public AccountPoolQueryBuilder WithTotalUnbonding(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("totalUnbonding", alias, [include, skip]);

    public AccountPoolQueryBuilder ExceptTotalUnbonding() => ExceptField("totalUnbonding");

    public AccountPoolQueryBuilder WithApy(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("apy", alias, [include, skip]);

    public AccountPoolQueryBuilder ExceptApy() => ExceptField("apy");
}

