// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class AttributeQueryBuilder : GraphQlQueryBuilder<AttributeQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "key" },
        new() { Name = "value" }
    };

    protected override string TypeName => "Attribute";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public AttributeQueryBuilder WithKey(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("key", alias, [include, skip]);

    public AttributeQueryBuilder ExceptKey() => ExceptField("key");

    public AttributeQueryBuilder WithValue(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("value", alias, [include, skip]);

    public AttributeQueryBuilder ExceptValue() => ExceptField("value");
}

