// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class BlockQueryBuilder : GraphQlQueryBuilder<BlockQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "number" },
        new() { Name = "hash" },
        new() { Name = "validator", IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) },
        new() { Name = "extrinsics", IsComplex = true, QueryBuilderType = typeof(ExtrinsicQueryBuilder) },
        new() { Name = "events", IsComplex = true, QueryBuilderType = typeof(EventQueryBuilder) },
        new() { Name = "createdAt" }
    };

    protected override string TypeName => "Block";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public BlockQueryBuilder WithNumber(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("number", alias, [include, skip]);

    public BlockQueryBuilder ExceptNumber() => ExceptField("number");

    public BlockQueryBuilder WithHash(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("hash", alias, [include, skip]);

    public BlockQueryBuilder ExceptHash() => ExceptField("hash");

    public BlockQueryBuilder WithValidator(AccountQueryBuilder accountQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("validator", alias, accountQueryBuilder, [include, skip]);

    public BlockQueryBuilder ExceptValidator() => ExceptField("validator");

    public BlockQueryBuilder WithExtrinsics(ExtrinsicQueryBuilder extrinsicQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("extrinsics", alias, extrinsicQueryBuilder, [include, skip]);

    public BlockQueryBuilder ExceptExtrinsics() => ExceptField("extrinsics");

    public BlockQueryBuilder WithEvents(EventQueryBuilder eventQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("events", alias, eventQueryBuilder, [include, skip]);

    public BlockQueryBuilder ExceptEvents() => ExceptField("events");

    public BlockQueryBuilder WithCreatedAt(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("createdAt", alias, [include, skip]);

    public BlockQueryBuilder ExceptCreatedAt() => ExceptField("createdAt");
}

