// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class CollectionQueryBuilder : GraphQlQueryBuilder<CollectionQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "owner", IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) },
        new() { Name = "attributes", IsComplex = true, QueryBuilderType = typeof(AttributeQueryBuilder) },
        new() { Name = "metadata", IsComplex = true, QueryBuilderType = typeof(MetadataQueryBuilder) },
        new() { Name = "mintPolicy", IsComplex = true, QueryBuilderType = typeof(MintPolicyQueryBuilder) },
        new() { Name = "marketPolicy", IsComplex = true, QueryBuilderType = typeof(MarketPolicyQueryBuilder) },
        new() { Name = "transferPolicy", IsComplex = true, QueryBuilderType = typeof(TransferPolicyQueryBuilder) },
        new() { Name = "pendingTransfer", IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) },
        new() { Name = "tokenGroups", IsComplex = true, QueryBuilderType = typeof(TokenGroupQueryBuilder) },
        new() { Name = "holders", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(CollectionHolderQueryBuilder) }
    };

    protected override string TypeName => "Collection";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public CollectionQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public CollectionQueryBuilder ExceptId() => ExceptField("id");

    public CollectionQueryBuilder WithOwner(AccountQueryBuilder accountQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("owner", alias, accountQueryBuilder, [include, skip]);

    public CollectionQueryBuilder ExceptOwner() => ExceptField("owner");

    public CollectionQueryBuilder WithAttributes(AttributeQueryBuilder attributeQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("attributes", alias, attributeQueryBuilder, [include, skip]);

    public CollectionQueryBuilder ExceptAttributes() => ExceptField("attributes");

    public CollectionQueryBuilder WithMetadata(MetadataQueryBuilder metadataQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("metadata", alias, metadataQueryBuilder, [include, skip]);

    public CollectionQueryBuilder ExceptMetadata() => ExceptField("metadata");

    public CollectionQueryBuilder WithMintPolicy(MintPolicyQueryBuilder mintPolicyQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("mintPolicy", alias, mintPolicyQueryBuilder, [include, skip]);

    public CollectionQueryBuilder ExceptMintPolicy() => ExceptField("mintPolicy");

    public CollectionQueryBuilder WithMarketPolicy(MarketPolicyQueryBuilder marketPolicyQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("marketPolicy", alias, marketPolicyQueryBuilder, [include, skip]);

    public CollectionQueryBuilder ExceptMarketPolicy() => ExceptField("marketPolicy");

    public CollectionQueryBuilder WithTransferPolicy(TransferPolicyQueryBuilder transferPolicyQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("transferPolicy", alias, transferPolicyQueryBuilder, [include, skip]);

    public CollectionQueryBuilder ExceptTransferPolicy() => ExceptField("transferPolicy");

    public CollectionQueryBuilder WithPendingTransfer(AccountQueryBuilder accountQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("pendingTransfer", alias, accountQueryBuilder, [include, skip]);

    public CollectionQueryBuilder ExceptPendingTransfer() => ExceptField("pendingTransfer");

    public CollectionQueryBuilder WithTokenGroups(TokenGroupQueryBuilder tokenGroupQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("tokenGroups", alias, tokenGroupQueryBuilder, [include, skip]);

    public CollectionQueryBuilder ExceptTokenGroups() => ExceptField("tokenGroups");

    /// <param name="limit">Number of holders to return per page. Defaults to the context cap (100 in GetCollection, 10 in bulk queries). Requesting a limit above the context cap raises a validation error.</param>
    /// <param name="page">Page number (max 500, default 1).</param>
    public CollectionQueryBuilder WithHolders(CollectionHolderQueryBuilder collectionHolderQueryBuilder, QueryBuilderParameter<int> page, QueryBuilderParameter<int?>? limit = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        if (limit != null)
            args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );

        args.Add(new() { ArgumentName = "page", ArgumentValue = page} );
        return WithObjectField("holders", alias, collectionHolderQueryBuilder, [include, skip], args);
    }

    public CollectionQueryBuilder ExceptHolders() => ExceptField("holders");
}

