// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class CollectionHolderQueryBuilder : GraphQlQueryBuilder<CollectionHolderQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "address" }
    };

    protected override string TypeName => "CollectionHolder";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public CollectionHolderQueryBuilder WithAddress(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("address", alias, [include, skip]);

    public CollectionHolderQueryBuilder ExceptAddress() => ExceptField("address");
}

