// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class CompatibleFuelTankQueryBuilder : GraphQlQueryBuilder<CompatibleFuelTankQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "name" },
        new() { Name = "providesDeposit" },
        new() { Name = "coveragePolicy" },
        new() { Name = "ruleSet", IsComplex = true, QueryBuilderType = typeof(CompatibleFuelTankRuleSetQueryBuilder) },
        new() { Name = "remainingBudget" },
        new() { Name = "maxBudget" },
        new() { Name = "consumedBudget" },
        new() { Name = "tankBalance" }
    };

    protected override string TypeName => "CompatibleFuelTank";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public CompatibleFuelTankQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public CompatibleFuelTankQueryBuilder ExceptId() => ExceptField("id");

    public CompatibleFuelTankQueryBuilder WithName(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("name", alias, [include, skip]);

    public CompatibleFuelTankQueryBuilder ExceptName() => ExceptField("name");

    public CompatibleFuelTankQueryBuilder WithProvidesDeposit(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("providesDeposit", alias, [include, skip]);

    public CompatibleFuelTankQueryBuilder ExceptProvidesDeposit() => ExceptField("providesDeposit");

    public CompatibleFuelTankQueryBuilder WithCoveragePolicy(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("coveragePolicy", alias, [include, skip]);

    public CompatibleFuelTankQueryBuilder ExceptCoveragePolicy() => ExceptField("coveragePolicy");

    public CompatibleFuelTankQueryBuilder WithRuleSet(CompatibleFuelTankRuleSetQueryBuilder compatibleFuelTankRuleSetQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("ruleSet", alias, compatibleFuelTankRuleSetQueryBuilder, [include, skip]);

    public CompatibleFuelTankQueryBuilder ExceptRuleSet() => ExceptField("ruleSet");

    public CompatibleFuelTankQueryBuilder WithRemainingBudget(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("remainingBudget", alias, [include, skip]);

    public CompatibleFuelTankQueryBuilder ExceptRemainingBudget() => ExceptField("remainingBudget");

    public CompatibleFuelTankQueryBuilder WithMaxBudget(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("maxBudget", alias, [include, skip]);

    public CompatibleFuelTankQueryBuilder ExceptMaxBudget() => ExceptField("maxBudget");

    public CompatibleFuelTankQueryBuilder WithConsumedBudget(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("consumedBudget", alias, [include, skip]);

    public CompatibleFuelTankQueryBuilder ExceptConsumedBudget() => ExceptField("consumedBudget");

    public CompatibleFuelTankQueryBuilder WithTankBalance(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("tankBalance", alias, [include, skip]);

    public CompatibleFuelTankQueryBuilder ExceptTankBalance() => ExceptField("tankBalance");
}

