// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class ExtrinsicQueryBuilder : GraphQlQueryBuilder<ExtrinsicQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "hash" },
        new() { Name = "block", IsComplex = true, QueryBuilderType = typeof(BlockQueryBuilder) },
        new() { Name = "success" },
        new() { Name = "pallet" },
        new() { Name = "method" },
        new() { Name = "signer", IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) },
        new() { Name = "nonce" },
        new() { Name = "error" },
        new() { Name = "events", IsComplex = true, QueryBuilderType = typeof(EventQueryBuilder) }
    };

    protected override string TypeName => "Extrinsic";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public ExtrinsicQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public ExtrinsicQueryBuilder ExceptId() => ExceptField("id");

    public ExtrinsicQueryBuilder WithHash(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("hash", alias, [include, skip]);

    public ExtrinsicQueryBuilder ExceptHash() => ExceptField("hash");

    public ExtrinsicQueryBuilder WithBlock(BlockQueryBuilder blockQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("block", alias, blockQueryBuilder, [include, skip]);

    public ExtrinsicQueryBuilder ExceptBlock() => ExceptField("block");

    public ExtrinsicQueryBuilder WithSuccess(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("success", alias, [include, skip]);

    public ExtrinsicQueryBuilder ExceptSuccess() => ExceptField("success");

    public ExtrinsicQueryBuilder WithPallet(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("pallet", alias, [include, skip]);

    public ExtrinsicQueryBuilder ExceptPallet() => ExceptField("pallet");

    public ExtrinsicQueryBuilder WithMethod(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("method", alias, [include, skip]);

    public ExtrinsicQueryBuilder ExceptMethod() => ExceptField("method");

    public ExtrinsicQueryBuilder WithSigner(AccountQueryBuilder accountQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("signer", alias, accountQueryBuilder, [include, skip]);

    public ExtrinsicQueryBuilder ExceptSigner() => ExceptField("signer");

    public ExtrinsicQueryBuilder WithNonce(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("nonce", alias, [include, skip]);

    public ExtrinsicQueryBuilder ExceptNonce() => ExceptField("nonce");

    public ExtrinsicQueryBuilder WithError(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("error", alias, [include, skip]);

    public ExtrinsicQueryBuilder ExceptError() => ExceptField("error");

    public ExtrinsicQueryBuilder WithEvents(EventQueryBuilder eventQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("events", alias, eventQueryBuilder, [include, skip]);

    public ExtrinsicQueryBuilder ExceptEvents() => ExceptField("events");
}

