// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class FuelTankQueryBuilder : GraphQlQueryBuilder<FuelTankQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "name" },
        new() { Name = "owner" },
        new() { Name = "coveragePolicy" },
        new() { Name = "isFrozen" },
        new() { Name = "accountCount" },
        new() { Name = "tankAccount", IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) },
        new() { Name = "userAccountManagement", IsComplex = true, QueryBuilderType = typeof(FuelTankUserAccountManagementQueryBuilder) },
        new() { Name = "accountRules", IsComplex = true, QueryBuilderType = typeof(FuelTankAccountRuleQueryBuilder) },
        new() { Name = "ruleSets", IsComplex = true, QueryBuilderType = typeof(FuelTankRuleSetQueryBuilder) }
    };

    protected override string TypeName => "FuelTank";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public FuelTankQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public FuelTankQueryBuilder ExceptId() => ExceptField("id");

    public FuelTankQueryBuilder WithName(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("name", alias, [include, skip]);

    public FuelTankQueryBuilder ExceptName() => ExceptField("name");

    public FuelTankQueryBuilder WithOwner(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("owner", alias, [include, skip]);

    public FuelTankQueryBuilder ExceptOwner() => ExceptField("owner");

    public FuelTankQueryBuilder WithCoveragePolicy(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("coveragePolicy", alias, [include, skip]);

    public FuelTankQueryBuilder ExceptCoveragePolicy() => ExceptField("coveragePolicy");

    public FuelTankQueryBuilder WithIsFrozen(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("isFrozen", alias, [include, skip]);

    public FuelTankQueryBuilder ExceptIsFrozen() => ExceptField("isFrozen");

    public FuelTankQueryBuilder WithAccountCount(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("accountCount", alias, [include, skip]);

    public FuelTankQueryBuilder ExceptAccountCount() => ExceptField("accountCount");

    public FuelTankQueryBuilder WithTankAccount(AccountQueryBuilder accountQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("tankAccount", alias, accountQueryBuilder, [include, skip]);

    public FuelTankQueryBuilder ExceptTankAccount() => ExceptField("tankAccount");

    public FuelTankQueryBuilder WithUserAccountManagement(FuelTankUserAccountManagementQueryBuilder fuelTankUserAccountManagementQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("userAccountManagement", alias, fuelTankUserAccountManagementQueryBuilder, [include, skip]);

    public FuelTankQueryBuilder ExceptUserAccountManagement() => ExceptField("userAccountManagement");

    public FuelTankQueryBuilder WithAccountRules(FuelTankAccountRuleQueryBuilder fuelTankAccountRuleQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("accountRules", alias, fuelTankAccountRuleQueryBuilder, [include, skip]);

    public FuelTankQueryBuilder ExceptAccountRules() => ExceptField("accountRules");

    public FuelTankQueryBuilder WithRuleSets(FuelTankRuleSetQueryBuilder fuelTankRuleSetQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("ruleSets", alias, fuelTankRuleSetQueryBuilder, [include, skip]);

    public FuelTankQueryBuilder ExceptRuleSets() => ExceptField("ruleSets");
}

