// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class FuelTankUserAccountManagementQueryBuilder : GraphQlQueryBuilder<FuelTankUserAccountManagementQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "tankReservesAccountCreationDeposit" },
        new() { Name = "tankReservesExistentialDeposit" }
    };

    protected override string TypeName => "FuelTankUserAccountManagement";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public FuelTankUserAccountManagementQueryBuilder WithTankReservesAccountCreationDeposit(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("tankReservesAccountCreationDeposit", alias, [include, skip]);

    public FuelTankUserAccountManagementQueryBuilder ExceptTankReservesAccountCreationDeposit() => ExceptField("tankReservesAccountCreationDeposit");

    public FuelTankUserAccountManagementQueryBuilder WithTankReservesExistentialDeposit(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("tankReservesExistentialDeposit", alias, [include, skip]);

    public FuelTankUserAccountManagementQueryBuilder ExceptTankReservesExistentialDeposit() => ExceptField("tankReservesExistentialDeposit");
}

