// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class FuelTankAccountRuleQueryBuilder : GraphQlQueryBuilder<FuelTankAccountRuleQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "whitelistedCallers", IsComplex = true },
        new() { Name = "requireToken", IsComplex = true, QueryBuilderType = typeof(RequireTokenQueryBuilder) }
    };

    protected override string TypeName => "FuelTankAccountRule";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public FuelTankAccountRuleQueryBuilder WithWhitelistedCallers(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("whitelistedCallers", alias, [include, skip]);

    public FuelTankAccountRuleQueryBuilder ExceptWhitelistedCallers() => ExceptField("whitelistedCallers");

    public FuelTankAccountRuleQueryBuilder WithRequireToken(RequireTokenQueryBuilder requireTokenQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("requireToken", alias, requireTokenQueryBuilder, [include, skip]);

    public FuelTankAccountRuleQueryBuilder ExceptRequireToken() => ExceptField("requireToken");
}

