// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class FuelTankPermittedExtrinsicQueryBuilder : GraphQlQueryBuilder<FuelTankPermittedExtrinsicQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "palletName" },
        new() { Name = "extrinsicName" }
    };

    protected override string TypeName => "FuelTankPermittedExtrinsic";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public FuelTankPermittedExtrinsicQueryBuilder WithPalletName(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("palletName", alias, [include, skip]);

    public FuelTankPermittedExtrinsicQueryBuilder ExceptPalletName() => ExceptField("palletName");

    public FuelTankPermittedExtrinsicQueryBuilder WithExtrinsicName(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("extrinsicName", alias, [include, skip]);

    public FuelTankPermittedExtrinsicQueryBuilder ExceptExtrinsicName() => ExceptField("extrinsicName");
}

