// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class FuelTankRuleSetQueryBuilder : GraphQlQueryBuilder<FuelTankRuleSetQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "isFrozen" },
        new() { Name = "requireAccount" },
        new() { Name = "requireSignature" },
        new() { Name = "whitelistedCallers", IsComplex = true },
        new() { Name = "whitelistedCollections", IsComplex = true },
        new() { Name = "whitelistedPallets", IsComplex = true },
        new() { Name = "maxFuelBurnPerTransaction" },
        new() { Name = "minimumInfusion" },
        new() { Name = "userFuelBudget", IsComplex = true, QueryBuilderType = typeof(FuelBudgetQueryBuilder) },
        new() { Name = "tankFuelBudget", IsComplex = true, QueryBuilderType = typeof(FuelBudgetQueryBuilder) },
        new() { Name = "requireToken", IsComplex = true, QueryBuilderType = typeof(RequireTokenQueryBuilder) },
        new() { Name = "permittedCalls", IsComplex = true },
        new() { Name = "permittedExtrinsics", IsComplex = true, QueryBuilderType = typeof(FuelTankPermittedExtrinsicQueryBuilder) }
    };

    protected override string TypeName => "FuelTankRuleSet";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public FuelTankRuleSetQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptId() => ExceptField("id");

    public FuelTankRuleSetQueryBuilder WithIsFrozen(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("isFrozen", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptIsFrozen() => ExceptField("isFrozen");

    public FuelTankRuleSetQueryBuilder WithRequireAccount(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("requireAccount", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptRequireAccount() => ExceptField("requireAccount");

    public FuelTankRuleSetQueryBuilder WithRequireSignature(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("requireSignature", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptRequireSignature() => ExceptField("requireSignature");

    public FuelTankRuleSetQueryBuilder WithWhitelistedCallers(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("whitelistedCallers", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptWhitelistedCallers() => ExceptField("whitelistedCallers");

    public FuelTankRuleSetQueryBuilder WithWhitelistedCollections(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("whitelistedCollections", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptWhitelistedCollections() => ExceptField("whitelistedCollections");

    public FuelTankRuleSetQueryBuilder WithWhitelistedPallets(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("whitelistedPallets", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptWhitelistedPallets() => ExceptField("whitelistedPallets");

    public FuelTankRuleSetQueryBuilder WithMaxFuelBurnPerTransaction(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("maxFuelBurnPerTransaction", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptMaxFuelBurnPerTransaction() => ExceptField("maxFuelBurnPerTransaction");

    public FuelTankRuleSetQueryBuilder WithMinimumInfusion(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("minimumInfusion", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptMinimumInfusion() => ExceptField("minimumInfusion");

    public FuelTankRuleSetQueryBuilder WithUserFuelBudget(FuelBudgetQueryBuilder fuelBudgetQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("userFuelBudget", alias, fuelBudgetQueryBuilder, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptUserFuelBudget() => ExceptField("userFuelBudget");

    public FuelTankRuleSetQueryBuilder WithTankFuelBudget(FuelBudgetQueryBuilder fuelBudgetQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("tankFuelBudget", alias, fuelBudgetQueryBuilder, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptTankFuelBudget() => ExceptField("tankFuelBudget");

    public FuelTankRuleSetQueryBuilder WithRequireToken(RequireTokenQueryBuilder requireTokenQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("requireToken", alias, requireTokenQueryBuilder, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptRequireToken() => ExceptField("requireToken");

    public FuelTankRuleSetQueryBuilder WithPermittedCalls(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("permittedCalls", alias, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptPermittedCalls() => ExceptField("permittedCalls");

    public FuelTankRuleSetQueryBuilder WithPermittedExtrinsics(FuelTankPermittedExtrinsicQueryBuilder fuelTankPermittedExtrinsicQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("permittedExtrinsics", alias, fuelTankPermittedExtrinsicQueryBuilder, [include, skip]);

    public FuelTankRuleSetQueryBuilder ExceptPermittedExtrinsics() => ExceptField("permittedExtrinsics");
}

