// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class FuelBudgetQueryBuilder : GraphQlQueryBuilder<FuelBudgetQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "amount" },
        new() { Name = "resetPeriod" }
    };

    protected override string TypeName => "FuelBudget";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public FuelBudgetQueryBuilder WithAmount(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("amount", alias, [include, skip]);

    public FuelBudgetQueryBuilder ExceptAmount() => ExceptField("amount");

    public FuelBudgetQueryBuilder WithResetPeriod(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("resetPeriod", alias, [include, skip]);

    public FuelBudgetQueryBuilder ExceptResetPeriod() => ExceptField("resetPeriod");
}

