// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class LinkedWalletQueryBuilder : GraphQlQueryBuilder<LinkedWalletQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "publicKey" },
        new() { Name = "idempotencyKey" }
    };

    protected override string TypeName => "LinkedWallet";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public LinkedWalletQueryBuilder WithPublicKey(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("publicKey", alias, [include, skip]);

    public LinkedWalletQueryBuilder ExceptPublicKey() => ExceptField("publicKey");

    public LinkedWalletQueryBuilder WithIdempotencyKey(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("idempotencyKey", alias, [include, skip]);

    public LinkedWalletQueryBuilder ExceptIdempotencyKey() => ExceptField("idempotencyKey");
}

