// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class LinkingCodeQueryBuilder : GraphQlQueryBuilder<LinkingCodeQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "idempotencyKey" },
        new() { Name = "code" },
        new() { Name = "qr" },
        new() { Name = "url" },
        new() { Name = "expires" }
    };

    protected override string TypeName => "LinkingCode";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public LinkingCodeQueryBuilder WithIdempotencyKey(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("idempotencyKey", alias, [include, skip]);

    public LinkingCodeQueryBuilder ExceptIdempotencyKey() => ExceptField("idempotencyKey");

    public LinkingCodeQueryBuilder WithCode(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("code", alias, [include, skip]);

    public LinkingCodeQueryBuilder ExceptCode() => ExceptField("code");

    public LinkingCodeQueryBuilder WithQr(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("qr", alias, [include, skip]);

    public LinkingCodeQueryBuilder ExceptQr() => ExceptField("qr");

    public LinkingCodeQueryBuilder WithUrl(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("url", alias, [include, skip]);

    public LinkingCodeQueryBuilder ExceptUrl() => ExceptField("url");

    public LinkingCodeQueryBuilder WithExpires(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("expires", alias, [include, skip]);

    public LinkingCodeQueryBuilder ExceptExpires() => ExceptField("expires");
}

