// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class ListingQueryBuilder : GraphQlQueryBuilder<ListingQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "seller", IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) },
        new() { Name = "makeAsset", IsComplex = true, QueryBuilderType = typeof(TokenQueryBuilder) },
        new() { Name = "takeAsset", IsComplex = true, QueryBuilderType = typeof(TokenQueryBuilder) },
        new() { Name = "amount" },
        new() { Name = "price" },
        new() { Name = "minTakeValue" },
        new() { Name = "type" },
        new() { Name = "isActive" },
        new() { Name = "highestPrice" }
    };

    protected override string TypeName => "Listing";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public ListingQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public ListingQueryBuilder ExceptId() => ExceptField("id");

    public ListingQueryBuilder WithSeller(AccountQueryBuilder accountQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("seller", alias, accountQueryBuilder, [include, skip]);

    public ListingQueryBuilder ExceptSeller() => ExceptField("seller");

    public ListingQueryBuilder WithMakeAsset(TokenQueryBuilder tokenQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("makeAsset", alias, tokenQueryBuilder, [include, skip]);

    public ListingQueryBuilder ExceptMakeAsset() => ExceptField("makeAsset");

    public ListingQueryBuilder WithTakeAsset(TokenQueryBuilder tokenQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("takeAsset", alias, tokenQueryBuilder, [include, skip]);

    public ListingQueryBuilder ExceptTakeAsset() => ExceptField("takeAsset");

    public ListingQueryBuilder WithAmount(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("amount", alias, [include, skip]);

    public ListingQueryBuilder ExceptAmount() => ExceptField("amount");

    public ListingQueryBuilder WithPrice(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("price", alias, [include, skip]);

    public ListingQueryBuilder ExceptPrice() => ExceptField("price");

    public ListingQueryBuilder WithMinTakeValue(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("minTakeValue", alias, [include, skip]);

    public ListingQueryBuilder ExceptMinTakeValue() => ExceptField("minTakeValue");

    public ListingQueryBuilder WithType(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("type", alias, [include, skip]);

    public ListingQueryBuilder ExceptType() => ExceptField("type");

    public ListingQueryBuilder WithIsActive(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("isActive", alias, [include, skip]);

    public ListingQueryBuilder ExceptIsActive() => ExceptField("isActive");

    public ListingQueryBuilder WithHighestPrice(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("highestPrice", alias, [include, skip]);

    public ListingQueryBuilder ExceptHighestPrice() => ExceptField("highestPrice");
}

