// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class ManagedWalletCursorPaginationQueryBuilder : GraphQlQueryBuilder<ManagedWalletCursorPaginationQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "data", IsComplex = true, QueryBuilderType = typeof(ManagedWalletQueryBuilder) },
        new() { Name = "perPage" },
        new() { Name = "previousCursor" },
        new() { Name = "nextCursor" }
    };

    protected override string TypeName => "ManagedWalletCursorPagination";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public ManagedWalletCursorPaginationQueryBuilder WithData(ManagedWalletQueryBuilder managedWalletQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("data", alias, managedWalletQueryBuilder, [include, skip]);

    public ManagedWalletCursorPaginationQueryBuilder ExceptData() => ExceptField("data");

    public ManagedWalletCursorPaginationQueryBuilder WithPerPage(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("perPage", alias, [include, skip]);

    public ManagedWalletCursorPaginationQueryBuilder ExceptPerPage() => ExceptField("perPage");

    public ManagedWalletCursorPaginationQueryBuilder WithPreviousCursor(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("previousCursor", alias, [include, skip]);

    public ManagedWalletCursorPaginationQueryBuilder ExceptPreviousCursor() => ExceptField("previousCursor");

    public ManagedWalletCursorPaginationQueryBuilder WithNextCursor(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("nextCursor", alias, [include, skip]);

    public ManagedWalletCursorPaginationQueryBuilder ExceptNextCursor() => ExceptField("nextCursor");
}

