// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class ManagedWalletSweepStatusQueryBuilder : GraphQlQueryBuilder<ManagedWalletSweepStatusQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "status" },
        new() { Name = "transferableTokenCount" }
    };

    protected override string TypeName => "ManagedWalletSweepStatus";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public ManagedWalletSweepStatusQueryBuilder WithStatus(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("status", alias, [include, skip]);

    public ManagedWalletSweepStatusQueryBuilder ExceptStatus() => ExceptField("status");

    public ManagedWalletSweepStatusQueryBuilder WithTransferableTokenCount(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("transferableTokenCount", alias, [include, skip]);

    public ManagedWalletSweepStatusQueryBuilder ExceptTransferableTokenCount() => ExceptField("transferableTokenCount");
}

