// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class MetadataQueryBuilder : GraphQlQueryBuilder<MetadataQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "attributes" },
        new() { Name = "name" },
        new() { Name = "description" },
        new() { Name = "fallbackImage" },
        new() { Name = "bannerImage" },
        new() { Name = "media", IsComplex = true, QueryBuilderType = typeof(MetadataMediaQueryBuilder) },
        new() { Name = "meta", IsComplex = true, QueryBuilderType = typeof(MetadataMetaQueryBuilder) }
    };

    protected override string TypeName => "Metadata";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public MetadataQueryBuilder WithAttributes(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("attributes", alias, [include, skip]);

    public MetadataQueryBuilder ExceptAttributes() => ExceptField("attributes");

    public MetadataQueryBuilder WithName(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("name", alias, [include, skip]);

    public MetadataQueryBuilder ExceptName() => ExceptField("name");

    public MetadataQueryBuilder WithDescription(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("description", alias, [include, skip]);

    public MetadataQueryBuilder ExceptDescription() => ExceptField("description");

    public MetadataQueryBuilder WithFallbackImage(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("fallbackImage", alias, [include, skip]);

    public MetadataQueryBuilder ExceptFallbackImage() => ExceptField("fallbackImage");

    public MetadataQueryBuilder WithBannerImage(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("bannerImage", alias, [include, skip]);

    public MetadataQueryBuilder ExceptBannerImage() => ExceptField("bannerImage");

    public MetadataQueryBuilder WithMedia(MetadataMediaQueryBuilder metadataMediaQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("media", alias, metadataMediaQueryBuilder, [include, skip]);

    public MetadataQueryBuilder ExceptMedia() => ExceptField("media");

    public MetadataQueryBuilder WithMeta(MetadataMetaQueryBuilder metadataMetaQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("meta", alias, metadataMetaQueryBuilder, [include, skip]);

    public MetadataQueryBuilder ExceptMeta() => ExceptField("meta");
}

