// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class MetadataMediaQueryBuilder : GraphQlQueryBuilder<MetadataMediaQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "url" },
        new() { Name = "type" },
        new() { Name = "alt" }
    };

    protected override string TypeName => "MetadataMedia";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public MetadataMediaQueryBuilder WithUrl(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("url", alias, [include, skip]);

    public MetadataMediaQueryBuilder ExceptUrl() => ExceptField("url");

    public MetadataMediaQueryBuilder WithType(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("type", alias, [include, skip]);

    public MetadataMediaQueryBuilder ExceptType() => ExceptField("type");

    public MetadataMediaQueryBuilder WithAlt(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("alt", alias, [include, skip]);

    public MetadataMediaQueryBuilder ExceptAlt() => ExceptField("alt");
}

