// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class MetadataMetaQueryBuilder : GraphQlQueryBuilder<MetadataMetaQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "language" }
    };

    protected override string TypeName => "MetadataMeta";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public MetadataMetaQueryBuilder WithLanguage(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("language", alias, [include, skip]);

    public MetadataMetaQueryBuilder ExceptLanguage() => ExceptField("language");
}

