// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class MintPolicyQueryBuilder : GraphQlQueryBuilder<MintPolicyQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "forceCollapsingSupply" },
        new() { Name = "maxTokenCount" },
        new() { Name = "maxTokenSupply" }
    };

    protected override string TypeName => "MintPolicy";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public MintPolicyQueryBuilder WithForceCollapsingSupply(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("forceCollapsingSupply", alias, [include, skip]);

    public MintPolicyQueryBuilder ExceptForceCollapsingSupply() => ExceptField("forceCollapsingSupply");

    public MintPolicyQueryBuilder WithMaxTokenCount(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("maxTokenCount", alias, [include, skip]);

    public MintPolicyQueryBuilder ExceptMaxTokenCount() => ExceptField("maxTokenCount");

    public MintPolicyQueryBuilder WithMaxTokenSupply(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("maxTokenSupply", alias, [include, skip]);

    public MintPolicyQueryBuilder ExceptMaxTokenSupply() => ExceptField("maxTokenSupply");
}

