// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class MutationQueryBuilder : GraphQlQueryBuilder<MutationQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "AuthenticatePusherSocket", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(PusherSocketAuthQueryBuilder) },
        new() { Name = "CreateTransaction", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(TransactionQueryBuilder) },
        new() { Name = "CreateBatchTransaction", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(TransactionQueryBuilder) },
        new() { Name = "CreateLinkingCode", IsComplex = true, QueryBuilderType = typeof(LinkingCodeQueryBuilder) },
        new() { Name = "CreateManagedWallet", RequiresParameters = true },
        new() { Name = "RefreshMetadata", RequiresParameters = true },
        new() { Name = "SignTransaction", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(TransactionQueryBuilder) },
        new() { Name = "SweepManagedWallet", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(SweepManagedWalletResultQueryBuilder) }
    };

    protected override string TypeName => "Mutation";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public MutationQueryBuilder(string? operationName = null) : base("mutation", operationName)
    {
    }

    public MutationQueryBuilder WithParameter<T>(GraphQlQueryParameter<T> parameter) => WithParameterInternal(parameter);

    /// <param name="id">The socket identifier assigned by Pusher.</param>
    public MutationQueryBuilder WithAuthenticatePusherSocket(PusherSocketAuthQueryBuilder pusherSocketAuthQueryBuilder, QueryBuilderParameter<string> id, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "id", ArgumentValue = id} );
        return WithObjectField("AuthenticatePusherSocket", alias, pusherSocketAuthQueryBuilder, [include, skip], args);
    }

    public MutationQueryBuilder ExceptAuthenticatePusherSocket() => ExceptField("AuthenticatePusherSocket");

    /// <param name="network">The network to mutate.</param>
    /// <param name="chain">The chain to mutate.</param>
    /// <param name="signerAddress">The SS58 address or public key of the signer. (mutually exclusive with signerExternalId)</param>
    /// <param name="signerExternalId">A user-defined external identifier, used with the daemon, to be used to sign the transaction. (mutually exclusive with signerAddress)</param>
    /// <param name="idempotencyKey">An optional idempotency key. A validation error will occur if the key already exists.</param>
    /// <param name="proxyAddress">Wrap the call in Proxy.proxy with this address as the real origin.</param>
    /// <param name="fuelTank">Wrap the call in FuelTanks.dispatch_and_touch using this tank address.</param>
    /// <param name="fuelTankRuleSetId">The fuel tank rule set id to dispatch against. Defaults to 0. Only used when fuelTank is provided.</param>
    /// <param name="transaction">The transaction details including the underlying method and required attributes.</param>
    public MutationQueryBuilder WithCreateTransaction(TransactionQueryBuilder transactionQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<TransactionInput> transaction, QueryBuilderParameter<string?>? signerAddress = null, QueryBuilderParameter<string?>? signerExternalId = null, QueryBuilderParameter<string?>? idempotencyKey = null, QueryBuilderParameter<string?>? proxyAddress = null, QueryBuilderParameter<string?>? fuelTank = null, QueryBuilderParameter<int?>? fuelTankRuleSetId = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (signerAddress != null)
            args.Add(new() { ArgumentName = "signerAddress", ArgumentValue = signerAddress} );

        if (signerExternalId != null)
            args.Add(new() { ArgumentName = "signerExternalId", ArgumentValue = signerExternalId} );

        if (idempotencyKey != null)
            args.Add(new() { ArgumentName = "idempotencyKey", ArgumentValue = idempotencyKey} );

        if (proxyAddress != null)
            args.Add(new() { ArgumentName = "proxyAddress", ArgumentValue = proxyAddress} );

        if (fuelTank != null)
            args.Add(new() { ArgumentName = "fuelTank", ArgumentValue = fuelTank} );

        if (fuelTankRuleSetId != null)
            args.Add(new() { ArgumentName = "fuelTankRuleSetId", ArgumentValue = fuelTankRuleSetId} );

        args.Add(new() { ArgumentName = "transaction", ArgumentValue = transaction} );
        return WithObjectField("CreateTransaction", alias, transactionQueryBuilder, [include, skip], args);
    }

    public MutationQueryBuilder ExceptCreateTransaction() => ExceptField("CreateTransaction");

    /// <param name="network">The network to mutate.</param>
    /// <param name="chain">The chain to mutate.</param>
    /// <param name="signerAddress">The SS58 address or public key of the signer. (mutually exclusive with signerExternalId)</param>
    /// <param name="signerExternalId">A user-defined external identifier, used with the daemon, to be used to sign the transaction. (mutually exclusive with signerAddress)</param>
    /// <param name="idempotencyKey">An optional idempotency key. A validation error will occur if the key already exists.</param>
    /// <param name="proxyAddress">Wrap the call in Proxy.proxy with this address as the real origin.</param>
    /// <param name="fuelTank">Wrap the call in FuelTanks.dispatch_and_touch using this tank address.</param>
    /// <param name="fuelTankRuleSetId">The fuel tank rule set id to dispatch against. Defaults to 0. Only used when fuelTank is provided.</param>
    /// <param name="transactions">The list of transactions to encode.</param>
    /// <param name="batchMode">Determines whether the batch halts, continues, or reverts when a call fails.</param>
    public MutationQueryBuilder WithCreateBatchTransaction(TransactionQueryBuilder transactionQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<IEnumerable<TransactionInput>> transactions, QueryBuilderParameter<BatchTransactionModeEnum> batchMode, QueryBuilderParameter<string?>? signerAddress = null, QueryBuilderParameter<string?>? signerExternalId = null, QueryBuilderParameter<string?>? idempotencyKey = null, QueryBuilderParameter<string?>? proxyAddress = null, QueryBuilderParameter<string?>? fuelTank = null, QueryBuilderParameter<int?>? fuelTankRuleSetId = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (signerAddress != null)
            args.Add(new() { ArgumentName = "signerAddress", ArgumentValue = signerAddress} );

        if (signerExternalId != null)
            args.Add(new() { ArgumentName = "signerExternalId", ArgumentValue = signerExternalId} );

        if (idempotencyKey != null)
            args.Add(new() { ArgumentName = "idempotencyKey", ArgumentValue = idempotencyKey} );

        if (proxyAddress != null)
            args.Add(new() { ArgumentName = "proxyAddress", ArgumentValue = proxyAddress} );

        if (fuelTank != null)
            args.Add(new() { ArgumentName = "fuelTank", ArgumentValue = fuelTank} );

        if (fuelTankRuleSetId != null)
            args.Add(new() { ArgumentName = "fuelTankRuleSetId", ArgumentValue = fuelTankRuleSetId} );

        args.Add(new() { ArgumentName = "transactions", ArgumentValue = transactions} );
        args.Add(new() { ArgumentName = "batchMode", ArgumentValue = batchMode} );
        return WithObjectField("CreateBatchTransaction", alias, transactionQueryBuilder, [include, skip], args);
    }

    public MutationQueryBuilder ExceptCreateBatchTransaction() => ExceptField("CreateBatchTransaction");

    /// <param name="idempotencyKey">An optional idempotency key. A validation error will occur if the key already exists.</param>
    public MutationQueryBuilder WithCreateLinkingCode(LinkingCodeQueryBuilder linkingCodeQueryBuilder, QueryBuilderParameter<string?>? idempotencyKey = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        if (idempotencyKey != null)
            args.Add(new() { ArgumentName = "idempotencyKey", ArgumentValue = idempotencyKey} );

        return WithObjectField("CreateLinkingCode", alias, linkingCodeQueryBuilder, [include, skip], args);
    }

    public MutationQueryBuilder ExceptCreateLinkingCode() => ExceptField("CreateLinkingCode");

    /// <param name="externalId">A user-defined external identifier.</param>
    public MutationQueryBuilder WithCreateManagedWallet(QueryBuilderParameter<string> externalId, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "externalId", ArgumentValue = externalId} );
        return WithScalarField("CreateManagedWallet", alias, [include, skip], args);
    }

    public MutationQueryBuilder ExceptCreateManagedWallet() => ExceptField("CreateManagedWallet");

    /// <param name="network">The network to mutate.</param>
    /// <param name="chain">The chain to mutate.</param>
    /// <param name="ids">The full token ID, e.g. "2100-1" (mutually exclusive with collectionId,uris).</param>
    /// <param name="collectionId">The collection identifier. (mutually exclusive with ids,uris)</param>
    /// <param name="tokenIds">A list of token identifiers associated with the collectionId. (requires collectionId, mutually exclusive with ids,uris).</param>
    /// <param name="uris">A list of URIs corresponding to the location of the Metadata file. (mutually exclusive with ids,collectionId).</param>
    public MutationQueryBuilder WithRefreshMetadata(QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<IEnumerable<string>>? ids = null, QueryBuilderParameter<global::System.Numerics.BigInteger?>? collectionId = null, QueryBuilderParameter<IEnumerable<global::System.Numerics.BigInteger>>? tokenIds = null, QueryBuilderParameter<IEnumerable<string>>? uris = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (ids != null)
            args.Add(new() { ArgumentName = "ids", ArgumentValue = ids} );

        if (collectionId != null)
            args.Add(new() { ArgumentName = "collectionId", ArgumentValue = collectionId} );

        if (tokenIds != null)
            args.Add(new() { ArgumentName = "tokenIds", ArgumentValue = tokenIds} );

        if (uris != null)
            args.Add(new() { ArgumentName = "uris", ArgumentValue = uris} );

        return WithScalarField("RefreshMetadata", alias, [include, skip], args);
    }

    public MutationQueryBuilder ExceptRefreshMetadata() => ExceptField("RefreshMetadata");

    /// <param name="uuid">The UUID of the pending transaction.</param>
    /// <param name="signedExtrinsic">The signed extrinsic.</param>
    public MutationQueryBuilder WithSignTransaction(TransactionQueryBuilder transactionQueryBuilder, QueryBuilderParameter<string> uuid, QueryBuilderParameter<string> signedExtrinsic, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "uuid", ArgumentValue = uuid} );
        args.Add(new() { ArgumentName = "signedExtrinsic", ArgumentValue = signedExtrinsic} );
        return WithObjectField("SignTransaction", alias, transactionQueryBuilder, [include, skip], args);
    }

    public MutationQueryBuilder ExceptSignTransaction() => ExceptField("SignTransaction");

    /// <param name="network">The network to mutate.</param>
    /// <param name="chain">The chain to mutate.</param>
    /// <param name="signerAddress">The SS58 address or public key of the signer. (mutually exclusive with signerExternalId)</param>
    /// <param name="signerExternalId">A user-defined external identifier, used with the daemon, to be used to sign the transaction. (mutually exclusive with signerAddress)</param>
    /// <param name="recipient">The address to which all swept funds and tokens will be sent.</param>
    /// <param name="fuelTank">Optional fuel tank to sponsor the sweep fee. When set, the sweep is dispatched via FuelTanks.dispatch_and_touch.</param>
    /// <param name="fuelTankRuleSetId">The fuel tank rule set id to dispatch against. Defaults to 0. Only used when fuelTank is provided.</param>
    /// <param name="idempotencyPrefix">Optional idempotency prefix for the sweep transactions; each chunk is keyed as "{prefix}-{n}". Generated by the platform when omitted.</param>
    public MutationQueryBuilder WithSweepManagedWallet(SweepManagedWalletResultQueryBuilder sweepManagedWalletResultQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> recipient, QueryBuilderParameter<string?>? signerAddress = null, QueryBuilderParameter<string?>? signerExternalId = null, QueryBuilderParameter<string?>? fuelTank = null, QueryBuilderParameter<int?>? fuelTankRuleSetId = null, QueryBuilderParameter<string?>? idempotencyPrefix = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (signerAddress != null)
            args.Add(new() { ArgumentName = "signerAddress", ArgumentValue = signerAddress} );

        if (signerExternalId != null)
            args.Add(new() { ArgumentName = "signerExternalId", ArgumentValue = signerExternalId} );

        args.Add(new() { ArgumentName = "recipient", ArgumentValue = recipient} );
        if (fuelTank != null)
            args.Add(new() { ArgumentName = "fuelTank", ArgumentValue = fuelTank} );

        if (fuelTankRuleSetId != null)
            args.Add(new() { ArgumentName = "fuelTankRuleSetId", ArgumentValue = fuelTankRuleSetId} );

        if (idempotencyPrefix != null)
            args.Add(new() { ArgumentName = "idempotencyPrefix", ArgumentValue = idempotencyPrefix} );

        return WithObjectField("SweepManagedWallet", alias, sweepManagedWalletResultQueryBuilder, [include, skip], args);
    }

    public MutationQueryBuilder ExceptSweepManagedWallet() => ExceptField("SweepManagedWallet");
}

