// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class NominationPoolQueryBuilder : GraphQlQueryBuilder<NominationPoolQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "name" },
        new() { Name = "state" },
        new() { Name = "capacity" },
        new() { Name = "balance", IsComplex = true, QueryBuilderType = typeof(PoolBalanceQueryBuilder) },
        new() { Name = "commission" },
        new() { Name = "apy" },
        new() { Name = "totalMembers" },
        new() { Name = "members", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(PoolMemberQueryBuilder) }
    };

    protected override string TypeName => "NominationPool";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public NominationPoolQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public NominationPoolQueryBuilder ExceptId() => ExceptField("id");

    public NominationPoolQueryBuilder WithName(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("name", alias, [include, skip]);

    public NominationPoolQueryBuilder ExceptName() => ExceptField("name");

    public NominationPoolQueryBuilder WithState(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("state", alias, [include, skip]);

    public NominationPoolQueryBuilder ExceptState() => ExceptField("state");

    public NominationPoolQueryBuilder WithCapacity(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("capacity", alias, [include, skip]);

    public NominationPoolQueryBuilder ExceptCapacity() => ExceptField("capacity");

    public NominationPoolQueryBuilder WithBalance(PoolBalanceQueryBuilder poolBalanceQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("balance", alias, poolBalanceQueryBuilder, [include, skip]);

    public NominationPoolQueryBuilder ExceptBalance() => ExceptField("balance");

    public NominationPoolQueryBuilder WithCommission(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("commission", alias, [include, skip]);

    public NominationPoolQueryBuilder ExceptCommission() => ExceptField("commission");

    public NominationPoolQueryBuilder WithApy(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("apy", alias, [include, skip]);

    public NominationPoolQueryBuilder ExceptApy() => ExceptField("apy");

    public NominationPoolQueryBuilder WithTotalMembers(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("totalMembers", alias, [include, skip]);

    public NominationPoolQueryBuilder ExceptTotalMembers() => ExceptField("totalMembers");

    /// <param name="limit">The number of members to return.</param>
    /// <param name="after">The offset for pagination.</param>
    public NominationPoolQueryBuilder WithMembers(PoolMemberQueryBuilder poolMemberQueryBuilder, QueryBuilderParameter<int> limit, QueryBuilderParameter<int?>? after = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        if (after != null)
            args.Add(new() { ArgumentName = "after", ArgumentValue = after} );

        return WithObjectField("members", alias, poolMemberQueryBuilder, [include, skip], args);
    }

    public NominationPoolQueryBuilder ExceptMembers() => ExceptField("members");
}

