// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class PendingCollectionQueryBuilder : GraphQlQueryBuilder<PendingCollectionQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "owner", IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) },
        new() { Name = "attributes", IsComplex = true, QueryBuilderType = typeof(AttributeQueryBuilder) },
        new() { Name = "metadata", IsComplex = true, QueryBuilderType = typeof(MetadataQueryBuilder) },
        new() { Name = "mintPolicy", IsComplex = true, QueryBuilderType = typeof(MintPolicyQueryBuilder) },
        new() { Name = "marketPolicy", IsComplex = true, QueryBuilderType = typeof(MarketPolicyQueryBuilder) },
        new() { Name = "transferPolicy", IsComplex = true, QueryBuilderType = typeof(TransferPolicyQueryBuilder) },
        new() { Name = "pendingTransfer", IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) }
    };

    protected override string TypeName => "PendingCollection";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public PendingCollectionQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public PendingCollectionQueryBuilder ExceptId() => ExceptField("id");

    public PendingCollectionQueryBuilder WithOwner(AccountQueryBuilder accountQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("owner", alias, accountQueryBuilder, [include, skip]);

    public PendingCollectionQueryBuilder ExceptOwner() => ExceptField("owner");

    public PendingCollectionQueryBuilder WithAttributes(AttributeQueryBuilder attributeQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("attributes", alias, attributeQueryBuilder, [include, skip]);

    public PendingCollectionQueryBuilder ExceptAttributes() => ExceptField("attributes");

    public PendingCollectionQueryBuilder WithMetadata(MetadataQueryBuilder metadataQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("metadata", alias, metadataQueryBuilder, [include, skip]);

    public PendingCollectionQueryBuilder ExceptMetadata() => ExceptField("metadata");

    public PendingCollectionQueryBuilder WithMintPolicy(MintPolicyQueryBuilder mintPolicyQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("mintPolicy", alias, mintPolicyQueryBuilder, [include, skip]);

    public PendingCollectionQueryBuilder ExceptMintPolicy() => ExceptField("mintPolicy");

    public PendingCollectionQueryBuilder WithMarketPolicy(MarketPolicyQueryBuilder marketPolicyQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("marketPolicy", alias, marketPolicyQueryBuilder, [include, skip]);

    public PendingCollectionQueryBuilder ExceptMarketPolicy() => ExceptField("marketPolicy");

    public PendingCollectionQueryBuilder WithTransferPolicy(TransferPolicyQueryBuilder transferPolicyQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("transferPolicy", alias, transferPolicyQueryBuilder, [include, skip]);

    public PendingCollectionQueryBuilder ExceptTransferPolicy() => ExceptField("transferPolicy");

    public PendingCollectionQueryBuilder WithPendingTransfer(AccountQueryBuilder accountQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("pendingTransfer", alias, accountQueryBuilder, [include, skip]);

    public PendingCollectionQueryBuilder ExceptPendingTransfer() => ExceptField("pendingTransfer");
}

