// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class PoolBalanceQueryBuilder : GraphQlQueryBuilder<PoolBalanceQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "stash" },
        new() { Name = "reward" },
        new() { Name = "active" }
    };

    protected override string TypeName => "PoolBalance";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public PoolBalanceQueryBuilder WithStash(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("stash", alias, [include, skip]);

    public PoolBalanceQueryBuilder ExceptStash() => ExceptField("stash");

    public PoolBalanceQueryBuilder WithReward(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("reward", alias, [include, skip]);

    public PoolBalanceQueryBuilder ExceptReward() => ExceptField("reward");

    public PoolBalanceQueryBuilder WithActive(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("active", alias, [include, skip]);

    public PoolBalanceQueryBuilder ExceptActive() => ExceptField("active");
}

