// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class PoolMemberQueryBuilder : GraphQlQueryBuilder<PoolMemberQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "publicKey" },
        new() { Name = "bonded" },
        new() { Name = "unrealisedEnj" }
    };

    protected override string TypeName => "PoolMember";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public PoolMemberQueryBuilder WithPublicKey(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("publicKey", alias, [include, skip]);

    public PoolMemberQueryBuilder ExceptPublicKey() => ExceptField("publicKey");

    public PoolMemberQueryBuilder WithBonded(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("bonded", alias, [include, skip]);

    public PoolMemberQueryBuilder ExceptBonded() => ExceptField("bonded");

    public PoolMemberQueryBuilder WithUnrealisedEnj(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("unrealisedEnj", alias, [include, skip]);

    public PoolMemberQueryBuilder ExceptUnrealisedEnj() => ExceptField("unrealisedEnj");
}

