// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class PusherSocketAuthQueryBuilder : GraphQlQueryBuilder<PusherSocketAuthQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "auth" },
        new() { Name = "channel" }
    };

    protected override string TypeName => "PusherSocketAuth";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public PusherSocketAuthQueryBuilder WithAuth(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("auth", alias, [include, skip]);

    public PusherSocketAuthQueryBuilder ExceptAuth() => ExceptField("auth");

    public PusherSocketAuthQueryBuilder WithChannel(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("channel", alias, [include, skip]);

    public PusherSocketAuthQueryBuilder ExceptChannel() => ExceptField("channel");
}

