// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class QueryQueryBuilder : GraphQlQueryBuilder<QueryQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "GetAccount", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) },
        new() { Name = "GetAccounts", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(AccountQueryBuilder) },
        new() { Name = "GetBlock", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(BlockQueryBuilder) },
        new() { Name = "GetBlocks", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(BlockQueryBuilder) },
        new() { Name = "GetListing", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(ListingQueryBuilder) },
        new() { Name = "GetListings", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(ListingQueryBuilder) },
        new() { Name = "GetManagedWallet", IsComplex = true, QueryBuilderType = typeof(ManagedWalletQueryBuilder) },
        new() { Name = "GetManagedWallets", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(ManagedWalletCursorPaginationQueryBuilder) },
        new() { Name = "ManagedWalletSweepStatus", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(ManagedWalletSweepStatusQueryBuilder) },
        new() { Name = "GetToken", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(TokenQueryBuilder) },
        new() { Name = "GetTokens", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(TokenQueryBuilder) },
        new() { Name = "GetTransaction", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(TransactionQueryBuilder) },
        new() { Name = "GetTransactions", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(TransactionCursorPaginationQueryBuilder) },
        new() { Name = "GetCollection", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(CollectionQueryBuilder) },
        new() { Name = "GetCollections", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(CollectionQueryBuilder) },
        new() { Name = "GetPendingCollectionTransfers", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(PendingCollectionQueryBuilder) },
        new() { Name = "GetExtrinsic", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(ExtrinsicQueryBuilder) },
        new() { Name = "GetExtrinsics", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(ExtrinsicQueryBuilder) },
        new() { Name = "GetLinkedWallet", IsComplex = true, QueryBuilderType = typeof(LinkedWalletQueryBuilder) },
        new() { Name = "VerifyMessage", RequiresParameters = true },
        new() { Name = "GetAccountPools", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(AccountPoolQueryBuilder) },
        new() { Name = "GetNominationPool", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(NominationPoolQueryBuilder) },
        new() { Name = "GetNominationPools", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(NominationPoolQueryBuilder) },
        new() { Name = "GetFuelTank", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(FuelTankQueryBuilder) },
        new() { Name = "GetFuelTanks", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(FuelTankQueryBuilder) },
        new() { Name = "GetFuelTankAccounts", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(FuelTankAccountQueryBuilder) },
        new() { Name = "GetCompatibleFuelTanks", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(CompatibleFuelTankQueryBuilder) }
    };

    protected override string TypeName => "Query";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public QueryQueryBuilder(string? operationName = null) : base("query", operationName)
    {
    }

    public QueryQueryBuilder WithParameter<T>(GraphQlQueryParameter<T> parameter) => WithParameterInternal(parameter);

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="address">The address of the account (either a public key or SS58 address).</param>
    public QueryQueryBuilder WithGetAccount(AccountQueryBuilder accountQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> address, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "address", ArgumentValue = address} );
        return WithObjectField("GetAccount", alias, accountQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetAccount() => ExceptField("GetAccount");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="addresses">The address of the accounts (either public key or SS58 addresses).</param>
    public QueryQueryBuilder WithGetAccounts(AccountQueryBuilder accountQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<IEnumerable<string>> addresses, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "addresses", ArgumentValue = addresses} );
        return WithObjectField("GetAccounts", alias, accountQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetAccounts() => ExceptField("GetAccounts");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="id">The block id (number) (mutually exclusive with hash).</param>
    /// <param name="hash">The block hash (mutually exclusive with id).</param>
    public QueryQueryBuilder WithGetBlock(BlockQueryBuilder blockQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<int?>? id = null, QueryBuilderParameter<string?>? hash = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (id != null)
            args.Add(new() { ArgumentName = "id", ArgumentValue = id} );

        if (hash != null)
            args.Add(new() { ArgumentName = "hash", ArgumentValue = hash} );

        return WithObjectField("GetBlock", alias, blockQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetBlock() => ExceptField("GetBlock");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="ids">The block id (number) (mutually exclusive with hashes).</param>
    /// <param name="hashes">The block hash (mutually exclusive with ids).</param>
    public QueryQueryBuilder WithGetBlocks(BlockQueryBuilder blockQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<IEnumerable<int>>? ids = null, QueryBuilderParameter<IEnumerable<string>>? hashes = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (ids != null)
            args.Add(new() { ArgumentName = "ids", ArgumentValue = ids} );

        if (hashes != null)
            args.Add(new() { ArgumentName = "hashes", ArgumentValue = hashes} );

        return WithObjectField("GetBlocks", alias, blockQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetBlocks() => ExceptField("GetBlocks");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="id">The listing ID.</param>
    public QueryQueryBuilder WithGetListing(ListingQueryBuilder listingQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> id, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "id", ArgumentValue = id} );
        return WithObjectField("GetListing", alias, listingQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetListing() => ExceptField("GetListing");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="collectionId">The collection ID to filter listings by (applies to either asset side).</param>
    /// <param name="tokenIds">Optional token IDs within the collection to filter by.</param>
    /// <param name="limit">Number of listings to return per page (max 100, default 25).</param>
    /// <param name="page">Page number (max 500, default 1).</param>
    public QueryQueryBuilder WithGetListings(ListingQueryBuilder listingQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<global::System.Numerics.BigInteger> collectionId, QueryBuilderParameter<int> limit, QueryBuilderParameter<int> page, QueryBuilderParameter<IEnumerable<global::System.Numerics.BigInteger>>? tokenIds = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "collectionId", ArgumentValue = collectionId} );
        if (tokenIds != null)
            args.Add(new() { ArgumentName = "tokenIds", ArgumentValue = tokenIds} );

        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        args.Add(new() { ArgumentName = "page", ArgumentValue = page} );
        return WithObjectField("GetListings", alias, listingQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetListings() => ExceptField("GetListings");

    /// <param name="publicKey">A list of public keys. (mutually exclusive with externalId)</param>
    /// <param name="externalId">A list of user-defined external identifiers. (mutually exclusive with publicKey)</param>
    public QueryQueryBuilder WithGetManagedWallet(ManagedWalletQueryBuilder managedWalletQueryBuilder, QueryBuilderParameter<string?>? publicKey = null, QueryBuilderParameter<string?>? externalId = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        if (publicKey != null)
            args.Add(new() { ArgumentName = "publicKey", ArgumentValue = publicKey} );

        if (externalId != null)
            args.Add(new() { ArgumentName = "externalId", ArgumentValue = externalId} );

        return WithObjectField("GetManagedWallet", alias, managedWalletQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetManagedWallet() => ExceptField("GetManagedWallet");

    /// <param name="publicKeys">A list of public keys. (mutually exclusive with externalIds)</param>
    /// <param name="externalIds">A list of user-defined external identifiers. (mutually exclusive with publicKeys)</param>
    /// <param name="limit">The number of results to return per page.</param>
    /// <param name="cursor">The cursor for which to paginate using.</param>
    public QueryQueryBuilder WithGetManagedWallets(ManagedWalletCursorPaginationQueryBuilder managedWalletCursorPaginationQueryBuilder, QueryBuilderParameter<int> limit, QueryBuilderParameter<IEnumerable<string>>? publicKeys = null, QueryBuilderParameter<IEnumerable<string>>? externalIds = null, QueryBuilderParameter<string?>? cursor = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        if (publicKeys != null)
            args.Add(new() { ArgumentName = "publicKeys", ArgumentValue = publicKeys} );

        if (externalIds != null)
            args.Add(new() { ArgumentName = "externalIds", ArgumentValue = externalIds} );

        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        if (cursor != null)
            args.Add(new() { ArgumentName = "cursor", ArgumentValue = cursor} );

        return WithObjectField("GetManagedWallets", alias, managedWalletCursorPaginationQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetManagedWallets() => ExceptField("GetManagedWallets");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="externalId">The user-defined external identifier of the managed wallet to inspect.</param>
    public QueryQueryBuilder WithManagedWalletSweepStatus(ManagedWalletSweepStatusQueryBuilder managedWalletSweepStatusQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> externalId, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "externalId", ArgumentValue = externalId} );
        return WithObjectField("ManagedWalletSweepStatus", alias, managedWalletSweepStatusQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptManagedWalletSweepStatus() => ExceptField("ManagedWalletSweepStatus");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="id">The full token ID, e.g. "2100-1" (mutually exclusive with collectionId + tokenId).</param>
    /// <param name="collectionId">The collection ID (used with tokenId).</param>
    /// <param name="tokenId">The token ID within the collection (used with collectionId).</param>
    public QueryQueryBuilder WithGetToken(TokenQueryBuilder tokenQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string?>? id = null, QueryBuilderParameter<global::System.Numerics.BigInteger?>? collectionId = null, QueryBuilderParameter<global::System.Numerics.BigInteger?>? tokenId = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (id != null)
            args.Add(new() { ArgumentName = "id", ArgumentValue = id} );

        if (collectionId != null)
            args.Add(new() { ArgumentName = "collectionId", ArgumentValue = collectionId} );

        if (tokenId != null)
            args.Add(new() { ArgumentName = "tokenId", ArgumentValue = tokenId} );

        return WithObjectField("GetToken", alias, tokenQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetToken() => ExceptField("GetToken");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="collectionId">The collection ID.</param>
    /// <param name="tokenIds">Optional token IDs within the collection (max 100). Can be combined with pagination.</param>
    /// <param name="name">Optional token metadata name substring to search for (case-insensitive).</param>
    /// <param name="limit">Number of tokens to return per page (max 100, default 25).</param>
    /// <param name="page">Page number (max 500, default 1).</param>
    public QueryQueryBuilder WithGetTokens(TokenQueryBuilder tokenQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<global::System.Numerics.BigInteger> collectionId, QueryBuilderParameter<int> limit, QueryBuilderParameter<int> page, QueryBuilderParameter<IEnumerable<global::System.Numerics.BigInteger>>? tokenIds = null, QueryBuilderParameter<string?>? name = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "collectionId", ArgumentValue = collectionId} );
        if (tokenIds != null)
            args.Add(new() { ArgumentName = "tokenIds", ArgumentValue = tokenIds} );

        if (name != null)
            args.Add(new() { ArgumentName = "name", ArgumentValue = name} );

        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        args.Add(new() { ArgumentName = "page", ArgumentValue = page} );
        return WithObjectField("GetTokens", alias, tokenQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetTokens() => ExceptField("GetTokens");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="uuid">The unique identifier, generated by the platform, for the transaction. (mutually exclusive with idempotencyKey, extrinsicHash)</param>
    /// <param name="idempotencyKey">A unique idempotency key, defined by the user. (mutually exclusive with uuid, extrinsicHash)</param>
    /// <param name="extrinsicHash">The on-chain hash of the extrinsic. (mutually exclusive with uuid, idempotencyKey)</param>
    public QueryQueryBuilder WithGetTransaction(TransactionQueryBuilder transactionQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string?>? uuid = null, QueryBuilderParameter<string?>? idempotencyKey = null, QueryBuilderParameter<string?>? extrinsicHash = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (uuid != null)
            args.Add(new() { ArgumentName = "uuid", ArgumentValue = uuid} );

        if (idempotencyKey != null)
            args.Add(new() { ArgumentName = "idempotencyKey", ArgumentValue = idempotencyKey} );

        if (extrinsicHash != null)
            args.Add(new() { ArgumentName = "extrinsicHash", ArgumentValue = extrinsicHash} );

        return WithObjectField("GetTransaction", alias, transactionQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetTransaction() => ExceptField("GetTransaction");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="uuids">The unique identifier, generated by the platform, for the transaction. (mutually exclusive with idempotencyKeys, extrinsicHashes)</param>
    /// <param name="idempotencyKeys">A unique idempotency key, defined by the user. (mutually exclusive with uuids, extrinsicHashes)</param>
    /// <param name="extrinsicHashes">The on-chain hash of the extrinsic. (mutually exclusive with uuids, idempotencyKeys)</param>
    /// <param name="limit">The number of results to return per page.</param>
    /// <param name="cursor">The cursor for which to paginate using.</param>
    public QueryQueryBuilder WithGetTransactions(TransactionCursorPaginationQueryBuilder transactionCursorPaginationQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<int> limit, QueryBuilderParameter<IEnumerable<string>>? uuids = null, QueryBuilderParameter<IEnumerable<string>>? idempotencyKeys = null, QueryBuilderParameter<IEnumerable<string>>? extrinsicHashes = null, QueryBuilderParameter<string?>? cursor = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (uuids != null)
            args.Add(new() { ArgumentName = "uuids", ArgumentValue = uuids} );

        if (idempotencyKeys != null)
            args.Add(new() { ArgumentName = "idempotencyKeys", ArgumentValue = idempotencyKeys} );

        if (extrinsicHashes != null)
            args.Add(new() { ArgumentName = "extrinsicHashes", ArgumentValue = extrinsicHashes} );

        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        if (cursor != null)
            args.Add(new() { ArgumentName = "cursor", ArgumentValue = cursor} );

        return WithObjectField("GetTransactions", alias, transactionCursorPaginationQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetTransactions() => ExceptField("GetTransactions");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="id">The collection ID.</param>
    public QueryQueryBuilder WithGetCollection(CollectionQueryBuilder collectionQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<global::System.Numerics.BigInteger> id, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "id", ArgumentValue = id} );
        return WithObjectField("GetCollection", alias, collectionQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetCollection() => ExceptField("GetCollection");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="ids">The collection IDs. Required if address is not provided.</param>
    /// <param name="address">Filter collections by owner address (public key or SS58). If provided, ids is not required.</param>
    public QueryQueryBuilder WithGetCollections(CollectionQueryBuilder collectionQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<IEnumerable<global::System.Numerics.BigInteger>>? ids = null, QueryBuilderParameter<string?>? address = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (ids != null)
            args.Add(new() { ArgumentName = "ids", ArgumentValue = ids} );

        if (address != null)
            args.Add(new() { ArgumentName = "address", ArgumentValue = address} );

        return WithObjectField("GetCollections", alias, collectionQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetCollections() => ExceptField("GetCollections");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="ids">Filter by collection IDs.</param>
    /// <param name="address">Filter by the target address of the pending transfer (public key or SS58).</param>
    public QueryQueryBuilder WithGetPendingCollectionTransfers(PendingCollectionQueryBuilder pendingCollectionQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<IEnumerable<global::System.Numerics.BigInteger>>? ids = null, QueryBuilderParameter<string?>? address = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (ids != null)
            args.Add(new() { ArgumentName = "ids", ArgumentValue = ids} );

        if (address != null)
            args.Add(new() { ArgumentName = "address", ArgumentValue = address} );

        return WithObjectField("GetPendingCollectionTransfers", alias, pendingCollectionQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetPendingCollectionTransfers() => ExceptField("GetPendingCollectionTransfers");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="hash">The extrinsic hash.</param>
    public QueryQueryBuilder WithGetExtrinsic(ExtrinsicQueryBuilder extrinsicQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> hash, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "hash", ArgumentValue = hash} );
        return WithObjectField("GetExtrinsic", alias, extrinsicQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetExtrinsic() => ExceptField("GetExtrinsic");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="hashes">The extrinsic hashes.</param>
    public QueryQueryBuilder WithGetExtrinsics(ExtrinsicQueryBuilder extrinsicQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<IEnumerable<string>> hashes, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "hashes", ArgumentValue = hashes} );
        return WithObjectField("GetExtrinsics", alias, extrinsicQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetExtrinsics() => ExceptField("GetExtrinsics");

    /// <param name="address">The address of the account (either a public key or SS58 address). (mutually exclusive with idempotencyKey)</param>
    /// <param name="idempotencyKey">The idempotency key assigned when creating a linking code. (mutually exclusive with address)</param>
    public QueryQueryBuilder WithGetLinkedWallet(LinkedWalletQueryBuilder linkedWalletQueryBuilder, QueryBuilderParameter<string?>? address = null, QueryBuilderParameter<string?>? idempotencyKey = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        if (address != null)
            args.Add(new() { ArgumentName = "address", ArgumentValue = address} );

        if (idempotencyKey != null)
            args.Add(new() { ArgumentName = "idempotencyKey", ArgumentValue = idempotencyKey} );

        return WithObjectField("GetLinkedWallet", alias, linkedWalletQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetLinkedWallet() => ExceptField("GetLinkedWallet");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="publicKey">The public key that allegedly signed the message.</param>
    /// <param name="signature">The signature to verify.</param>
    /// <param name="message">The original message.</param>
    public QueryQueryBuilder WithVerifyMessage(QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> publicKey, QueryBuilderParameter<string> signature, QueryBuilderParameter<string> message, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "publicKey", ArgumentValue = publicKey} );
        args.Add(new() { ArgumentName = "signature", ArgumentValue = signature} );
        args.Add(new() { ArgumentName = "message", ArgumentValue = message} );
        return WithScalarField("VerifyMessage", alias, [include, skip], args);
    }

    public QueryQueryBuilder ExceptVerifyMessage() => ExceptField("VerifyMessage");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="address">The SS58 address or public key of the account.</param>
    public QueryQueryBuilder WithGetAccountPools(AccountPoolQueryBuilder accountPoolQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> address, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "address", ArgumentValue = address} );
        return WithObjectField("GetAccountPools", alias, accountPoolQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetAccountPools() => ExceptField("GetAccountPools");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="id">The identifier of the pool.</param>
    public QueryQueryBuilder WithGetNominationPool(NominationPoolQueryBuilder nominationPoolQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<int> id, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "id", ArgumentValue = id} );
        return WithObjectField("GetNominationPool", alias, nominationPoolQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetNominationPool() => ExceptField("GetNominationPool");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="limit">Number of pools to return (default 25, max 100).</param>
    /// <param name="page">Page number for pagination (default 1).</param>
    public QueryQueryBuilder WithGetNominationPools(NominationPoolQueryBuilder nominationPoolQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<int> limit, QueryBuilderParameter<int> page, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        args.Add(new() { ArgumentName = "page", ArgumentValue = page} );
        return WithObjectField("GetNominationPools", alias, nominationPoolQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetNominationPools() => ExceptField("GetNominationPools");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="id">The fuel tank address. Accepts either a 0x-prefixed public key or an SS58 address.</param>
    public QueryQueryBuilder WithGetFuelTank(FuelTankQueryBuilder fuelTankQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> id, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "id", ArgumentValue = id} );
        return WithObjectField("GetFuelTank", alias, fuelTankQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetFuelTank() => ExceptField("GetFuelTank");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="id">Filter to the fuel tank with this address. Accepts either a 0x-prefixed public key or an SS58 address. When combined with name, the two are OR-ed (matches either).</param>
    /// <param name="name">Filter to fuel tanks whose name contains this term (case-insensitive). When combined with id, the two are OR-ed (matches either).</param>
    /// <param name="address">Filter fuel tanks by owner address (public key or SS58). If combined with id and/or name, the owner filter is AND-ed with the other criteria.</param>
    /// <param name="limit">Number of fuel tanks to return (default 25, max 100).</param>
    /// <param name="page">Page number for pagination (default 1).</param>
    public QueryQueryBuilder WithGetFuelTanks(FuelTankQueryBuilder fuelTankQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<int> limit, QueryBuilderParameter<int> page, QueryBuilderParameter<string?>? id = null, QueryBuilderParameter<string?>? name = null, QueryBuilderParameter<string?>? address = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        if (id != null)
            args.Add(new() { ArgumentName = "id", ArgumentValue = id} );

        if (name != null)
            args.Add(new() { ArgumentName = "name", ArgumentValue = name} );

        if (address != null)
            args.Add(new() { ArgumentName = "address", ArgumentValue = address} );

        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        args.Add(new() { ArgumentName = "page", ArgumentValue = page} );
        return WithObjectField("GetFuelTanks", alias, fuelTankQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetFuelTanks() => ExceptField("GetFuelTanks");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="tankId">The fuel tank address. Accepts either a 0x-prefixed public key or an SS58 address.</param>
    /// <param name="address">Filter to a single account address. Accepts either a 0x-prefixed public key or an SS58 address.</param>
    /// <param name="limit">Number of accounts to return (default 25, max 100).</param>
    /// <param name="page">Page number for pagination (default 1).</param>
    public QueryQueryBuilder WithGetFuelTankAccounts(FuelTankAccountQueryBuilder fuelTankAccountQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> tankId, QueryBuilderParameter<int> limit, QueryBuilderParameter<int> page, QueryBuilderParameter<string?>? address = null, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "tankId", ArgumentValue = tankId} );
        if (address != null)
            args.Add(new() { ArgumentName = "address", ArgumentValue = address} );

        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        args.Add(new() { ArgumentName = "page", ArgumentValue = page} );
        return WithObjectField("GetFuelTankAccounts", alias, fuelTankAccountQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetFuelTankAccounts() => ExceptField("GetFuelTankAccounts");

    /// <param name="network">The network to query.</param>
    /// <param name="chain">The chain to query.</param>
    /// <param name="account">The account address that will dispatch the call. Accepts either a 0x-prefixed public key or an SS58 address.</param>
    /// <param name="transactions">Transaction calls to encode and check for compatible fuel tanks.</param>
    /// <param name="batchMode">The batching behavior used when multiple transactions are supplied.</param>
    public QueryQueryBuilder WithGetCompatibleFuelTanks(CompatibleFuelTankQueryBuilder compatibleFuelTankQueryBuilder, QueryBuilderParameter<Network> network, QueryBuilderParameter<Chain> chain, QueryBuilderParameter<string> account, QueryBuilderParameter<IEnumerable<TransactionInput>> transactions, QueryBuilderParameter<BatchTransactionModeEnum> batchMode, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "network", ArgumentValue = network} );
        args.Add(new() { ArgumentName = "chain", ArgumentValue = chain} );
        args.Add(new() { ArgumentName = "account", ArgumentValue = account} );
        args.Add(new() { ArgumentName = "transactions", ArgumentValue = transactions} );
        args.Add(new() { ArgumentName = "batchMode", ArgumentValue = batchMode} );
        return WithObjectField("GetCompatibleFuelTanks", alias, compatibleFuelTankQueryBuilder, [include, skip], args);
    }

    public QueryQueryBuilder ExceptGetCompatibleFuelTanks() => ExceptField("GetCompatibleFuelTanks");
}

