// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class RequireTokenQueryBuilder : GraphQlQueryBuilder<RequireTokenQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "collectionId" },
        new() { Name = "tokenId" }
    };

    protected override string TypeName => "RequireToken";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public RequireTokenQueryBuilder WithCollectionId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("collectionId", alias, [include, skip]);

    public RequireTokenQueryBuilder ExceptCollectionId() => ExceptField("collectionId");

    public RequireTokenQueryBuilder WithTokenId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("tokenId", alias, [include, skip]);

    public RequireTokenQueryBuilder ExceptTokenId() => ExceptField("tokenId");
}

