// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class RoyaltyBeneficiaryQueryBuilder : GraphQlQueryBuilder<RoyaltyBeneficiaryQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "accountId" },
        new() { Name = "percentage" }
    };

    protected override string TypeName => "RoyaltyBeneficiary";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public RoyaltyBeneficiaryQueryBuilder WithAccountId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("accountId", alias, [include, skip]);

    public RoyaltyBeneficiaryQueryBuilder ExceptAccountId() => ExceptField("accountId");

    public RoyaltyBeneficiaryQueryBuilder WithPercentage(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("percentage", alias, [include, skip]);

    public RoyaltyBeneficiaryQueryBuilder ExceptPercentage() => ExceptField("percentage");
}

