// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class SweepManagedWalletResultQueryBuilder : GraphQlQueryBuilder<SweepManagedWalletResultQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "accepted" },
        new() { Name = "idempotencyPrefix" }
    };

    protected override string TypeName => "SweepManagedWalletResult";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public SweepManagedWalletResultQueryBuilder WithAccepted(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("accepted", alias, [include, skip]);

    public SweepManagedWalletResultQueryBuilder ExceptAccepted() => ExceptField("accepted");

    public SweepManagedWalletResultQueryBuilder WithIdempotencyPrefix(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("idempotencyPrefix", alias, [include, skip]);

    public SweepManagedWalletResultQueryBuilder ExceptIdempotencyPrefix() => ExceptField("idempotencyPrefix");
}

