// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class TokenGroupTokenQueryBuilder : GraphQlQueryBuilder<TokenGroupTokenQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "tokenGroupId" },
        new() { Name = "collectionId" },
        new() { Name = "tokenId" },
        new() { Name = "position" },
        new() { Name = "token", IsComplex = true, QueryBuilderType = typeof(TokenQueryBuilder) },
        new() { Name = "tokenGroup", IsComplex = true, QueryBuilderType = typeof(TokenGroupQueryBuilder) }
    };

    protected override string TypeName => "TokenGroupToken";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public TokenGroupTokenQueryBuilder WithTokenGroupId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("tokenGroupId", alias, [include, skip]);

    public TokenGroupTokenQueryBuilder ExceptTokenGroupId() => ExceptField("tokenGroupId");

    public TokenGroupTokenQueryBuilder WithCollectionId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("collectionId", alias, [include, skip]);

    public TokenGroupTokenQueryBuilder ExceptCollectionId() => ExceptField("collectionId");

    public TokenGroupTokenQueryBuilder WithTokenId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("tokenId", alias, [include, skip]);

    public TokenGroupTokenQueryBuilder ExceptTokenId() => ExceptField("tokenId");

    public TokenGroupTokenQueryBuilder WithPosition(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("position", alias, [include, skip]);

    public TokenGroupTokenQueryBuilder ExceptPosition() => ExceptField("position");

    public TokenGroupTokenQueryBuilder WithToken(TokenQueryBuilder tokenQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("token", alias, tokenQueryBuilder, [include, skip]);

    public TokenGroupTokenQueryBuilder ExceptToken() => ExceptField("token");

    public TokenGroupTokenQueryBuilder WithTokenGroup(TokenGroupQueryBuilder tokenGroupQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("tokenGroup", alias, tokenGroupQueryBuilder, [include, skip]);

    public TokenGroupTokenQueryBuilder ExceptTokenGroup() => ExceptField("tokenGroup");
}

