// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class TokenCapQueryBuilder : GraphQlQueryBuilder<TokenCapQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "__typename" },
        new() { Name = "type" },
        new() { Name = "supply" }
    };

    protected override string TypeName => "TokenCap";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public TokenCapQueryBuilder WithTypeName(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("__typename", alias, [include, skip]);

    public TokenCapQueryBuilder ExceptTypeName() => ExceptField("__typename");

    public TokenCapQueryBuilder WithType(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("type", alias, [include, skip]);

    public TokenCapQueryBuilder ExceptType() => ExceptField("type");

    public TokenCapQueryBuilder WithSupply(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("supply", alias, [include, skip]);

    public TokenCapQueryBuilder ExceptSupply() => ExceptField("supply");
}

