// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class TokenQueryBuilder : GraphQlQueryBuilder<TokenQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "tokenId" },
        new() { Name = "supply" },
        new() { Name = "isFrozen" },
        new() { Name = "isNonFungible" },
        new() { Name = "isListingForbidden" },
        new() { Name = "infusion" },
        new() { Name = "anyoneCanInfuse" },
        new() { Name = "attributes", IsComplex = true, QueryBuilderType = typeof(AttributeQueryBuilder) },
        new() { Name = "metadata", IsComplex = true, QueryBuilderType = typeof(MetadataQueryBuilder) },
        new() { Name = "behavior", IsComplex = true, QueryBuilderType = typeof(TokenBehaviorQueryBuilder) },
        new() { Name = "cap", IsComplex = true, QueryBuilderType = typeof(TokenCapQueryBuilder) },
        new() { Name = "tokenGroupTokens", IsComplex = true, QueryBuilderType = typeof(TokenGroupTokenQueryBuilder) },
        new() { Name = "collection", IsComplex = true, QueryBuilderType = typeof(CollectionQueryBuilder) },
        new() { Name = "holders", RequiresParameters = true, IsComplex = true, QueryBuilderType = typeof(TokenHolderQueryBuilder) }
    };

    protected override string TypeName => "Token";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public TokenQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public TokenQueryBuilder ExceptId() => ExceptField("id");

    public TokenQueryBuilder WithTokenId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("tokenId", alias, [include, skip]);

    public TokenQueryBuilder ExceptTokenId() => ExceptField("tokenId");

    public TokenQueryBuilder WithSupply(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("supply", alias, [include, skip]);

    public TokenQueryBuilder ExceptSupply() => ExceptField("supply");

    public TokenQueryBuilder WithIsFrozen(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("isFrozen", alias, [include, skip]);

    public TokenQueryBuilder ExceptIsFrozen() => ExceptField("isFrozen");

    public TokenQueryBuilder WithIsNonFungible(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("isNonFungible", alias, [include, skip]);

    public TokenQueryBuilder ExceptIsNonFungible() => ExceptField("isNonFungible");

    public TokenQueryBuilder WithIsListingForbidden(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("isListingForbidden", alias, [include, skip]);

    public TokenQueryBuilder ExceptIsListingForbidden() => ExceptField("isListingForbidden");

    public TokenQueryBuilder WithInfusion(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("infusion", alias, [include, skip]);

    public TokenQueryBuilder ExceptInfusion() => ExceptField("infusion");

    public TokenQueryBuilder WithAnyoneCanInfuse(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("anyoneCanInfuse", alias, [include, skip]);

    public TokenQueryBuilder ExceptAnyoneCanInfuse() => ExceptField("anyoneCanInfuse");

    public TokenQueryBuilder WithAttributes(AttributeQueryBuilder attributeQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("attributes", alias, attributeQueryBuilder, [include, skip]);

    public TokenQueryBuilder ExceptAttributes() => ExceptField("attributes");

    public TokenQueryBuilder WithMetadata(MetadataQueryBuilder metadataQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("metadata", alias, metadataQueryBuilder, [include, skip]);

    public TokenQueryBuilder ExceptMetadata() => ExceptField("metadata");

    public TokenQueryBuilder WithBehavior(TokenBehaviorQueryBuilder tokenBehaviorQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("behavior", alias, tokenBehaviorQueryBuilder, [include, skip]);

    public TokenQueryBuilder ExceptBehavior() => ExceptField("behavior");

    public TokenQueryBuilder WithCap(TokenCapQueryBuilder tokenCapQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("cap", alias, tokenCapQueryBuilder, [include, skip]);

    public TokenQueryBuilder ExceptCap() => ExceptField("cap");

    public TokenQueryBuilder WithTokenGroupTokens(TokenGroupTokenQueryBuilder tokenGroupTokenQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("tokenGroupTokens", alias, tokenGroupTokenQueryBuilder, [include, skip]);

    public TokenQueryBuilder ExceptTokenGroupTokens() => ExceptField("tokenGroupTokens");

    public TokenQueryBuilder WithCollection(CollectionQueryBuilder collectionQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("collection", alias, collectionQueryBuilder, [include, skip]);

    public TokenQueryBuilder ExceptCollection() => ExceptField("collection");

    /// <param name="limit">Number of holders to return per page (max 100, default 100).</param>
    /// <param name="page">Page number (max 500, default 1).</param>
    public TokenQueryBuilder WithHolders(TokenHolderQueryBuilder tokenHolderQueryBuilder, QueryBuilderParameter<int> limit, QueryBuilderParameter<int> page, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null)
    {
        var args = new List<QueryBuilderArgumentInfo>();
        args.Add(new() { ArgumentName = "limit", ArgumentValue = limit} );
        args.Add(new() { ArgumentName = "page", ArgumentValue = page} );
        return WithObjectField("holders", alias, tokenHolderQueryBuilder, [include, skip], args);
    }

    public TokenQueryBuilder ExceptHolders() => ExceptField("holders");
}

