// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class TokenBehaviorQueryBuilder : GraphQlQueryBuilder<TokenBehaviorQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "__typename" },
        new() { Name = "beneficiaries", IsComplex = true, QueryBuilderType = typeof(RoyaltyBeneficiaryQueryBuilder) }
    };

    protected override string TypeName => "TokenBehavior";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public TokenBehaviorQueryBuilder WithTypeName(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("__typename", alias, [include, skip]);

    public TokenBehaviorQueryBuilder ExceptTypeName() => ExceptField("__typename");

    public TokenBehaviorQueryBuilder WithBeneficiaries(RoyaltyBeneficiaryQueryBuilder royaltyBeneficiaryQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("beneficiaries", alias, royaltyBeneficiaryQueryBuilder, [include, skip]);

    public TokenBehaviorQueryBuilder ExceptBeneficiaries() => ExceptField("beneficiaries");
}

