// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class TokenHolderQueryBuilder : GraphQlQueryBuilder<TokenHolderQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "address" },
        new() { Name = "amount" }
    };

    protected override string TypeName => "TokenHolder";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public TokenHolderQueryBuilder WithAddress(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("address", alias, [include, skip]);

    public TokenHolderQueryBuilder ExceptAddress() => ExceptField("address");

    public TokenHolderQueryBuilder WithAmount(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("amount", alias, [include, skip]);

    public TokenHolderQueryBuilder ExceptAmount() => ExceptField("amount");
}

