// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class TokenGroupQueryBuilder : GraphQlQueryBuilder<TokenGroupQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "id" },
        new() { Name = "collectionId" },
        new() { Name = "attributes", IsComplex = true, QueryBuilderType = typeof(AttributeQueryBuilder) },
        new() { Name = "metadata", IsComplex = true, QueryBuilderType = typeof(MetadataQueryBuilder) },
        new() { Name = "tokenGroupTokens", IsComplex = true, QueryBuilderType = typeof(TokenGroupTokenQueryBuilder) }
    };

    protected override string TypeName => "TokenGroup";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public TokenGroupQueryBuilder WithId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("id", alias, [include, skip]);

    public TokenGroupQueryBuilder ExceptId() => ExceptField("id");

    public TokenGroupQueryBuilder WithCollectionId(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("collectionId", alias, [include, skip]);

    public TokenGroupQueryBuilder ExceptCollectionId() => ExceptField("collectionId");

    public TokenGroupQueryBuilder WithAttributes(AttributeQueryBuilder attributeQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("attributes", alias, attributeQueryBuilder, [include, skip]);

    public TokenGroupQueryBuilder ExceptAttributes() => ExceptField("attributes");

    public TokenGroupQueryBuilder WithMetadata(MetadataQueryBuilder metadataQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("metadata", alias, metadataQueryBuilder, [include, skip]);

    public TokenGroupQueryBuilder ExceptMetadata() => ExceptField("metadata");

    public TokenGroupQueryBuilder WithTokenGroupTokens(TokenGroupTokenQueryBuilder tokenGroupTokenQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("tokenGroupTokens", alias, tokenGroupTokenQueryBuilder, [include, skip]);

    public TokenGroupQueryBuilder ExceptTokenGroupTokens() => ExceptField("tokenGroupTokens");
}

