// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class TransferPolicyQueryBuilder : GraphQlQueryBuilder<TransferPolicyQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "isFrozen" }
    };

    protected override string TypeName => "TransferPolicy";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public TransferPolicyQueryBuilder WithIsFrozen(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("isFrozen", alias, [include, skip]);

    public TransferPolicyQueryBuilder ExceptIsFrozen() => ExceptField("isFrozen");
}

