// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

public partial class TransactionCursorPaginationQueryBuilder : GraphQlQueryBuilder<TransactionCursorPaginationQueryBuilder>
{
    private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
    {
        new() { Name = "data", IsComplex = true, QueryBuilderType = typeof(TransactionQueryBuilder) },
        new() { Name = "perPage" },
        new() { Name = "previousCursor" },
        new() { Name = "nextCursor" }
    };

    protected override string TypeName => "TransactionCursorPagination";

    public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

    public TransactionCursorPaginationQueryBuilder WithData(TransactionQueryBuilder transactionQueryBuilder, string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithObjectField("data", alias, transactionQueryBuilder, [include, skip]);

    public TransactionCursorPaginationQueryBuilder ExceptData() => ExceptField("data");

    public TransactionCursorPaginationQueryBuilder WithPerPage(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("perPage", alias, [include, skip]);

    public TransactionCursorPaginationQueryBuilder ExceptPerPage() => ExceptField("perPage");

    public TransactionCursorPaginationQueryBuilder WithPreviousCursor(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("previousCursor", alias, [include, skip]);

    public TransactionCursorPaginationQueryBuilder ExceptPreviousCursor() => ExceptField("previousCursor");

    public TransactionCursorPaginationQueryBuilder WithNextCursor(string? alias = null, IncludeDirective? include = null, SkipDirective? skip = null) => WithScalarField("nextCursor", alias, [include, skip]);

    public TransactionCursorPaginationQueryBuilder ExceptNextCursor() => ExceptField("nextCursor");
}

