// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A single account rule applied when a user account is added. Provide exactly one of the variant fields per object.
/// </summary>
public partial class AccountRuleInput : IGraphQlInputObject
{
    private InputPropertyInfo _whitelistedCallers;
    private InputPropertyInfo _requireToken;

    /// <summary>
    /// Only these caller addresses may be added as user accounts.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
    #endif
    public QueryBuilderParameter<ICollection<string>?>? WhitelistedCallers
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_whitelistedCallers.Value;
        set => _whitelistedCallers = new() { Name = "whitelistedCallers", Value = value };
    }

    /// <summary>
    /// Caller must hold the referenced token to be added as a user account.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<RequireTokenInput?>))]
    #endif
    public QueryBuilderParameter<RequireTokenInput?>? RequireToken
    {
        get => (QueryBuilderParameter<RequireTokenInput?>?)_requireToken.Value;
        set => _requireToken = new() { Name = "requireToken", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_whitelistedCallers.Name != null) yield return _whitelistedCallers;
        if (_requireToken.Name != null) yield return _requireToken;
    }
}

