// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for adding a user account to a fuel tank (FuelTanks.add_account).
/// </summary>
public partial class AddAccountInput : IGraphQlInputObject
{
    private InputPropertyInfo _tankId;
    private InputPropertyInfo _address;

    /// <summary>
    /// The fuel tank address.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? TankId
    {
        get => (QueryBuilderParameter<string?>?)_tankId.Value;
        set => _tankId = new() { Name = "tankId", Value = value };
    }

    /// <summary>
    /// The user account address to add.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Address
    {
        get => (QueryBuilderParameter<string?>?)_address.Value;
        set => _address = new() { Name = "address", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_tankId.Name != null) yield return _tankId;
        if (_address.Name != null) yield return _address;
    }
}

