// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for adding multiple user accounts in one call (FuelTanks.batch_add_account).
/// </summary>
public partial class AddAccountsInput : IGraphQlInputObject
{
    private InputPropertyInfo _tankId;
    private InputPropertyInfo _addresses;

    /// <summary>
    /// The fuel tank address.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? TankId
    {
        get => (QueryBuilderParameter<string?>?)_tankId.Value;
        set => _tankId = new() { Name = "tankId", Value = value };
    }

    /// <summary>
    /// List of user account addresses to add. 1–100 entries.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
    #endif
    public QueryBuilderParameter<ICollection<string>?>? Addresses
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_addresses.Value;
        set => _addresses = new() { Name = "addresses", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_tankId.Name != null) yield return _tankId;
        if (_addresses.Name != null) yield return _addresses;
    }
}

