// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for adding accounts to a listing whitelist (Marketplace.add_whitelisted_accounts).
/// </summary>
public partial class AddWhitelistedAccountsInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _accounts;

    /// <summary>
    /// The ID of the listing as a 0x-prefixed hash.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Id
    {
        get => (QueryBuilderParameter<string?>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// Accounts (SS58 address or public key) to whitelist, with optional per-account allowances.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<WhitelistedAccountInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<WhitelistedAccountInput>?>? Accounts
    {
        get => (QueryBuilderParameter<ICollection<WhitelistedAccountInput>?>?)_accounts.Value;
        set => _accounts = new() { Name = "accounts", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_accounts.Name != null) yield return _accounts;
    }
}

