// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for answering a counter offer on a listing (Marketplace.answer_counter_offer).
/// </summary>
public partial class AnswerCounterOfferInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _creator;
    private InputPropertyInfo _response;
    private InputPropertyInfo _counterPrice;

    /// <summary>
    /// The ID of the listing as a 0x-prefixed hash.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Id
    {
        get => (QueryBuilderParameter<string?>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// The SS58 address or public key of the account that placed the counter offer.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Creator
    {
        get => (QueryBuilderParameter<string?>?)_creator.Value;
        set => _creator = new() { Name = "creator", Value = value };
    }

    /// <summary>
    /// The response: Accept, Reject, or Counter.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CounterOfferResponseEnum?>))]
    #endif
    public QueryBuilderParameter<CounterOfferResponseEnum?>? Response
    {
        get => (QueryBuilderParameter<CounterOfferResponseEnum?>?)_response.Value;
        set => _response = new() { Name = "response", Value = value };
    }

    /// <summary>
    /// Required when response is Counter — the new counter price, expressed as a decimal or integer ENJ (e.g. "1.5"); converted to base units on-chain.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? CounterPrice
    {
        get => (QueryBuilderParameter<string?>?)_counterPrice.Value;
        set => _counterPrice = new() { Name = "counterPrice", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_creator.Name != null) yield return _creator;
        if (_response.Name != null) yield return _response;
        if (_counterPrice.Name != null) yield return _counterPrice;
    }
}

