// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input for batch transfer of token balances via MultiTokens.batch_transfer.
/// </summary>
public partial class BatchTransferInput : IGraphQlInputObject
{
    private InputPropertyInfo _collectionId;
    private InputPropertyInfo _recipients;

    /// <summary>
    /// The collection the tokens belong to.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? CollectionId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_collectionId.Value;
        set => _collectionId = new() { Name = "collectionId", Value = value };
    }

    /// <summary>
    /// The list of token transfers to perform for the collection.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<TransferTokenEntryInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<TransferTokenEntryInput>?>? Recipients
    {
        get => (QueryBuilderParameter<ICollection<TransferTokenEntryInput>?>?)_recipients.Value;
        set => _recipients = new() { Name = "recipients", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_collectionId.Name != null) yield return _collectionId;
        if (_recipients.Name != null) yield return _recipients;
    }
}

