// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for batch setting attributes on a token (MultiTokens.batch_set_attribute).
/// </summary>
public partial class BatchSetTokenAttributeInput : IGraphQlInputObject
{
    private InputPropertyInfo _collectionId;
    private InputPropertyInfo _tokenId;
    private InputPropertyInfo _attributes;

    /// <summary>
    /// The collection ID containing the token.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? CollectionId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_collectionId.Value;
        set => _collectionId = new() { Name = "collectionId", Value = value };
    }

    /// <summary>
    /// The token ID to set the attributes on.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? TokenId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_tokenId.Value;
        set => _tokenId = new() { Name = "tokenId", Value = value };
    }

    /// <summary>
    /// The list of key-value attribute pairs to set.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<AttributeInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<AttributeInput>?>? Attributes
    {
        get => (QueryBuilderParameter<ICollection<AttributeInput>?>?)_attributes.Value;
        set => _attributes = new() { Name = "attributes", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_collectionId.Name != null) yield return _collectionId;
        if (_tokenId.Name != null) yield return _tokenId;
        if (_attributes.Name != null) yield return _attributes;
    }
}

