// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for burning a token (MultiTokens.burn).
/// </summary>
public partial class BurnTokenInput : IGraphQlInputObject
{
    private InputPropertyInfo _collectionId;
    private InputPropertyInfo _tokenId;
    private InputPropertyInfo _amount;
    private InputPropertyInfo _removeTokenStorage;

    /// <summary>
    /// The collection the token belongs to.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? CollectionId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_collectionId.Value;
        set => _collectionId = new() { Name = "collectionId", Value = value };
    }

    /// <summary>
    /// The token to burn.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? TokenId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_tokenId.Value;
        set => _tokenId = new() { Name = "tokenId", Value = value };
    }

    /// <summary>
    /// The amount of the token to burn.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? Amount
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_amount.Value;
        set => _amount = new() { Name = "amount", Value = value };
    }

    /// <summary>
    /// Whether to remove the on-chain storage deposit after all supply is destroyed.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
    #endif
    public QueryBuilderParameter<bool?>? RemoveTokenStorage
    {
        get => (QueryBuilderParameter<bool?>?)_removeTokenStorage.Value;
        set => _removeTokenStorage = new() { Name = "removeTokenStorage", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_collectionId.Name != null) yield return _collectionId;
        if (_tokenId.Name != null) yield return _tokenId;
        if (_amount.Name != null) yield return _amount;
        if (_removeTokenStorage.Name != null) yield return _removeTokenStorage;
    }
}

