// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for minting a new token (MultiTokens.mint with CreateToken params).
/// </summary>
public partial class CreateTokenInput : IGraphQlInputObject
{
    private InputPropertyInfo _recipient;
    private InputPropertyInfo _collectionId;
    private InputPropertyInfo _tokenId;
    private InputPropertyInfo _initialSupply;
    private InputPropertyInfo _listingForbidden;
    private InputPropertyInfo _cap;
    private InputPropertyInfo _behavior;
    private InputPropertyInfo _freezeState;
    private InputPropertyInfo _attributes;
    private InputPropertyInfo _infusion;
    private InputPropertyInfo _anyoneCanInfuse;
    private InputPropertyInfo _groups;

    /// <summary>
    /// The SS58 address or public key of the token recipient.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Recipient
    {
        get => (QueryBuilderParameter<string?>?)_recipient.Value;
        set => _recipient = new() { Name = "recipient", Value = value };
    }

    /// <summary>
    /// The collection to mint the token in.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? CollectionId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_collectionId.Value;
        set => _collectionId = new() { Name = "collectionId", Value = value };
    }

    /// <summary>
    /// The token ID to create.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? TokenId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_tokenId.Value;
        set => _tokenId = new() { Name = "tokenId", Value = value };
    }

    /// <summary>
    /// The initial supply to mint.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? InitialSupply
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_initialSupply.Value;
        set => _initialSupply = new() { Name = "initialSupply", Value = value };
    }

    /// <summary>
    /// Whether the token is forbidden from being listed on the marketplace.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
    #endif
    public QueryBuilderParameter<bool?>? ListingForbidden
    {
        get => (QueryBuilderParameter<bool?>?)_listingForbidden.Value;
        set => _listingForbidden = new() { Name = "listingForbidden", Value = value };
    }

    /// <summary>
    /// Supply cap for the token. Omit for no cap.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<TokenCapInput?>))]
    #endif
    public QueryBuilderParameter<TokenCapInput?>? Cap
    {
        get => (QueryBuilderParameter<TokenCapInput?>?)_cap.Value;
        set => _cap = new() { Name = "cap", Value = value };
    }

    /// <summary>
    /// Token behavior: IS_CURRENCY (with name/symbol/decimalCount) or HAS_ROYALTY (with royalty beneficiary).
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<TokenBehaviorInput?>))]
    #endif
    public QueryBuilderParameter<TokenBehaviorInput?>? Behavior
    {
        get => (QueryBuilderParameter<TokenBehaviorInput?>?)_behavior.Value;
        set => _behavior = new() { Name = "behavior", Value = value };
    }

    /// <summary>
    /// The initial freeze state of the token. Omit to create the token unfrozen and freezable later.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<FreezeState?>))]
    #endif
    public QueryBuilderParameter<FreezeState?>? FreezeState
    {
        get => (QueryBuilderParameter<FreezeState?>?)_freezeState.Value;
        set => _freezeState = new() { Name = "freezeState", Value = value };
    }

    /// <summary>
    /// Key-value attributes to attach to the token on-chain.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<AttributeInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<AttributeInput>?>? Attributes
    {
        get => (QueryBuilderParameter<ICollection<AttributeInput>?>?)_attributes.Value;
        set => _attributes = new() { Name = "attributes", Value = value };
    }

    /// <summary>
    /// Amount of ENJ infused into the token at creation, expressed as a decimal or integer ENJ (e.g. "1.5"); converted to base units on-chain.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
    #endif
    public QueryBuilderParameter<string>? Infusion
    {
        get => (QueryBuilderParameter<string>?)_infusion.Value;
        set => _infusion = new() { Name = "infusion", Value = value };
    }

    /// <summary>
    /// Whether anyone can infuse this token (not just the collection owner).
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
    #endif
    public QueryBuilderParameter<bool?>? AnyoneCanInfuse
    {
        get => (QueryBuilderParameter<bool?>?)_anyoneCanInfuse.Value;
        set => _anyoneCanInfuse = new() { Name = "anyoneCanInfuse", Value = value };
    }

    /// <summary>
    /// Group IDs this token belongs to.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<global::System.Numerics.BigInteger>?>))]
    #endif
    public QueryBuilderParameter<ICollection<global::System.Numerics.BigInteger>?>? Groups
    {
        get => (QueryBuilderParameter<ICollection<global::System.Numerics.BigInteger>?>?)_groups.Value;
        set => _groups = new() { Name = "groups", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_recipient.Name != null) yield return _recipient;
        if (_collectionId.Name != null) yield return _collectionId;
        if (_tokenId.Name != null) yield return _tokenId;
        if (_initialSupply.Name != null) yield return _initialSupply;
        if (_listingForbidden.Name != null) yield return _listingForbidden;
        if (_cap.Name != null) yield return _cap;
        if (_behavior.Name != null) yield return _behavior;
        if (_freezeState.Name != null) yield return _freezeState;
        if (_attributes.Name != null) yield return _attributes;
        if (_infusion.Name != null) yield return _infusion;
        if (_anyoneCanInfuse.Name != null) yield return _anyoneCanInfuse;
        if (_groups.Name != null) yield return _groups;
    }
}

