// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for inserting or replacing a rule set (FuelTanks.insert_rule_set). Upsert semantics: if a rule set with the given id exists, it is replaced.
/// </summary>
public partial class CreateRuleSetInput : IGraphQlInputObject
{
    private InputPropertyInfo _tankId;
    private InputPropertyInfo _id;
    private InputPropertyInfo _rules;
    private InputPropertyInfo _requireAccount;

    /// <summary>
    /// The fuel tank address.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? TankId
    {
        get => (QueryBuilderParameter<string?>?)_tankId.Value;
        set => _tankId = new() { Name = "tankId", Value = value };
    }

    /// <summary>
    /// The rule set id to insert or replace.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
    #endif
    public QueryBuilderParameter<int?>? Id
    {
        get => (QueryBuilderParameter<int?>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// The dispatch rules that apply to this rule set. At least one is required.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<DispatchRuleInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<DispatchRuleInput>?>? Rules
    {
        get => (QueryBuilderParameter<ICollection<DispatchRuleInput>?>?)_rules.Value;
        set => _rules = new() { Name = "rules", Value = value };
    }

    /// <summary>
    /// If true, only registered user accounts may use this rule set.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
    #endif
    public QueryBuilderParameter<bool?>? RequireAccount
    {
        get => (QueryBuilderParameter<bool?>?)_requireAccount.Value;
        set => _requireAccount = new() { Name = "requireAccount", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_tankId.Name != null) yield return _tankId;
        if (_id.Name != null) yield return _id;
        if (_rules.Name != null) yield return _rules;
        if (_requireAccount.Name != null) yield return _requireAccount;
    }
}

