// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for creating a fuel tank (FuelTanks.create_fuel_tank).
/// </summary>
public partial class CreateFuelTankInput : IGraphQlInputObject
{
    private InputPropertyInfo _name;
    private InputPropertyInfo _coveragePolicy;
    private InputPropertyInfo _userAccountManagement;
    private InputPropertyInfo _ruleSets;
    private InputPropertyInfo _accountRules;
    private InputPropertyInfo _accountExpiration;

    /// <summary>
    /// The fuel tank display name. Up to 32 bytes after UTF-8 encoding.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Name
    {
        get => (QueryBuilderParameter<string?>?)_name.Value;
        set => _name = new() { Name = "name", Value = value };
    }

    /// <summary>
    /// Whether the tank covers transaction fees only (FEES) or also the storage deposit (FEES_AND_DEPOSIT).
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CoveragePolicy?>))]
    #endif
    public QueryBuilderParameter<CoveragePolicy?>? CoveragePolicy
    {
        get => (QueryBuilderParameter<CoveragePolicy?>?)_coveragePolicy.Value;
        set => _coveragePolicy = new() { Name = "coveragePolicy", Value = value };
    }

    /// <summary>
    /// Optional user account deposit settings. Omit if the tank should not manage user deposits.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<UserAccountManagementInput?>))]
    #endif
    public QueryBuilderParameter<UserAccountManagementInput?>? UserAccountManagement
    {
        get => (QueryBuilderParameter<UserAccountManagementInput?>?)_userAccountManagement.Value;
        set => _userAccountManagement = new() { Name = "userAccountManagement", Value = value };
    }

    /// <summary>
    /// Rule sets to create with the tank, each paired with its numeric id. At least one rule set is required — the chain rejects a tank with no rule sets.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<RuleSetEntryInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<RuleSetEntryInput>?>? RuleSets
    {
        get => (QueryBuilderParameter<ICollection<RuleSetEntryInput>?>?)_ruleSets.Value;
        set => _ruleSets = new() { Name = "ruleSets", Value = value };
    }

    /// <summary>
    /// Account rules applied to all user accounts on this tank.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<AccountRuleInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<AccountRuleInput>?>? AccountRules
    {
        get => (QueryBuilderParameter<ICollection<AccountRuleInput>?>?)_accountRules.Value;
        set => _accountRules = new() { Name = "accountRules", Value = value };
    }

    /// <summary>
    /// Optional number of blocks after which idle user accounts expire and can be cleared.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
    #endif
    public QueryBuilderParameter<int?>? AccountExpiration
    {
        get => (QueryBuilderParameter<int?>?)_accountExpiration.Value;
        set => _accountExpiration = new() { Name = "accountExpiration", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_name.Name != null) yield return _name;
        if (_coveragePolicy.Name != null) yield return _coveragePolicy;
        if (_userAccountManagement.Name != null) yield return _userAccountManagement;
        if (_ruleSets.Name != null) yield return _ruleSets;
        if (_accountRules.Name != null) yield return _accountRules;
        if (_accountExpiration.Name != null) yield return _accountExpiration;
    }
}

