// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A single dispatch rule for a rule set. Provide exactly one of the variant fields per object.
/// </summary>
public partial class DispatchRuleInput : IGraphQlInputObject
{
    private InputPropertyInfo _whitelistedCallers;
    private InputPropertyInfo _whitelistedCollections;
    private InputPropertyInfo _whitelistedPallets;
    private InputPropertyInfo _maxFuelBurnPerTransaction;
    private InputPropertyInfo _minimumInfusion;
    private InputPropertyInfo _userFuelBudget;
    private InputPropertyInfo _tankFuelBudget;
    private InputPropertyInfo _requireToken;
    private InputPropertyInfo _permittedCalls;
    private InputPropertyInfo _permittedExtrinsics;
    private InputPropertyInfo _requireSignature;

    /// <summary>
    /// Only these caller addresses may use this rule set.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
    #endif
    public QueryBuilderParameter<ICollection<string>?>? WhitelistedCallers
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_whitelistedCallers.Value;
        set => _whitelistedCallers = new() { Name = "whitelistedCallers", Value = value };
    }

    /// <summary>
    /// Only calls targeting these collection ids are permitted.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<global::System.Numerics.BigInteger>?>))]
    #endif
    public QueryBuilderParameter<ICollection<global::System.Numerics.BigInteger>?>? WhitelistedCollections
    {
        get => (QueryBuilderParameter<ICollection<global::System.Numerics.BigInteger>?>?)_whitelistedCollections.Value;
        set => _whitelistedCollections = new() { Name = "whitelistedCollections", Value = value };
    }

    /// <summary>
    /// Only calls targeting these pallets are permitted.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<FuelTankWhitelistedPallet>?>))]
    #endif
    public QueryBuilderParameter<ICollection<FuelTankWhitelistedPallet>?>? WhitelistedPallets
    {
        get => (QueryBuilderParameter<ICollection<FuelTankWhitelistedPallet>?>?)_whitelistedPallets.Value;
        set => _whitelistedPallets = new() { Name = "whitelistedPallets", Value = value };
    }

    /// <summary>
    /// Maximum fuel that any single transaction under this rule set may burn, expressed as ENJ (e.g. "1.5" for 1.5 ENJ; converted to base units on-chain).
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? MaxFuelBurnPerTransaction
    {
        get => (QueryBuilderParameter<string?>?)_maxFuelBurnPerTransaction.Value;
        set => _maxFuelBurnPerTransaction = new() { Name = "maxFuelBurnPerTransaction", Value = value };
    }

    /// <summary>
    /// Minimum amount that must be infused into the fuel tank for this rule set to take effect, expressed as ENJ (e.g. "1.5" for 1.5 ENJ; converted to base units on-chain).
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? MinimumInfusion
    {
        get => (QueryBuilderParameter<string?>?)_minimumInfusion.Value;
        set => _minimumInfusion = new() { Name = "minimumInfusion", Value = value };
    }

    /// <summary>
    /// Per-user fuel budget that resets every resetPeriod blocks.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<FuelBudgetRuleInput?>))]
    #endif
    public QueryBuilderParameter<FuelBudgetRuleInput?>? UserFuelBudget
    {
        get => (QueryBuilderParameter<FuelBudgetRuleInput?>?)_userFuelBudget.Value;
        set => _userFuelBudget = new() { Name = "userFuelBudget", Value = value };
    }

    /// <summary>
    /// Tank-wide fuel budget that resets every resetPeriod blocks.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<FuelBudgetRuleInput?>))]
    #endif
    public QueryBuilderParameter<FuelBudgetRuleInput?>? TankFuelBudget
    {
        get => (QueryBuilderParameter<FuelBudgetRuleInput?>?)_tankFuelBudget.Value;
        set => _tankFuelBudget = new() { Name = "tankFuelBudget", Value = value };
    }

    /// <summary>
    /// Callers must hold the referenced token to use this rule set.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<RequireTokenInput?>))]
    #endif
    public QueryBuilderParameter<RequireTokenInput?>? RequireToken
    {
        get => (QueryBuilderParameter<RequireTokenInput?>?)_requireToken.Value;
        set => _requireToken = new() { Name = "requireToken", Value = value };
    }

    /// <summary>
    /// Permitted call hashes — list of 0x-prefixed 64-character blake2_256 hex digests. Compute the hash client-side from the SCALE-encoded call.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
    #endif
    public QueryBuilderParameter<ICollection<string>?>? PermittedCalls
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_permittedCalls.Value;
        set => _permittedCalls = new() { Name = "permittedCalls", Value = value };
    }

    /// <summary>
    /// Only these specific extrinsics (pallet + method) are permitted.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<FuelTankPermittedMethod>?>))]
    #endif
    public QueryBuilderParameter<ICollection<FuelTankPermittedMethod>?>? PermittedExtrinsics
    {
        get => (QueryBuilderParameter<ICollection<FuelTankPermittedMethod>?>?)_permittedExtrinsics.Value;
        set => _permittedExtrinsics = new() { Name = "permittedExtrinsics", Value = value };
    }

    /// <summary>
    /// Calls under this rule set must include a signature from this signer address.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? RequireSignature
    {
        get => (QueryBuilderParameter<string?>?)_requireSignature.Value;
        set => _requireSignature = new() { Name = "requireSignature", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_whitelistedCallers.Name != null) yield return _whitelistedCallers;
        if (_whitelistedCollections.Name != null) yield return _whitelistedCollections;
        if (_whitelistedPallets.Name != null) yield return _whitelistedPallets;
        if (_maxFuelBurnPerTransaction.Name != null) yield return _maxFuelBurnPerTransaction;
        if (_minimumInfusion.Name != null) yield return _minimumInfusion;
        if (_userFuelBudget.Name != null) yield return _userFuelBudget;
        if (_tankFuelBudget.Name != null) yield return _tankFuelBudget;
        if (_requireToken.Name != null) yield return _requireToken;
        if (_permittedCalls.Name != null) yield return _permittedCalls;
        if (_permittedExtrinsics.Name != null) yield return _permittedExtrinsics;
        if (_requireSignature.Name != null) yield return _requireSignature;
    }
}

