// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for filling a marketplace listing (Marketplace.fill_listing).
/// </summary>
public partial class FillListingInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _amount;

    /// <summary>
    /// The ID of the listing as a 0x-prefixed hash.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Id
    {
        get => (QueryBuilderParameter<string?>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// The amount to fill from the listing.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? Amount
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_amount.Value;
        set => _amount = new() { Name = "amount", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_amount.Name != null) yield return _amount;
    }
}

