// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A capped amount of fuel that resets every resetPeriod blocks. Used by userFuelBudget and tankFuelBudget rules.
/// </summary>
public partial class FuelBudgetRuleInput : IGraphQlInputObject
{
    private InputPropertyInfo _amount;
    private InputPropertyInfo _resetPeriod;

    /// <summary>
    /// The maximum fuel spend per reset period, expressed as ENJ (e.g. "1.5" for 1.5 ENJ; converted to base units on-chain).
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
    #endif
    public QueryBuilderParameter<string>? Amount
    {
        get => (QueryBuilderParameter<string>?)_amount.Value;
        set => _amount = new() { Name = "amount", Value = value };
    }

    /// <summary>
    /// The number of blocks after which the budget refills. Must be at most 4294967295 (MAX_UINT32).
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? ResetPeriod
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_resetPeriod.Value;
        set => _resetPeriod = new() { Name = "resetPeriod", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_amount.Name != null) yield return _amount;
        if (_resetPeriod.Name != null) yield return _resetPeriod;
    }
}

