// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for infusing a token with currency via MultiTokens.infuse. Note: signer authorization validation (anyoneCanInfuse flag / collection ownership) is deferred to a future task.
/// </summary>
public partial class InfuseTokenInput : IGraphQlInputObject
{
    private InputPropertyInfo _collectionId;
    private InputPropertyInfo _tokenId;
    private InputPropertyInfo _amount;

    /// <summary>
    /// The collection the token belongs to.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? CollectionId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_collectionId.Value;
        set => _collectionId = new() { Name = "collectionId", Value = value };
    }

    /// <summary>
    /// The token ID to infuse with currency.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? TokenId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_tokenId.Value;
        set => _tokenId = new() { Name = "tokenId", Value = value };
    }

    /// <summary>
    /// The amount of ENJ currency to infuse into the token, expressed as a decimal or integer ENJ (e.g. "1.5"); converted to base units on-chain.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
    #endif
    public QueryBuilderParameter<string>? Amount
    {
        get => (QueryBuilderParameter<string>?)_amount.Value;
        set => _amount = new() { Name = "amount", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_collectionId.Name != null) yield return _collectionId;
        if (_tokenId.Name != null) yield return _tokenId;
        if (_amount.Name != null) yield return _amount;
    }
}

