// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A single token entry for batch infusion via MultiTokens.batch_infuse. The collectionId is specified on the parent InfuseTokensInput.
/// </summary>
public partial class InfuseTokenEntryInput : IGraphQlInputObject
{
    private InputPropertyInfo _tokenId;
    private InputPropertyInfo _amount;

    /// <summary>
    /// The token ID to infuse with currency.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? TokenId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_tokenId.Value;
        set => _tokenId = new() { Name = "tokenId", Value = value };
    }

    /// <summary>
    /// The amount of currency to infuse into the token.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? Amount
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_amount.Value;
        set => _amount = new() { Name = "amount", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_tokenId.Name != null) yield return _tokenId;
        if (_amount.Name != null) yield return _amount;
    }
}

