// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// The marketplace listing variant and its variant-specific fields.
/// </summary>
public partial class ListingDataInput : IGraphQlInputObject
{
    private InputPropertyInfo _type;
    private InputPropertyInfo _startBlock;
    private InputPropertyInfo _endBlock;
    private InputPropertyInfo _expiration;

    /// <summary>
    /// The listing type to create: fixed price, auction, or offer.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ListingTypeEnum?>))]
    #endif
    public QueryBuilderParameter<ListingTypeEnum?>? Type
    {
        get => (QueryBuilderParameter<ListingTypeEnum?>?)_type.Value;
        set => _type = new() { Name = "type", Value = value };
    }

    /// <summary>
    /// Auction-only start block.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger?>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger?>? StartBlock
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger?>?)_startBlock.Value;
        set => _startBlock = new() { Name = "startBlock", Value = value };
    }

    /// <summary>
    /// Auction-only end block.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger?>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger?>? EndBlock
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger?>?)_endBlock.Value;
        set => _endBlock = new() { Name = "endBlock", Value = value };
    }

    /// <summary>
    /// Optional offer expiration block.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger?>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger?>? Expiration
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger?>?)_expiration.Value;
        set => _expiration = new() { Name = "expiration", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_type.Name != null) yield return _type;
        if (_startBlock.Name != null) yield return _startBlock;
        if (_endBlock.Name != null) yield return _endBlock;
        if (_expiration.Name != null) yield return _expiration;
    }
}

