// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for mutating a token (MultiTokens.mutate_token).
/// </summary>
public partial class MutateTokenInput : IGraphQlInputObject
{
    private InputPropertyInfo _collectionId;
    private InputPropertyInfo _tokenId;
    private InputPropertyInfo _behavior;
    private InputPropertyInfo _listingForbidden;
    private InputPropertyInfo _anyoneCanInfuse;
    private InputPropertyInfo _name;
    private InputPropertyInfo _attributes;

    /// <summary>
    /// The collection ID containing the token to mutate.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? CollectionId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_collectionId.Value;
        set => _collectionId = new() { Name = "collectionId", Value = value };
    }

    /// <summary>
    /// The token ID to mutate.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? TokenId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_tokenId.Value;
        set => _tokenId = new() { Name = "tokenId", Value = value };
    }

    /// <summary>
    /// Optional token market behavior mutation. Omit to keep unchanged, set to null to clear, or provide a value to update.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<TokenBehaviorInput?>))]
    #endif
    public QueryBuilderParameter<TokenBehaviorInput?>? Behavior
    {
        get => (QueryBuilderParameter<TokenBehaviorInput?>?)_behavior.Value;
        set => _behavior = new() { Name = "behavior", Value = value };
    }

    /// <summary>
    /// Optional listing forbidden flag mutation. Omit to keep unchanged, or provide a boolean to update.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
    #endif
    public QueryBuilderParameter<bool?>? ListingForbidden
    {
        get => (QueryBuilderParameter<bool?>?)_listingForbidden.Value;
        set => _listingForbidden = new() { Name = "listingForbidden", Value = value };
    }

    /// <summary>
    /// Optional anyoneCanInfuse flag mutation. Omit to keep unchanged, or provide a boolean to update.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
    #endif
    public QueryBuilderParameter<bool?>? AnyoneCanInfuse
    {
        get => (QueryBuilderParameter<bool?>?)_anyoneCanInfuse.Value;
        set => _anyoneCanInfuse = new() { Name = "anyoneCanInfuse", Value = value };
    }

    /// <summary>
    /// Optional token name mutation. Omit to keep unchanged, or provide a string to update.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Name
    {
        get => (QueryBuilderParameter<string?>?)_name.Value;
        set => _name = new() { Name = "name", Value = value };
    }

    /// <summary>
    /// Key-value attributes to attach to the token on-chain.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<AttributeInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<AttributeInput>?>? Attributes
    {
        get => (QueryBuilderParameter<ICollection<AttributeInput>?>?)_attributes.Value;
        set => _attributes = new() { Name = "attributes", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_collectionId.Name != null) yield return _collectionId;
        if (_tokenId.Name != null) yield return _tokenId;
        if (_behavior.Name != null) yield return _behavior;
        if (_listingForbidden.Name != null) yield return _listingForbidden;
        if (_anyoneCanInfuse.Name != null) yield return _anyoneCanInfuse;
        if (_name.Name != null) yield return _name;
        if (_attributes.Name != null) yield return _attributes;
    }
}

