// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for mutating a collection (MultiTokens.mutate_collection).
/// </summary>
public partial class MutateCollectionInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _owner;
    private InputPropertyInfo _royalties;
    private InputPropertyInfo _explicitRoyaltyCurrencies;
    private InputPropertyInfo _attributes;

    /// <summary>
    /// The collection ID to mutate.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? Id
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// Optional new owner account (SS58 address or public key).
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Owner
    {
        get => (QueryBuilderParameter<string?>?)_owner.Value;
        set => _owner = new() { Name = "owner", Value = value };
    }

    /// <summary>
    /// Optional market policy royalty beneficiaries. Omit to keep unchanged.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<RoyaltyInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<RoyaltyInput>?>? Royalties
    {
        get => (QueryBuilderParameter<ICollection<RoyaltyInput>?>?)_royalties.Value;
        set => _royalties = new() { Name = "royalties", Value = value };
    }

    /// <summary>
    /// Optional explicit list of token currencies accepted for royalty payments.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<RoyaltyCurrencyInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<RoyaltyCurrencyInput>?>? ExplicitRoyaltyCurrencies
    {
        get => (QueryBuilderParameter<ICollection<RoyaltyCurrencyInput>?>?)_explicitRoyaltyCurrencies.Value;
        set => _explicitRoyaltyCurrencies = new() { Name = "explicitRoyaltyCurrencies", Value = value };
    }

    /// <summary>
    /// Key-value attributes to attach to the collection on-chain.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<AttributeInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<AttributeInput>?>? Attributes
    {
        get => (QueryBuilderParameter<ICollection<AttributeInput>?>?)_attributes.Value;
        set => _attributes = new() { Name = "attributes", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_owner.Name != null) yield return _owner;
        if (_royalties.Name != null) yield return _royalties;
        if (_explicitRoyaltyCurrencies.Name != null) yield return _explicitRoyaltyCurrencies;
        if (_attributes.Name != null) yield return _attributes;
    }
}

