// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for mutating an existing fuel tank (FuelTanks.mutate_fuel_tank).
/// </summary>
public partial class MutateFuelTankInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _name;
    private InputPropertyInfo _coveragePolicy;
    private InputPropertyInfo _userAccountManagement;
    private InputPropertyInfo _accountRules;
    private InputPropertyInfo _owner;
    private InputPropertyInfo _accountExpiration;

    /// <summary>
    /// The fuel tank address to mutate.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Id
    {
        get => (QueryBuilderParameter<string?>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// Optional new display name (up to 32 bytes). Omit to keep unchanged.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Name
    {
        get => (QueryBuilderParameter<string?>?)_name.Value;
        set => _name = new() { Name = "name", Value = value };
    }

    /// <summary>
    /// Optional new coverage policy. Omit to keep unchanged.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CoveragePolicy?>))]
    #endif
    public QueryBuilderParameter<CoveragePolicy?>? CoveragePolicy
    {
        get => (QueryBuilderParameter<CoveragePolicy?>?)_coveragePolicy.Value;
        set => _coveragePolicy = new() { Name = "coveragePolicy", Value = value };
    }

    /// <summary>
    /// Three-state mutation envelope for user account management settings. Omit to keep unchanged.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ShouldMutateUserAccountManagementInput?>))]
    #endif
    public QueryBuilderParameter<ShouldMutateUserAccountManagementInput?>? UserAccountManagement
    {
        get => (QueryBuilderParameter<ShouldMutateUserAccountManagementInput?>?)_userAccountManagement.Value;
        set => _userAccountManagement = new() { Name = "userAccountManagement", Value = value };
    }

    /// <summary>
    /// Optional replacement account rules. Omit to keep unchanged; provide [] to clear all account rules.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<AccountRuleInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<AccountRuleInput>?>? AccountRules
    {
        get => (QueryBuilderParameter<ICollection<AccountRuleInput>?>?)_accountRules.Value;
        set => _accountRules = new() { Name = "accountRules", Value = value };
    }

    /// <summary>
    /// Optional new tank owner address. Omit to keep unchanged. Cannot be cleared.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Owner
    {
        get => (QueryBuilderParameter<string?>?)_owner.Value;
        set => _owner = new() { Name = "owner", Value = value };
    }

    /// <summary>
    /// Three-state mutation envelope for account expiration (in blocks). Omit to keep unchanged.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ShouldMutateAccountExpirationInput?>))]
    #endif
    public QueryBuilderParameter<ShouldMutateAccountExpirationInput?>? AccountExpiration
    {
        get => (QueryBuilderParameter<ShouldMutateAccountExpirationInput?>?)_accountExpiration.Value;
        set => _accountExpiration = new() { Name = "accountExpiration", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_name.Name != null) yield return _name;
        if (_coveragePolicy.Name != null) yield return _coveragePolicy;
        if (_userAccountManagement.Name != null) yield return _userAccountManagement;
        if (_accountRules.Name != null) yield return _accountRules;
        if (_owner.Name != null) yield return _owner;
        if (_accountExpiration.Name != null) yield return _accountExpiration;
    }
}

