// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input for bonding into a nomination pool.
/// </summary>
public partial class NominationPoolsBondInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _amount;
    private InputPropertyInfo _fill;

    /// <summary>
    /// The pool ID to bond into.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
    #endif
    public QueryBuilderParameter<int?>? Id
    {
        get => (QueryBuilderParameter<int?>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// The specific amount to bond, expressed as ENJ (e.g. "1.5" for 1.5 ENJ; converted to base units on-chain). Mutually exclusive with fill.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Amount
    {
        get => (QueryBuilderParameter<string?>?)_amount.Value;
        set => _amount = new() { Name = "amount", Value = value };
    }

    /// <summary>
    /// Bond up to pool capacity. Mutually exclusive with amount.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
    #endif
    public QueryBuilderParameter<bool?>? Fill
    {
        get => (QueryBuilderParameter<bool?>?)_fill.Value;
        set => _fill = new() { Name = "fill", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_amount.Name != null) yield return _amount;
        if (_fill.Name != null) yield return _fill;
    }
}

