// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input for initiating unbonding from a nomination pool.
/// </summary>
public partial class NominationPoolsUnbondInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _unbondingPoints;

    /// <summary>
    /// The pool ID to unbond from.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
    #endif
    public QueryBuilderParameter<int?>? Id
    {
        get => (QueryBuilderParameter<int?>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// The number of points to unbond.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? UnbondingPoints
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_unbondingPoints.Value;
        set => _unbondingPoints = new() { Name = "unbondingPoints", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_unbondingPoints.Name != null) yield return _unbondingPoints;
    }
}

