// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for removing a rule set (FuelTanks.remove_rule_set). The tank or the rule set must be frozen first.
/// </summary>
public partial class RemoveRuleSetInput : IGraphQlInputObject
{
    private InputPropertyInfo _tankId;
    private InputPropertyInfo _id;

    /// <summary>
    /// The fuel tank address.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? TankId
    {
        get => (QueryBuilderParameter<string?>?)_tankId.Value;
        set => _tankId = new() { Name = "tankId", Value = value };
    }

    /// <summary>
    /// The rule set id to remove.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
    #endif
    public QueryBuilderParameter<int?>? Id
    {
        get => (QueryBuilderParameter<int?>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_tankId.Name != null) yield return _tankId;
        if (_id.Name != null) yield return _id;
    }
}

