// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for removing accounts from a listing whitelist (Marketplace.remove_whitelisted_accounts).
/// </summary>
public partial class RemoveWhitelistedAccountsInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _addresses;

    /// <summary>
    /// The listing ID as a 0x-prefixed hash.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Id
    {
        get => (QueryBuilderParameter<string?>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// The SS58 addresses or public keys to remove from the whitelist.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>?>))]
    #endif
    public QueryBuilderParameter<ICollection<string>?>? Addresses
    {
        get => (QueryBuilderParameter<ICollection<string>?>?)_addresses.Value;
        set => _addresses = new() { Name = "addresses", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_addresses.Name != null) yield return _addresses;
    }
}

