// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A royalty beneficiary with an account address and percentage share.
/// </summary>
public partial class RoyaltyInput : IGraphQlInputObject
{
    private InputPropertyInfo _address;
    private InputPropertyInfo _percentage;

    /// <summary>
    /// The SS58 address or hex public key of the royalty beneficiary.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Address
    {
        get => (QueryBuilderParameter<string?>?)_address.Value;
        set => _address = new() { Name = "address", Value = value };
    }

    /// <summary>
    /// The royalty percentage (e.g. 5.0 for 5%). Each entry must be between 0 and 50, and the total royalty percentage per transaction cannot exceed 50.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<decimal?>))]
    #endif
    public QueryBuilderParameter<decimal?>? Percentage
    {
        get => (QueryBuilderParameter<decimal?>?)_percentage.Value;
        set => _percentage = new() { Name = "percentage", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_address.Name != null) yield return _address;
        if (_percentage.Name != null) yield return _percentage;
    }
}

