// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for setting an attribute on a collection (MultiTokens.set_attribute).
/// </summary>
public partial class SetCollectionAttributeInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _key;
    private InputPropertyInfo _value;

    /// <summary>
    /// The collection ID to set the attribute on.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? Id
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// The attribute key.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Key
    {
        get => (QueryBuilderParameter<string?>?)_key.Value;
        set => _key = new() { Name = "key", Value = value };
    }

    /// <summary>
    /// The attribute value.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Value
    {
        get => (QueryBuilderParameter<string?>?)_value.Value;
        set => _value = new() { Name = "value", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_key.Name != null) yield return _key;
        if (_value.Name != null) yield return _value;
    }
}

