// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for setting an attribute on a token (MultiTokens.set_attribute).
/// </summary>
public partial class SetTokenAttributeInput : IGraphQlInputObject
{
    private InputPropertyInfo _collectionId;
    private InputPropertyInfo _tokenId;
    private InputPropertyInfo _key;
    private InputPropertyInfo _value;

    /// <summary>
    /// The collection ID containing the token.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? CollectionId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_collectionId.Value;
        set => _collectionId = new() { Name = "collectionId", Value = value };
    }

    /// <summary>
    /// The token ID to set the attribute on.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? TokenId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_tokenId.Value;
        set => _tokenId = new() { Name = "tokenId", Value = value };
    }

    /// <summary>
    /// The attribute key.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Key
    {
        get => (QueryBuilderParameter<string?>?)_key.Value;
        set => _key = new() { Name = "key", Value = value };
    }

    /// <summary>
    /// The attribute value.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Value
    {
        get => (QueryBuilderParameter<string?>?)_value.Value;
        set => _value = new() { Name = "value", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_collectionId.Name != null) yield return _collectionId;
        if (_tokenId.Name != null) yield return _tokenId;
        if (_key.Name != null) yield return _key;
        if (_value.Name != null) yield return _value;
    }
}

