// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Three-state mutation envelope for accountExpiration. action: NO_MUTATION keeps the existing value; CLEAR removes the expiration; SET applies value (in blocks).
/// </summary>
public partial class ShouldMutateAccountExpirationInput : IGraphQlInputObject
{
    private InputPropertyInfo _action;
    private InputPropertyInfo _value;

    /// <summary>
    /// Which mutation to apply.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ShouldMutateAction?>))]
    #endif
    public QueryBuilderParameter<ShouldMutateAction?>? Action
    {
        get => (QueryBuilderParameter<ShouldMutateAction?>?)_action.Value;
        set => _action = new() { Name = "action", Value = value };
    }

    /// <summary>
    /// New account expiration in blocks. Required when action is SET; must be omitted otherwise.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
    #endif
    public QueryBuilderParameter<int?>? Value
    {
        get => (QueryBuilderParameter<int?>?)_value.Value;
        set => _value = new() { Name = "value", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_action.Name != null) yield return _action;
        if (_value.Name != null) yield return _value;
    }
}

