// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for thawing a collection (MultiTokens.thaw with Collection freezeType).
/// </summary>
public partial class ThawCollectionInput : IGraphQlInputObject
{
    private InputPropertyInfo _collectionId;

    /// <summary>
    /// The collection to thaw.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? CollectionId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_collectionId.Value;
        set => _collectionId = new() { Name = "collectionId", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_collectionId.Name != null) yield return _collectionId;
    }
}

