// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Behavior for a token. IS_CURRENCY enables currency metadata (name, symbol, decimalCount). HAS_ROYALTY attaches royalty beneficiaries.
/// </summary>
public partial class TokenBehaviorInput : IGraphQlInputObject
{
    private InputPropertyInfo _type;
    private InputPropertyInfo _name;
    private InputPropertyInfo _symbol;
    private InputPropertyInfo _decimalCount;
    private InputPropertyInfo _royalties;

    /// <summary>
    /// The behavior type: IS_CURRENCY or HAS_ROYALTY.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<TokenBehaviorType?>))]
    #endif
    public QueryBuilderParameter<TokenBehaviorType?>? Type
    {
        get => (QueryBuilderParameter<TokenBehaviorType?>?)_type.Value;
        set => _type = new() { Name = "type", Value = value };
    }

    /// <summary>
    /// Currency name as a plain ASCII string (e.g. "Enjin Coin") or a 0x-prefixed hex string. Required when type is IS_CURRENCY.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Name
    {
        get => (QueryBuilderParameter<string?>?)_name.Value;
        set => _name = new() { Name = "name", Value = value };
    }

    /// <summary>
    /// Currency symbol as a plain ASCII string (e.g. "ENJ") or a 0x-prefixed hex string. Required when type is IS_CURRENCY.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Symbol
    {
        get => (QueryBuilderParameter<string?>?)_symbol.Value;
        set => _symbol = new() { Name = "symbol", Value = value };
    }

    /// <summary>
    /// Decimal precision. Required when type is IS_CURRENCY.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
    #endif
    public QueryBuilderParameter<int?>? DecimalCount
    {
        get => (QueryBuilderParameter<int?>?)_decimalCount.Value;
        set => _decimalCount = new() { Name = "decimalCount", Value = value };
    }

    /// <summary>
    /// Royalty beneficiaries. Required when type is HAS_ROYALTY. Provide one or more.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<RoyaltyInput>?>))]
    #endif
    public QueryBuilderParameter<ICollection<RoyaltyInput>?>? Royalties
    {
        get => (QueryBuilderParameter<ICollection<RoyaltyInput>?>?)_royalties.Value;
        set => _royalties = new() { Name = "royalties", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_type.Name != null) yield return _type;
        if (_name.Name != null) yield return _name;
        if (_symbol.Name != null) yield return _symbol;
        if (_decimalCount.Name != null) yield return _decimalCount;
        if (_royalties.Name != null) yield return _royalties;
    }
}

