// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Supply cap for a token. Use COLLAPSING_SUPPLY with an initial supply value for a token whose supply collapses as it burns, or SUPPLY for a fixed-supply fungible token.
/// </summary>
public partial class TokenCapInput : IGraphQlInputObject
{
    private InputPropertyInfo _type;
    private InputPropertyInfo _supply;

    /// <summary>
    /// The cap type: COLLAPSING_SUPPLY or SUPPLY.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<TokenCapType?>))]
    #endif
    public QueryBuilderParameter<TokenCapType?>? Type
    {
        get => (QueryBuilderParameter<TokenCapType?>?)_type.Value;
        set => _type = new() { Name = "type", Value = value };
    }

    /// <summary>
    /// The maximum token supply. Required when type is COLLAPSING_SUPPLY or SUPPLY.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger?>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger?>? Supply
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger?>?)_supply.Value;
        set => _supply = new() { Name = "supply", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_type.Name != null) yield return _type;
        if (_supply.Name != null) yield return _supply;
    }
}

