// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// A single token entry for batch transfers via MultiTokens.batch_transfer. The collectionId is specified on the parent BatchTransferInput.
/// </summary>
public partial class TransferTokenEntryInput : IGraphQlInputObject
{
    private InputPropertyInfo _address;
    private InputPropertyInfo _tokenId;
    private InputPropertyInfo _amount;

    /// <summary>
    /// The SS58 address or public key of the token recipient.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Address
    {
        get => (QueryBuilderParameter<string?>?)_address.Value;
        set => _address = new() { Name = "address", Value = value };
    }

    /// <summary>
    /// The token ID to transfer.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? TokenId
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_tokenId.Value;
        set => _tokenId = new() { Name = "tokenId", Value = value };
    }

    /// <summary>
    /// The amount of token balance to transfer.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? Amount
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_amount.Value;
        set => _amount = new() { Name = "amount", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_address.Name != null) yield return _address;
        if (_tokenId.Name != null) yield return _tokenId;
        if (_amount.Name != null) yield return _amount;
    }
}

