// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input for a transaction including the method and its corresponding attributes.
/// </summary>
public partial class TransactionInput : IGraphQlInputObject
{
    private InputPropertyInfo _createCollection;
    private InputPropertyInfo _destroyCollection;
    private InputPropertyInfo _mutateCollection;
    private InputPropertyInfo _mutateToken;
    private InputPropertyInfo _createToken;
    private InputPropertyInfo _mintToken;
    private InputPropertyInfo _transferToken;
    private InputPropertyInfo _createTokens;
    private InputPropertyInfo _mintTokens;
    private InputPropertyInfo _batchTransfer;
    private InputPropertyInfo _freezeCollection;
    private InputPropertyInfo _thawCollection;
    private InputPropertyInfo _freezeToken;
    private InputPropertyInfo _thawToken;
    private InputPropertyInfo _burnToken;
    private InputPropertyInfo _infuseToken;
    private InputPropertyInfo _infuseTokens;
    private InputPropertyInfo _transferEnj;
    private InputPropertyInfo _createListing;
    private InputPropertyInfo _cancelListing;
    private InputPropertyInfo _fillListing;
    private InputPropertyInfo _finalizeAuction;
    private InputPropertyInfo _addWhitelistedAccounts;
    private InputPropertyInfo _removeWhitelistedAccounts;
    private InputPropertyInfo _placeBid;
    private InputPropertyInfo _placeCounterOffer;
    private InputPropertyInfo _answerCounterOffer;
    private InputPropertyInfo _createTokenGroup;
    private InputPropertyInfo _destroyTokenGroup;
    private InputPropertyInfo _addTokenToGroup;
    private InputPropertyInfo _removeTokenFromGroup;
    private InputPropertyInfo _setTokenGroups;
    private InputPropertyInfo _setTokenGroupAttribute;
    private InputPropertyInfo _removeTokenGroupAttribute;
    private InputPropertyInfo _setTokenAttribute;
    private InputPropertyInfo _setCollectionAttribute;
    private InputPropertyInfo _removeTokenAttribute;
    private InputPropertyInfo _removeCollectionAttribute;
    private InputPropertyInfo _batchSetCollectionAttribute;
    private InputPropertyInfo _batchSetTokenAttribute;
    private InputPropertyInfo _removeAllCollectionAttributes;
    private InputPropertyInfo _removeAllTokenAttributes;
    private InputPropertyInfo _nominationPoolsBond;
    private InputPropertyInfo _nominationPoolsUnbond;
    private InputPropertyInfo _acceptCollectionTransfer;
    private InputPropertyInfo _cancelCollectionTransfer;

    /// <summary>
    /// Arguments for CREATE_COLLECTION method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CreateCollectionInput?>))]
    #endif
    public QueryBuilderParameter<CreateCollectionInput?>? CreateCollection
    {
        get => (QueryBuilderParameter<CreateCollectionInput?>?)_createCollection.Value;
        set => _createCollection = new() { Name = "createCollection", Value = value };
    }

    /// <summary>
    /// Arguments for DESTROY_COLLECTION method (MultiTokens.destroy_collection). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<DestroyCollectionInput?>))]
    #endif
    public QueryBuilderParameter<DestroyCollectionInput?>? DestroyCollection
    {
        get => (QueryBuilderParameter<DestroyCollectionInput?>?)_destroyCollection.Value;
        set => _destroyCollection = new() { Name = "destroyCollection", Value = value };
    }

    /// <summary>
    /// Arguments for MUTATE_COLLECTION method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<MutateCollectionInput?>))]
    #endif
    public QueryBuilderParameter<MutateCollectionInput?>? MutateCollection
    {
        get => (QueryBuilderParameter<MutateCollectionInput?>?)_mutateCollection.Value;
        set => _mutateCollection = new() { Name = "mutateCollection", Value = value };
    }

    /// <summary>
    /// Arguments for MUTATE_TOKEN method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<MutateTokenInput?>))]
    #endif
    public QueryBuilderParameter<MutateTokenInput?>? MutateToken
    {
        get => (QueryBuilderParameter<MutateTokenInput?>?)_mutateToken.Value;
        set => _mutateToken = new() { Name = "mutateToken", Value = value };
    }

    /// <summary>
    /// Arguments for CREATE_TOKEN method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CreateTokenInput?>))]
    #endif
    public QueryBuilderParameter<CreateTokenInput?>? CreateToken
    {
        get => (QueryBuilderParameter<CreateTokenInput?>?)_createToken.Value;
        set => _createToken = new() { Name = "createToken", Value = value };
    }

    /// <summary>
    /// Arguments for MINT_TOKEN method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<MintTokenInput?>))]
    #endif
    public QueryBuilderParameter<MintTokenInput?>? MintToken
    {
        get => (QueryBuilderParameter<MintTokenInput?>?)_mintToken.Value;
        set => _mintToken = new() { Name = "mintToken", Value = value };
    }

    /// <summary>
    /// Arguments for TRANSFER_TOKEN method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<TransferTokenInput?>))]
    #endif
    public QueryBuilderParameter<TransferTokenInput?>? TransferToken
    {
        get => (QueryBuilderParameter<TransferTokenInput?>?)_transferToken.Value;
        set => _transferToken = new() { Name = "transferToken", Value = value };
    }

    /// <summary>
    /// Arguments for CREATE_TOKENS batch_mint method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CreateTokensInput?>))]
    #endif
    public QueryBuilderParameter<CreateTokensInput?>? CreateTokens
    {
        get => (QueryBuilderParameter<CreateTokensInput?>?)_createTokens.Value;
        set => _createTokens = new() { Name = "createTokens", Value = value };
    }

    /// <summary>
    /// Arguments for MINT_TOKENS batch_mint method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<MintTokensInput?>))]
    #endif
    public QueryBuilderParameter<MintTokensInput?>? MintTokens
    {
        get => (QueryBuilderParameter<MintTokensInput?>?)_mintTokens.Value;
        set => _mintTokens = new() { Name = "mintTokens", Value = value };
    }

    /// <summary>
    /// Arguments for BATCH_TRANSFER method (MultiTokens.batch_transfer). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<BatchTransferInput?>))]
    #endif
    public QueryBuilderParameter<BatchTransferInput?>? BatchTransfer
    {
        get => (QueryBuilderParameter<BatchTransferInput?>?)_batchTransfer.Value;
        set => _batchTransfer = new() { Name = "batchTransfer", Value = value };
    }

    /// <summary>
    /// Arguments for FREEZE_COLLECTION method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<FreezeCollectionInput?>))]
    #endif
    public QueryBuilderParameter<FreezeCollectionInput?>? FreezeCollection
    {
        get => (QueryBuilderParameter<FreezeCollectionInput?>?)_freezeCollection.Value;
        set => _freezeCollection = new() { Name = "freezeCollection", Value = value };
    }

    /// <summary>
    /// Arguments for THAW_COLLECTION method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ThawCollectionInput?>))]
    #endif
    public QueryBuilderParameter<ThawCollectionInput?>? ThawCollection
    {
        get => (QueryBuilderParameter<ThawCollectionInput?>?)_thawCollection.Value;
        set => _thawCollection = new() { Name = "thawCollection", Value = value };
    }

    /// <summary>
    /// Arguments for FREEZE_TOKEN method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<FreezeTokenInput?>))]
    #endif
    public QueryBuilderParameter<FreezeTokenInput?>? FreezeToken
    {
        get => (QueryBuilderParameter<FreezeTokenInput?>?)_freezeToken.Value;
        set => _freezeToken = new() { Name = "freezeToken", Value = value };
    }

    /// <summary>
    /// Arguments for THAW_TOKEN method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<ThawTokenInput?>))]
    #endif
    public QueryBuilderParameter<ThawTokenInput?>? ThawToken
    {
        get => (QueryBuilderParameter<ThawTokenInput?>?)_thawToken.Value;
        set => _thawToken = new() { Name = "thawToken", Value = value };
    }

    /// <summary>
    /// Arguments for BURN_TOKEN method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<BurnTokenInput?>))]
    #endif
    public QueryBuilderParameter<BurnTokenInput?>? BurnToken
    {
        get => (QueryBuilderParameter<BurnTokenInput?>?)_burnToken.Value;
        set => _burnToken = new() { Name = "burnToken", Value = value };
    }

    /// <summary>
    /// Arguments for INFUSE_TOKEN method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<InfuseTokenInput?>))]
    #endif
    public QueryBuilderParameter<InfuseTokenInput?>? InfuseToken
    {
        get => (QueryBuilderParameter<InfuseTokenInput?>?)_infuseToken.Value;
        set => _infuseToken = new() { Name = "infuseToken", Value = value };
    }

    /// <summary>
    /// Arguments for INFUSE_TOKENS batch_infuse method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<InfuseTokensInput?>))]
    #endif
    public QueryBuilderParameter<InfuseTokensInput?>? InfuseTokens
    {
        get => (QueryBuilderParameter<InfuseTokensInput?>?)_infuseTokens.Value;
        set => _infuseTokens = new() { Name = "infuseTokens", Value = value };
    }

    /// <summary>
    /// Arguments for TRANSFER_ENJ method (Balances.transfer_keep_alive). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<TransferEnjInput?>))]
    #endif
    public QueryBuilderParameter<TransferEnjInput?>? TransferEnj
    {
        get => (QueryBuilderParameter<TransferEnjInput?>?)_transferEnj.Value;
        set => _transferEnj = new() { Name = "transferEnj", Value = value };
    }

    /// <summary>
    /// Arguments for CREATE_LISTING method (Marketplace.create_listing). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CreateListingInput?>))]
    #endif
    public QueryBuilderParameter<CreateListingInput?>? CreateListing
    {
        get => (QueryBuilderParameter<CreateListingInput?>?)_createListing.Value;
        set => _createListing = new() { Name = "createListing", Value = value };
    }

    /// <summary>
    /// Arguments for CANCEL_LISTING method (Marketplace.cancel_listing). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CancelListingInput?>))]
    #endif
    public QueryBuilderParameter<CancelListingInput?>? CancelListing
    {
        get => (QueryBuilderParameter<CancelListingInput?>?)_cancelListing.Value;
        set => _cancelListing = new() { Name = "cancelListing", Value = value };
    }

    /// <summary>
    /// Arguments for FILL_LISTING method (Marketplace.fill_listing). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<FillListingInput?>))]
    #endif
    public QueryBuilderParameter<FillListingInput?>? FillListing
    {
        get => (QueryBuilderParameter<FillListingInput?>?)_fillListing.Value;
        set => _fillListing = new() { Name = "fillListing", Value = value };
    }

    /// <summary>
    /// Arguments for FINALIZE_AUCTION method (Marketplace.finalize_auction). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<FinalizeAuctionInput?>))]
    #endif
    public QueryBuilderParameter<FinalizeAuctionInput?>? FinalizeAuction
    {
        get => (QueryBuilderParameter<FinalizeAuctionInput?>?)_finalizeAuction.Value;
        set => _finalizeAuction = new() { Name = "finalizeAuction", Value = value };
    }

    /// <summary>
    /// Arguments for ADD_WHITELISTED_ACCOUNTS method (Marketplace.add_whitelisted_accounts). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<AddWhitelistedAccountsInput?>))]
    #endif
    public QueryBuilderParameter<AddWhitelistedAccountsInput?>? AddWhitelistedAccounts
    {
        get => (QueryBuilderParameter<AddWhitelistedAccountsInput?>?)_addWhitelistedAccounts.Value;
        set => _addWhitelistedAccounts = new() { Name = "addWhitelistedAccounts", Value = value };
    }

    /// <summary>
    /// Arguments for REMOVE_WHITELISTED_ACCOUNTS method (Marketplace.remove_whitelisted_accounts). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<RemoveWhitelistedAccountsInput?>))]
    #endif
    public QueryBuilderParameter<RemoveWhitelistedAccountsInput?>? RemoveWhitelistedAccounts
    {
        get => (QueryBuilderParameter<RemoveWhitelistedAccountsInput?>?)_removeWhitelistedAccounts.Value;
        set => _removeWhitelistedAccounts = new() { Name = "removeWhitelistedAccounts", Value = value };
    }

    /// <summary>
    /// Arguments for PLACE_BID method (Marketplace.place_bid). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<PlaceBidInput?>))]
    #endif
    public QueryBuilderParameter<PlaceBidInput?>? PlaceBid
    {
        get => (QueryBuilderParameter<PlaceBidInput?>?)_placeBid.Value;
        set => _placeBid = new() { Name = "placeBid", Value = value };
    }

    /// <summary>
    /// Arguments for PLACE_COUNTER_OFFER method (Marketplace.place_counter_offer). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<PlaceCounterOfferInput?>))]
    #endif
    public QueryBuilderParameter<PlaceCounterOfferInput?>? PlaceCounterOffer
    {
        get => (QueryBuilderParameter<PlaceCounterOfferInput?>?)_placeCounterOffer.Value;
        set => _placeCounterOffer = new() { Name = "placeCounterOffer", Value = value };
    }

    /// <summary>
    /// Arguments for ANSWER_COUNTER_OFFER method (Marketplace.answer_counter_offer). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<AnswerCounterOfferInput?>))]
    #endif
    public QueryBuilderParameter<AnswerCounterOfferInput?>? AnswerCounterOffer
    {
        get => (QueryBuilderParameter<AnswerCounterOfferInput?>?)_answerCounterOffer.Value;
        set => _answerCounterOffer = new() { Name = "answerCounterOffer", Value = value };
    }

    /// <summary>
    /// Arguments for CREATE_TOKEN_GROUP method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CreateTokenGroupInput?>))]
    #endif
    public QueryBuilderParameter<CreateTokenGroupInput?>? CreateTokenGroup
    {
        get => (QueryBuilderParameter<CreateTokenGroupInput?>?)_createTokenGroup.Value;
        set => _createTokenGroup = new() { Name = "createTokenGroup", Value = value };
    }

    /// <summary>
    /// Arguments for DESTROY_TOKEN_GROUP method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<DestroyTokenGroupInput?>))]
    #endif
    public QueryBuilderParameter<DestroyTokenGroupInput?>? DestroyTokenGroup
    {
        get => (QueryBuilderParameter<DestroyTokenGroupInput?>?)_destroyTokenGroup.Value;
        set => _destroyTokenGroup = new() { Name = "destroyTokenGroup", Value = value };
    }

    /// <summary>
    /// Arguments for ADD_TOKEN_TO_GROUP method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<AddTokenToGroupInput?>))]
    #endif
    public QueryBuilderParameter<AddTokenToGroupInput?>? AddTokenToGroup
    {
        get => (QueryBuilderParameter<AddTokenToGroupInput?>?)_addTokenToGroup.Value;
        set => _addTokenToGroup = new() { Name = "addTokenToGroup", Value = value };
    }

    /// <summary>
    /// Arguments for REMOVE_TOKEN_FROM_GROUP method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<RemoveTokenFromGroupInput?>))]
    #endif
    public QueryBuilderParameter<RemoveTokenFromGroupInput?>? RemoveTokenFromGroup
    {
        get => (QueryBuilderParameter<RemoveTokenFromGroupInput?>?)_removeTokenFromGroup.Value;
        set => _removeTokenFromGroup = new() { Name = "removeTokenFromGroup", Value = value };
    }

    /// <summary>
    /// Arguments for SET_TOKEN_GROUPS method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<SetTokenGroupsInput?>))]
    #endif
    public QueryBuilderParameter<SetTokenGroupsInput?>? SetTokenGroups
    {
        get => (QueryBuilderParameter<SetTokenGroupsInput?>?)_setTokenGroups.Value;
        set => _setTokenGroups = new() { Name = "setTokenGroups", Value = value };
    }

    /// <summary>
    /// Arguments for SET_TOKEN_GROUP_ATTRIBUTE method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<SetTokenGroupAttributeInput?>))]
    #endif
    public QueryBuilderParameter<SetTokenGroupAttributeInput?>? SetTokenGroupAttribute
    {
        get => (QueryBuilderParameter<SetTokenGroupAttributeInput?>?)_setTokenGroupAttribute.Value;
        set => _setTokenGroupAttribute = new() { Name = "setTokenGroupAttribute", Value = value };
    }

    /// <summary>
    /// Arguments for REMOVE_TOKEN_GROUP_ATTRIBUTE method. Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<RemoveTokenGroupAttributeInput?>))]
    #endif
    public QueryBuilderParameter<RemoveTokenGroupAttributeInput?>? RemoveTokenGroupAttribute
    {
        get => (QueryBuilderParameter<RemoveTokenGroupAttributeInput?>?)_removeTokenGroupAttribute.Value;
        set => _removeTokenGroupAttribute = new() { Name = "removeTokenGroupAttribute", Value = value };
    }

    /// <summary>
    /// Arguments for SET_TOKEN_ATTRIBUTE method (MultiTokens.set_attribute). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<SetTokenAttributeInput?>))]
    #endif
    public QueryBuilderParameter<SetTokenAttributeInput?>? SetTokenAttribute
    {
        get => (QueryBuilderParameter<SetTokenAttributeInput?>?)_setTokenAttribute.Value;
        set => _setTokenAttribute = new() { Name = "setTokenAttribute", Value = value };
    }

    /// <summary>
    /// Arguments for SET_COLLECTION_ATTRIBUTE method (MultiTokens.set_attribute). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<SetCollectionAttributeInput?>))]
    #endif
    public QueryBuilderParameter<SetCollectionAttributeInput?>? SetCollectionAttribute
    {
        get => (QueryBuilderParameter<SetCollectionAttributeInput?>?)_setCollectionAttribute.Value;
        set => _setCollectionAttribute = new() { Name = "setCollectionAttribute", Value = value };
    }

    /// <summary>
    /// Arguments for REMOVE_TOKEN_ATTRIBUTE method (MultiTokens.remove_attribute). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<RemoveTokenAttributeInput?>))]
    #endif
    public QueryBuilderParameter<RemoveTokenAttributeInput?>? RemoveTokenAttribute
    {
        get => (QueryBuilderParameter<RemoveTokenAttributeInput?>?)_removeTokenAttribute.Value;
        set => _removeTokenAttribute = new() { Name = "removeTokenAttribute", Value = value };
    }

    /// <summary>
    /// Arguments for REMOVE_COLLECTION_ATTRIBUTE method (MultiTokens.remove_attribute). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<RemoveCollectionAttributeInput?>))]
    #endif
    public QueryBuilderParameter<RemoveCollectionAttributeInput?>? RemoveCollectionAttribute
    {
        get => (QueryBuilderParameter<RemoveCollectionAttributeInput?>?)_removeCollectionAttribute.Value;
        set => _removeCollectionAttribute = new() { Name = "removeCollectionAttribute", Value = value };
    }

    /// <summary>
    /// Arguments for BATCH_SET_ATTRIBUTE method on a collection (MultiTokens.batch_set_attribute). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<BatchSetCollectionAttributeInput?>))]
    #endif
    public QueryBuilderParameter<BatchSetCollectionAttributeInput?>? BatchSetCollectionAttribute
    {
        get => (QueryBuilderParameter<BatchSetCollectionAttributeInput?>?)_batchSetCollectionAttribute.Value;
        set => _batchSetCollectionAttribute = new() { Name = "batchSetCollectionAttribute", Value = value };
    }

    /// <summary>
    /// Arguments for BATCH_SET_ATTRIBUTE method on a token (MultiTokens.batch_set_attribute). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<BatchSetTokenAttributeInput?>))]
    #endif
    public QueryBuilderParameter<BatchSetTokenAttributeInput?>? BatchSetTokenAttribute
    {
        get => (QueryBuilderParameter<BatchSetTokenAttributeInput?>?)_batchSetTokenAttribute.Value;
        set => _batchSetTokenAttribute = new() { Name = "batchSetTokenAttribute", Value = value };
    }

    /// <summary>
    /// Arguments for REMOVE_ALL_ATTRIBUTES method on a collection (MultiTokens.remove_all_attributes). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<RemoveAllCollectionAttributesInput?>))]
    #endif
    public QueryBuilderParameter<RemoveAllCollectionAttributesInput?>? RemoveAllCollectionAttributes
    {
        get => (QueryBuilderParameter<RemoveAllCollectionAttributesInput?>?)_removeAllCollectionAttributes.Value;
        set => _removeAllCollectionAttributes = new() { Name = "removeAllCollectionAttributes", Value = value };
    }

    /// <summary>
    /// Arguments for REMOVE_ALL_ATTRIBUTES method on a token (MultiTokens.remove_all_attributes). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<RemoveAllTokenAttributesInput?>))]
    #endif
    public QueryBuilderParameter<RemoveAllTokenAttributesInput?>? RemoveAllTokenAttributes
    {
        get => (QueryBuilderParameter<RemoveAllTokenAttributesInput?>?)_removeAllTokenAttributes.Value;
        set => _removeAllTokenAttributes = new() { Name = "removeAllTokenAttributes", Value = value };
    }

    /// <summary>
    /// Arguments for NOMINATION_POOLS_BOND method (NominationPools.bond). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<NominationPoolsBondInput?>))]
    #endif
    public QueryBuilderParameter<NominationPoolsBondInput?>? NominationPoolsBond
    {
        get => (QueryBuilderParameter<NominationPoolsBondInput?>?)_nominationPoolsBond.Value;
        set => _nominationPoolsBond = new() { Name = "nominationPoolsBond", Value = value };
    }

    /// <summary>
    /// Arguments for NOMINATION_POOLS_UNBOND method (NominationPools.unbond). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<NominationPoolsUnbondInput?>))]
    #endif
    public QueryBuilderParameter<NominationPoolsUnbondInput?>? NominationPoolsUnbond
    {
        get => (QueryBuilderParameter<NominationPoolsUnbondInput?>?)_nominationPoolsUnbond.Value;
        set => _nominationPoolsUnbond = new() { Name = "nominationPoolsUnbond", Value = value };
    }

    /// <summary>
    /// Arguments for ACCEPT_COLLECTION_TRANSFER method (MultiTokens.accept_collection_transfer). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<AcceptCollectionTransferInput?>))]
    #endif
    public QueryBuilderParameter<AcceptCollectionTransferInput?>? AcceptCollectionTransfer
    {
        get => (QueryBuilderParameter<AcceptCollectionTransferInput?>?)_acceptCollectionTransfer.Value;
        set => _acceptCollectionTransfer = new() { Name = "acceptCollectionTransfer", Value = value };
    }

    /// <summary>
    /// Arguments for CANCEL_COLLECTION_TRANSFER method (MultiTokens.cancel_collection_transfer). Provide only one specific input object per transaction.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<CancelCollectionTransferInput?>))]
    #endif
    public QueryBuilderParameter<CancelCollectionTransferInput?>? CancelCollectionTransfer
    {
        get => (QueryBuilderParameter<CancelCollectionTransferInput?>?)_cancelCollectionTransfer.Value;
        set => _cancelCollectionTransfer = new() { Name = "cancelCollectionTransfer", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_createCollection.Name != null) yield return _createCollection;
        if (_destroyCollection.Name != null) yield return _destroyCollection;
        if (_mutateCollection.Name != null) yield return _mutateCollection;
        if (_mutateToken.Name != null) yield return _mutateToken;
        if (_createToken.Name != null) yield return _createToken;
        if (_mintToken.Name != null) yield return _mintToken;
        if (_transferToken.Name != null) yield return _transferToken;
        if (_createTokens.Name != null) yield return _createTokens;
        if (_mintTokens.Name != null) yield return _mintTokens;
        if (_batchTransfer.Name != null) yield return _batchTransfer;
        if (_freezeCollection.Name != null) yield return _freezeCollection;
        if (_thawCollection.Name != null) yield return _thawCollection;
        if (_freezeToken.Name != null) yield return _freezeToken;
        if (_thawToken.Name != null) yield return _thawToken;
        if (_burnToken.Name != null) yield return _burnToken;
        if (_infuseToken.Name != null) yield return _infuseToken;
        if (_infuseTokens.Name != null) yield return _infuseTokens;
        if (_transferEnj.Name != null) yield return _transferEnj;
        if (_createListing.Name != null) yield return _createListing;
        if (_cancelListing.Name != null) yield return _cancelListing;
        if (_fillListing.Name != null) yield return _fillListing;
        if (_finalizeAuction.Name != null) yield return _finalizeAuction;
        if (_addWhitelistedAccounts.Name != null) yield return _addWhitelistedAccounts;
        if (_removeWhitelistedAccounts.Name != null) yield return _removeWhitelistedAccounts;
        if (_placeBid.Name != null) yield return _placeBid;
        if (_placeCounterOffer.Name != null) yield return _placeCounterOffer;
        if (_answerCounterOffer.Name != null) yield return _answerCounterOffer;
        if (_createTokenGroup.Name != null) yield return _createTokenGroup;
        if (_destroyTokenGroup.Name != null) yield return _destroyTokenGroup;
        if (_addTokenToGroup.Name != null) yield return _addTokenToGroup;
        if (_removeTokenFromGroup.Name != null) yield return _removeTokenFromGroup;
        if (_setTokenGroups.Name != null) yield return _setTokenGroups;
        if (_setTokenGroupAttribute.Name != null) yield return _setTokenGroupAttribute;
        if (_removeTokenGroupAttribute.Name != null) yield return _removeTokenGroupAttribute;
        if (_setTokenAttribute.Name != null) yield return _setTokenAttribute;
        if (_setCollectionAttribute.Name != null) yield return _setCollectionAttribute;
        if (_removeTokenAttribute.Name != null) yield return _removeTokenAttribute;
        if (_removeCollectionAttribute.Name != null) yield return _removeCollectionAttribute;
        if (_batchSetCollectionAttribute.Name != null) yield return _batchSetCollectionAttribute;
        if (_batchSetTokenAttribute.Name != null) yield return _batchSetTokenAttribute;
        if (_removeAllCollectionAttributes.Name != null) yield return _removeAllCollectionAttributes;
        if (_removeAllTokenAttributes.Name != null) yield return _removeAllTokenAttributes;
        if (_nominationPoolsBond.Name != null) yield return _nominationPoolsBond;
        if (_nominationPoolsUnbond.Name != null) yield return _nominationPoolsUnbond;
        if (_acceptCollectionTransfer.Name != null) yield return _acceptCollectionTransfer;
        if (_cancelCollectionTransfer.Name != null) yield return _cancelCollectionTransfer;
    }
}

