// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input for transferring native ENJ via Balances.transfer_keep_alive.
/// </summary>
public partial class TransferEnjInput : IGraphQlInputObject
{
    private InputPropertyInfo _recipient;
    private InputPropertyInfo _amount;

    /// <summary>
    /// The SS58 address or public key of the ENJ recipient.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Recipient
    {
        get => (QueryBuilderParameter<string?>?)_recipient.Value;
        set => _recipient = new() { Name = "recipient", Value = value };
    }

    /// <summary>
    /// The amount of ENJ to transfer, expressed as whole ENJ (integer; converted to base units on-chain).
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? Amount
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_amount.Value;
        set => _amount = new() { Name = "amount", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_recipient.Name != null) yield return _recipient;
        if (_amount.Name != null) yield return _amount;
    }
}

