// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Input data for revoking an operator approval on a collection (MultiTokens.unapprove_collection).
/// </summary>
public partial class UnapproveCollectionInput : IGraphQlInputObject
{
    private InputPropertyInfo _id;
    private InputPropertyInfo _operator;

    /// <summary>
    /// The collection to revoke the operator approval on.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger>? Id
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger>?)_id.Value;
        set => _id = new() { Name = "id", Value = value };
    }

    /// <summary>
    /// The SS58 address or public key of the operator whose approval is being revoked.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Operator
    {
        get => (QueryBuilderParameter<string?>?)_operator.Value;
        set => _operator = new() { Name = "operator", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_id.Name != null) yield return _id;
        if (_operator.Name != null) yield return _operator;
    }
}

