// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// Controls whether the fuel tank reserves account-creation deposits and existential deposits on behalf of users.
/// </summary>
public partial class UserAccountManagementInput : IGraphQlInputObject
{
    private InputPropertyInfo _tankReservesAccountCreationDeposit;
    private InputPropertyInfo _tankReservesExistentialDeposit;

    /// <summary>
    /// If true, the fuel tank pays the account-creation deposit for new user accounts.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
    #endif
    public QueryBuilderParameter<bool?>? TankReservesAccountCreationDeposit
    {
        get => (QueryBuilderParameter<bool?>?)_tankReservesAccountCreationDeposit.Value;
        set => _tankReservesAccountCreationDeposit = new() { Name = "tankReservesAccountCreationDeposit", Value = value };
    }

    /// <summary>
    /// If true, the fuel tank pays the existential deposit for new user accounts.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
    #endif
    public QueryBuilderParameter<bool?>? TankReservesExistentialDeposit
    {
        get => (QueryBuilderParameter<bool?>?)_tankReservesExistentialDeposit.Value;
        set => _tankReservesExistentialDeposit = new() { Name = "tankReservesExistentialDeposit", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_tankReservesAccountCreationDeposit.Name != null) yield return _tankReservesAccountCreationDeposit;
        if (_tankReservesExistentialDeposit.Name != null) yield return _tankReservesExistentialDeposit;
    }
}

