// <auto-generated> This file has been auto generated. </auto-generated>
#nullable enable annotations

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace Enjin.Platform.Sdk;

/// <summary>
/// An account entry for a listing whitelist, with optional allowance.
/// </summary>
public partial class WhitelistedAccountInput : IGraphQlInputObject
{
    private InputPropertyInfo _address;
    private InputPropertyInfo _allowance;

    /// <summary>
    /// The SS58 address or public key of the whitelisted account.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<string?>))]
    #endif
    public QueryBuilderParameter<string?>? Address
    {
        get => (QueryBuilderParameter<string?>?)_address.Value;
        set => _address = new() { Name = "address", Value = value };
    }

    /// <summary>
    /// Optional allowance for how much of the listing this account may fill.
    /// </summary>
    #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
    [JsonConverter(typeof(QueryBuilderParameterConverter<global::System.Numerics.BigInteger?>))]
    #endif
    public QueryBuilderParameter<global::System.Numerics.BigInteger?>? Allowance
    {
        get => (QueryBuilderParameter<global::System.Numerics.BigInteger?>?)_allowance.Value;
        set => _allowance = new() { Name = "allowance", Value = value };
    }

    IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
    {
        if (_address.Name != null) yield return _address;
        if (_allowance.Name != null) yield return _allowance;
    }
}

